create table if not exists public.gptq_paper_daily_snapshots(
id bigint generated by default as identity primary key,run_key text not null unique,run_date date not null,strategy_version text not null,mode text not null,
status text not null,pipeline_status text not null,phase22_status text,phase21_status text,phase23_status text,phase24_status text,latest_market_date date,
signals_eligible integer not null default 0,top_symbol text,top_score numeric,orders_created integer not null default 0,positions_open integer not null default 0,
cash numeric not null default 0,market_value numeric not null default 0,equity numeric not null default 0,realized_pnl numeric not null default 0,unrealized_pnl numeric not null default 0,
positions jsonb not null default '[]'::jsonb,top_candidates jsonb not null default '[]'::jsonb,raw_summary jsonb not null default '{}'::jsonb,completed_at timestamptz,created_at timestamptz not null default now());
alter table public.gptq_paper_daily_snapshots enable row level security;
drop policy if exists "paper_dashboard_read_daily_snapshots" on public.gptq_paper_daily_snapshots;
create policy "paper_dashboard_read_daily_snapshots" on public.gptq_paper_daily_snapshots for select to anon using(true);
create or replace view public.gptq_paper_dashboard_latest as select * from public.gptq_paper_daily_snapshots order by completed_at desc nulls last,created_at desc limit 1;
grant select on public.gptq_paper_daily_snapshots,public.gptq_paper_dashboard_latest to anon,authenticated;
notify pgrst,'reload schema';
