-- GPT Quant V9.2 Paper Trading Phase 2.5
-- Automatic Trading Orchestrator database upgrade

create table if not exists public.gptq_paper_orchestrator_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  strategy_version text not null,
  mode text not null default 'SHADOW_ONLY_NO_BROKER',
  status text not null default 'RUNNING',
  pipeline_status text not null default 'STARTING',
  latest_market_date date,
  market_data_status text,
  result jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists gptq_paper_orchestrator_runs_created_at_idx
on public.gptq_paper_orchestrator_runs(created_at desc);

alter table public.gptq_paper_orchestrator_runs enable row level security;

drop policy if exists "paper_dashboard_read_orchestrator_runs"
on public.gptq_paper_orchestrator_runs;

create policy "paper_dashboard_read_orchestrator_runs"
on public.gptq_paper_orchestrator_runs
for select to anon using (true);
