begin;

create table if not exists public.paper_qualification_recovery_audit_v92 (
    id bigint generated by default as identity primary key,
    recovery_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',

    previous_state text not null,
    target_state text not null,
    recovery_allowed boolean not null default false,
    state_transition boolean not null default false,
    autonomous_paper_operations_authorized boolean not null default false,

    revalidated_score numeric not null default 0,
    critical_failures jsonb not null default '[]'::jsonb,
    warning_failures jsonb not null default '[]'::jsonb,
    reason_codes jsonb not null default '[]'::jsonb,

    evidence_sha256 text not null,

    paper_only boolean not null default true,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase3653_target_state
        check (target_state in (
            'QUALIFIED',
            'QUALIFIED_WITH_OBSERVATION',
            'NOT_QUALIFIED',
            'REVOKED',
            'FAIL_CLOSED'
        )),
    constraint ck_phase3653_paper_only
        check (paper_only = true),
    constraint ck_phase3653_no_broker_submission
        check (broker_order_submission_enabled = false),
    constraint ck_phase3653_no_real_money
        check (real_money_trading_enabled = false),
    constraint ck_phase3653_no_live_release
        check (live_money_release_authorized = false),
    constraint ck_phase3653_fail_closed
        check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_qualification_recovery_audit_v92_portfolio_date
    on public.paper_qualification_recovery_audit_v92 (portfolio_id, recovery_date);

create index if not exists ix_paper_qualification_recovery_audit_v92_transition
    on public.paper_qualification_recovery_audit_v92
    (state_transition, recovery_date desc);

comment on table public.paper_qualification_recovery_audit_v92 is
'GPT Quant V9.2 Phase 3.6.5.3 explicit fail-closed qualification recovery audit. Paper-only; broker and real-money authorization hard-disabled.';

commit;