-- GPT Quant V9.2
-- Phase 3.7.7 — Production Paper Qualification Evidence Persistence + Cross-Run Accumulation
-- Append-safe / idempotent evidence ledger for Production Paper qualification.

create table if not exists public.paper_production_qualification_evidence_v92 (
    id bigint generated by default as identity primary key,
    portfolio_id text not null,
    strategy_version text not null,
    cycle_date date not null,
    cycle_state text not null,
    valid_cycle boolean not null default false,
    blocked_cycle boolean not null default false,
    runtime_supervision_pass boolean not null default false,
    paper_only_boundary_pass boolean not null default false,
    trade_activity_observed boolean not null default false,
    source_workflow text not null,
    source_run_id text not null,
    source_run_attempt integer not null default 1,
    source_commit_sha text,
    evidence_hash text not null,
    raw_evidence jsonb not null default '{}'::jsonb,
    observed_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists uq_paper_production_qualification_evidence_v92_cycle
on public.paper_production_qualification_evidence_v92
(portfolio_id, strategy_version, cycle_date);

create unique index if not exists uq_paper_production_qualification_evidence_v92_hash
on public.paper_production_qualification_evidence_v92
(evidence_hash);

create index if not exists ix_paper_production_qualification_evidence_v92_portfolio_date
on public.paper_production_qualification_evidence_v92
(portfolio_id, strategy_version, cycle_date desc);

create or replace function public.touch_paper_production_qualification_evidence_v92()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_touch_paper_production_qualification_evidence_v92
on public.paper_production_qualification_evidence_v92;

create trigger trg_touch_paper_production_qualification_evidence_v92
before update on public.paper_production_qualification_evidence_v92
for each row execute function public.touch_paper_production_qualification_evidence_v92();

alter table public.paper_production_qualification_evidence_v92 enable row level security;

revoke all on table public.paper_production_qualification_evidence_v92 from anon, authenticated;
grant select, insert, update on table public.paper_production_qualification_evidence_v92 to service_role;

comment on table public.paper_production_qualification_evidence_v92 is
'GPT Quant Phase 3.7.7 canonical Production Paper qualification evidence ledger. One logical cycle per portfolio/strategy/date. Paper-only. No broker or real-money execution.';

notify pgrst, 'reload schema';

select
  'PHASE377_READY' as phase377_state,
  to_regclass('public.paper_production_qualification_evidence_v92') as canonical_table;
