begin;

create table if not exists public.paper_true_safety_revocation_reconciliation_v92 (
    id bigint generated by default as identity primary key,
    reconciliation_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE3723_TRUE_SAFETY_REVOCATION_ROOT_CAUSE_RECONCILIATION',

    classification text not null,
    canonical_recovery_authorized boolean not null default false,
    historical_rewrite_allowed boolean not null default false,

    supervision_table text,
    supervision_state text not null default 'MISSING',
    controller_state text not null default 'MISSING',
    lifecycle_state text not null default 'MISSING',

    supervision_date date,
    controller_date date,
    lifecycle_date date,

    supervision_revoked boolean not null default false,
    controller_revoked boolean not null default false,
    lifecycle_revoked boolean not null default false,

    true_violations jsonb not null default '[]'::jsonb,
    stale_indicators jsonb not null default '[]'::jsonb,
    reason_codes jsonb not null default '[]'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase3723_classification check (
        classification in (
            'TRUE_SAFETY_VIOLATION',
            'STALE_OR_FALSE_REVOCATION',
            'NEEDS_REVIEW',
            'NO_ACTIVE_REVOCATION'
        )
    ),
    constraint ck_phase3723_no_history_rewrite check (historical_rewrite_allowed = false),
    constraint ck_phase3723_paper_only check (paper_only = true),
    constraint ck_phase3723_no_broker_api check (broker_api_used = false),
    constraint ck_phase3723_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase3723_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase3723_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase3723_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase3723_fail_closed check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_true_safety_revocation_reconciliation_v92_portfolio_date
    on public.paper_true_safety_revocation_reconciliation_v92 (portfolio_id, reconciliation_date);

create table if not exists public.paper_true_safety_revocation_reconciliation_audit_v92 (
    id bigint generated by default as identity primary key,
    reconciliation_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE3723_TRUE_SAFETY_REVOCATION_ROOT_CAUSE_RECONCILIATION',

    classification text not null,
    canonical_recovery_authorized boolean not null default false,
    historical_rewrite_allowed boolean not null default false,

    supervision_table text,
    supervision_state text not null default 'MISSING',
    controller_state text not null default 'MISSING',
    lifecycle_state text not null default 'MISSING',

    supervision_date date,
    controller_date date,
    lifecycle_date date,

    supervision_revoked boolean not null default false,
    controller_revoked boolean not null default false,
    lifecycle_revoked boolean not null default false,

    true_violations jsonb not null default '[]'::jsonb,
    stale_indicators jsonb not null default '[]'::jsonb,
    reason_codes jsonb not null default '[]'::jsonb,
    evidence_document jsonb not null default '{}'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),

    constraint ck_phase3723_audit_no_history_rewrite check (historical_rewrite_allowed = false),
    constraint ck_phase3723_audit_paper_only check (paper_only = true),
    constraint ck_phase3723_audit_no_broker_api check (broker_api_used = false),
    constraint ck_phase3723_audit_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase3723_audit_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase3723_audit_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase3723_audit_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase3723_audit_fail_closed check (fail_closed_policy = true)
);

create index if not exists ix_paper_true_safety_revocation_reconciliation_audit_v92_portfolio_created
    on public.paper_true_safety_revocation_reconciliation_audit_v92 (portfolio_id, created_at desc);

alter table public.paper_true_safety_revocation_reconciliation_v92 enable row level security;
alter table public.paper_true_safety_revocation_reconciliation_audit_v92 enable row level security;

comment on table public.paper_true_safety_revocation_reconciliation_v92 is
'GPT Quant V9.2 Phase 3.7.2.3 true safety revocation root-cause reconciliation state.';

comment on table public.paper_true_safety_revocation_reconciliation_audit_v92 is
'GPT Quant V9.2 Phase 3.7.2.3 immutable-style true safety revocation reconciliation audit evidence.';

notify pgrst, 'reload schema';

commit;