begin;

create table if not exists public.paper_stale_legacy_safety_recovery_authorization_v92 (
    id bigint generated by default as identity primary key,
    recovery_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE3725_STALE_LEGACY_SAFETY_STATE_CONTROLLED_CANONICAL_RECOVERY',

    forensic_classification text not null,
    recovery_eligible boolean not null default false,
    recovery_state text not null,

    previous_supervision_state text not null,
    target_supervision_state text not null,
    historical_rewrite_allowed boolean not null default false,

    forensic_evidence_sha256 text,
    previous_supervision_evidence_sha256 text,
    recovery_evidence_sha256 text not null,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    created_at timestamptz not null default now(),

    constraint ck_phase3725_forensic_classification check (
        forensic_classification = 'RECOVERY_ELIGIBLE_STALE_OR_LEGACY'
    ),
    constraint ck_phase3725_recovery_eligible check (recovery_eligible = true),
    constraint ck_phase3725_recovery_state check (
        recovery_state = 'RECOVERED_CONTINUE_ACTIVE'
    ),
    constraint ck_phase3725_target_state check (
        target_supervision_state = 'CONTINUE_ACTIVE'
    ),
    constraint ck_phase3725_no_history_rewrite check (historical_rewrite_allowed = false),
    constraint ck_phase3725_paper_only check (paper_only = true),
    constraint ck_phase3725_no_broker_api check (broker_api_used = false),
    constraint ck_phase3725_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase3725_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase3725_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase3725_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase3725_fail_closed check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_stale_legacy_safety_recovery_authorization_v92_portfolio_date
    on public.paper_stale_legacy_safety_recovery_authorization_v92 (portfolio_id, recovery_date);

create table if not exists public.paper_stale_legacy_safety_recovery_audit_v92 (
    id bigint generated by default as identity primary key,
    recovery_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE3725_STALE_LEGACY_SAFETY_STATE_CONTROLLED_CANONICAL_RECOVERY',

    forensic_classification text not null,
    recovery_eligible boolean not null default false,
    recovery_state text not null,

    previous_supervision_state text not null,
    target_supervision_state text not null,
    historical_rewrite_allowed boolean not null default false,

    forensic_evidence_sha256 text,
    previous_supervision_evidence_sha256 text,
    recovery_evidence_sha256 text not null,

    recovery_evidence jsonb not null default '{}'::jsonb,
    new_supervision_row_sha256 text not null,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    created_at timestamptz not null default now(),

    constraint ck_phase3725_audit_no_history_rewrite check (historical_rewrite_allowed = false),
    constraint ck_phase3725_audit_paper_only check (paper_only = true),
    constraint ck_phase3725_audit_no_broker_api check (broker_api_used = false),
    constraint ck_phase3725_audit_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase3725_audit_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase3725_audit_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase3725_audit_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase3725_audit_fail_closed check (fail_closed_policy = true)
);

create index if not exists ix_paper_stale_legacy_safety_recovery_audit_v92_portfolio_created
    on public.paper_stale_legacy_safety_recovery_audit_v92 (portfolio_id, created_at desc);

alter table public.paper_stale_legacy_safety_recovery_authorization_v92 enable row level security;
alter table public.paper_stale_legacy_safety_recovery_audit_v92 enable row level security;

comment on table public.paper_stale_legacy_safety_recovery_authorization_v92 is
'GPT Quant V9.2 Phase 3.7.2.5 controlled paper-only canonical recovery authorization.';

comment on table public.paper_stale_legacy_safety_recovery_audit_v92 is
'GPT Quant V9.2 Phase 3.7.2.5 immutable-style controlled recovery audit evidence.';

notify pgrst, 'reload schema';

commit;