begin;

create table if not exists public.paper_daily_autonomous_controller_v92 (
    id bigint generated by default as identity primary key,
    controller_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE368_PRODUCTION_PAPER_DAILY_AUTONOMOUS_OPERATIONS_CONTROLLER',

    controller_state text not null,
    controller_passed boolean not null default false,
    autonomous_daily_operations_authorized boolean not null default false,
    daily_paper_cycle_executed boolean not null default false,

    activation_state text not null default 'UNKNOWN',
    qualification_state text not null default 'UNKNOWN',
    runtime_supervision_state text not null default 'UNKNOWN',
    runtime_supervision_score numeric not null default 0,
    master_cycle_state text not null default 'UNKNOWN',
    master_exit_code integer not null default 0,
    safety_revocation_triggered boolean not null default false,

    reason_codes jsonb not null default '[]'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase368_controller_state check (
        controller_state in (
            'COMPLETED',
            'COMPLETED_WITH_OBSERVATION',
            'BLOCKED',
            'FAILED',
            'FAIL_CLOSED'
        )
    ),
    constraint ck_phase368_paper_only check (paper_only = true),
    constraint ck_phase368_no_broker_api check (broker_api_used = false),
    constraint ck_phase368_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase368_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase368_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase368_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase368_fail_closed check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_daily_autonomous_controller_v92_portfolio_date
    on public.paper_daily_autonomous_controller_v92 (portfolio_id, controller_date);

create index if not exists ix_paper_daily_autonomous_controller_v92_state_date
    on public.paper_daily_autonomous_controller_v92 (controller_state, controller_date desc);

create table if not exists public.paper_daily_autonomous_controller_audit_v92 (
    id bigint generated by default as identity primary key,
    controller_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE368_PRODUCTION_PAPER_DAILY_AUTONOMOUS_OPERATIONS_CONTROLLER',

    controller_state text not null,
    controller_passed boolean not null default false,
    autonomous_daily_operations_authorized boolean not null default false,
    daily_paper_cycle_executed boolean not null default false,

    activation_state text not null default 'UNKNOWN',
    qualification_state text not null default 'UNKNOWN',
    runtime_supervision_state text not null default 'UNKNOWN',
    runtime_supervision_score numeric not null default 0,
    master_cycle_state text not null default 'UNKNOWN',
    master_exit_code integer not null default 0,
    safety_revocation_triggered boolean not null default false,

    reason_codes jsonb not null default '[]'::jsonb,
    stdout_tail text not null default '',
    stderr_tail text not null default '',

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),

    constraint ck_phase368_audit_paper_only check (paper_only = true),
    constraint ck_phase368_audit_no_broker_api check (broker_api_used = false),
    constraint ck_phase368_audit_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase368_audit_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase368_audit_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase368_audit_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase368_audit_fail_closed check (fail_closed_policy = true)
);

create index if not exists ix_paper_daily_autonomous_controller_audit_v92_portfolio_created
    on public.paper_daily_autonomous_controller_audit_v92 (portfolio_id, created_at desc);

alter table public.paper_daily_autonomous_controller_v92 enable row level security;
alter table public.paper_daily_autonomous_controller_audit_v92 enable row level security;

comment on table public.paper_daily_autonomous_controller_v92 is
'GPT Quant V9.2 Phase 3.6.8 daily autonomous Production Paper operations controller state. Paper-only and fail-closed.';

comment on table public.paper_daily_autonomous_controller_audit_v92 is
'GPT Quant V9.2 Phase 3.6.8 immutable-style daily autonomous controller audit ledger.';

commit;