-- GPT Quant V9.2
-- Phase 3.7.9 — Production Paper Qualification State Reconciliation
-- + Automatic Promotion Readiness

create table if not exists public.paper_production_promotion_readiness_v92 (
    id bigint generated by default as identity primary key,
    portfolio_id text not null,
    strategy_version text not null,
    readiness_date date not null,
    qualification_state text not null,
    promotion_readiness_state text not null,
    promotion_ready boolean not null default false,
    observed_cycles integer not null default 0,
    valid_cycles integer not null default 0,
    blocked_cycles integer not null default 0,
    runtime_supervision_pass boolean not null default false,
    paper_only_boundary_pass boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    historical_rewrite_allowed boolean not null default false,
    source_phase375_run_id text,
    source_phase376_run_id text,
    reconciliation_hash text not null,
    raw_state jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists uq_paper_production_promotion_readiness_v92_day
on public.paper_production_promotion_readiness_v92
(portfolio_id, strategy_version, readiness_date);

create unique index if not exists uq_paper_production_promotion_readiness_v92_hash
on public.paper_production_promotion_readiness_v92
(reconciliation_hash);

create index if not exists ix_paper_production_promotion_readiness_v92_state
on public.paper_production_promotion_readiness_v92
(portfolio_id, strategy_version, readiness_date desc);

alter table public.paper_production_promotion_readiness_v92 enable row level security;

revoke all on table public.paper_production_promotion_readiness_v92 from anon, authenticated;
grant select, insert, update on table public.paper_production_promotion_readiness_v92 to service_role;

comment on table public.paper_production_promotion_readiness_v92 is
'GPT Quant Phase 3.7.9 canonical production-paper qualification reconciliation and automatic promotion-readiness state. Paper-only; no broker or real-money execution.';

notify pgrst, 'reload schema';

select
  'PHASE379_READY' as phase379_state,
  to_regclass('public.paper_production_promotion_readiness_v92') as canonical_table;
