begin;

create table if not exists public.paper_true_safety_violation_forensics_v92 (
    id bigint generated by default as identity primary key,
    forensic_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE3724_TRUE_SAFETY_VIOLATION_EVIDENCE_FORENSICS_AND_RECOVERY_ELIGIBILITY',

    classification text not null,
    recovery_eligible boolean not null default false,
    historical_rewrite_allowed boolean not null default false,

    supervision_table text,
    supervision_state text not null default 'MISSING',
    controller_state text not null default 'MISSING',
    lifecycle_state text not null default 'MISSING',
    prior_reconciliation_class text not null default 'MISSING',

    supervision_date date,
    controller_date date,
    lifecycle_date date,
    diagnostic_date date,
    reconciliation_date date,

    current_violations jsonb not null default '[]'::jsonb,
    stale_or_legacy_indicators jsonb not null default '[]'::jsonb,
    evidence_gaps jsonb not null default '[]'::jsonb,
    reason_codes jsonb not null default '[]'::jsonb,
    source_hashes jsonb not null default '{}'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase3724_classification check (
        classification in (
            'RECOVERY_ELIGIBLE_STALE_OR_LEGACY',
            'RECOVERY_BLOCKED_TRUE_CURRENT_VIOLATION',
            'RECOVERY_BLOCKED_INSUFFICIENT_EVIDENCE',
            'NO_ACTIVE_VIOLATION'
        )
    ),
    constraint ck_phase3724_no_history_rewrite check (historical_rewrite_allowed = false),
    constraint ck_phase3724_paper_only check (paper_only = true),
    constraint ck_phase3724_no_broker_api check (broker_api_used = false),
    constraint ck_phase3724_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase3724_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase3724_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase3724_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase3724_fail_closed check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_true_safety_violation_forensics_v92_portfolio_date
    on public.paper_true_safety_violation_forensics_v92 (portfolio_id, forensic_date);

create table if not exists public.paper_true_safety_violation_forensics_audit_v92 (
    id bigint generated by default as identity primary key,
    forensic_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE3724_TRUE_SAFETY_VIOLATION_EVIDENCE_FORENSICS_AND_RECOVERY_ELIGIBILITY',

    classification text not null,
    recovery_eligible boolean not null default false,
    historical_rewrite_allowed boolean not null default false,

    supervision_table text,
    supervision_state text not null default 'MISSING',
    controller_state text not null default 'MISSING',
    lifecycle_state text not null default 'MISSING',
    prior_reconciliation_class text not null default 'MISSING',

    supervision_date date,
    controller_date date,
    lifecycle_date date,
    diagnostic_date date,
    reconciliation_date date,

    current_violations jsonb not null default '[]'::jsonb,
    stale_or_legacy_indicators jsonb not null default '[]'::jsonb,
    evidence_gaps jsonb not null default '[]'::jsonb,
    reason_codes jsonb not null default '[]'::jsonb,
    source_hashes jsonb not null default '{}'::jsonb,
    evidence_document jsonb not null default '{}'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),

    constraint ck_phase3724_audit_no_history_rewrite check (historical_rewrite_allowed = false),
    constraint ck_phase3724_audit_paper_only check (paper_only = true),
    constraint ck_phase3724_audit_no_broker_api check (broker_api_used = false),
    constraint ck_phase3724_audit_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase3724_audit_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase3724_audit_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase3724_audit_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase3724_audit_fail_closed check (fail_closed_policy = true)
);

create index if not exists ix_paper_true_safety_violation_forensics_audit_v92_portfolio_created
    on public.paper_true_safety_violation_forensics_audit_v92 (portfolio_id, created_at desc);

alter table public.paper_true_safety_violation_forensics_v92 enable row level security;
alter table public.paper_true_safety_violation_forensics_audit_v92 enable row level security;

comment on table public.paper_true_safety_violation_forensics_v92 is
'GPT Quant V9.2 Phase 3.7.2.4 safety-violation evidence forensics and recovery eligibility.';

comment on table public.paper_true_safety_violation_forensics_audit_v92 is
'GPT Quant V9.2 Phase 3.7.2.4 immutable-style safety-violation forensic audit evidence.';

notify pgrst, 'reload schema';

commit;