begin;

create table if not exists public.paper_observation_acceptance_readiness_v92 (
    id bigint generated by default as identity primary key,
    monitor_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE371_PRODUCTION_PAPER_OBSERVATION_DAILY_HEALTH_ACCEPTANCE_READINESS_MONITOR',

    readiness_state text not null,
    observation_state text not null default 'UNKNOWN',
    observation_days integer not null default 0,
    remaining_days integer not null default 0,
    lifecycle_pass_rate numeric not null default 0,
    safety_revocation_days integer not null default 0,
    evidence_chain_break_count integer not null default 0,
    max_drawdown numeric not null default 0,
    signal_days integer not null default 0,
    fill_days integer not null default 0,
    observation_validated boolean not null default false,
    acceptance_candidate boolean not null default false,
    latest_controller_state text not null default 'UNKNOWN',

    hard_failures jsonb not null default '[]'::jsonb,
    notes jsonb not null default '[]'::jsonb,

    source_observation_evidence_sha256 text,
    source_controller_evidence_sha256 text,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase371_readiness_state check (
        readiness_state in (
            'NOT_READY',
            'READY_WITH_LIMITED_COVERAGE',
            'READY',
            'BLOCKED',
            'FAIL_CLOSED'
        )
    ),
    constraint ck_phase371_paper_only check (paper_only = true),
    constraint ck_phase371_no_broker_api check (broker_api_used = false),
    constraint ck_phase371_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase371_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase371_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase371_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase371_fail_closed check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_observation_acceptance_readiness_v92_portfolio_date
    on public.paper_observation_acceptance_readiness_v92 (portfolio_id, monitor_date);

create table if not exists public.paper_observation_acceptance_readiness_audit_v92 (
    id bigint generated by default as identity primary key,
    monitor_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE371_PRODUCTION_PAPER_OBSERVATION_DAILY_HEALTH_ACCEPTANCE_READINESS_MONITOR',

    readiness_state text not null,
    observation_state text not null default 'UNKNOWN',
    observation_days integer not null default 0,
    remaining_days integer not null default 0,
    lifecycle_pass_rate numeric not null default 0,
    safety_revocation_days integer not null default 0,
    evidence_chain_break_count integer not null default 0,
    max_drawdown numeric not null default 0,
    signal_days integer not null default 0,
    fill_days integer not null default 0,
    observation_validated boolean not null default false,
    acceptance_candidate boolean not null default false,
    latest_controller_state text not null default 'UNKNOWN',

    hard_failures jsonb not null default '[]'::jsonb,
    notes jsonb not null default '[]'::jsonb,

    source_observation_evidence_sha256 text,
    source_controller_evidence_sha256 text,
    evidence_document jsonb not null default '{}'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),

    constraint ck_phase371_audit_paper_only check (paper_only = true),
    constraint ck_phase371_audit_no_broker_api check (broker_api_used = false),
    constraint ck_phase371_audit_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase371_audit_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase371_audit_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase371_audit_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase371_audit_fail_closed check (fail_closed_policy = true)
);

create index if not exists ix_paper_observation_acceptance_readiness_audit_v92_portfolio_created
    on public.paper_observation_acceptance_readiness_audit_v92 (portfolio_id, created_at desc);

alter table public.paper_observation_acceptance_readiness_v92 enable row level security;
alter table public.paper_observation_acceptance_readiness_audit_v92 enable row level security;

comment on table public.paper_observation_acceptance_readiness_v92 is
'GPT Quant V9.2 Phase 3.7.1 daily Production Paper observation health and acceptance readiness state.';

comment on table public.paper_observation_acceptance_readiness_audit_v92 is
'GPT Quant V9.2 Phase 3.7.1 immutable-style acceptance readiness audit evidence.';

notify pgrst, 'reload schema';

commit;