begin;

create table if not exists public.paper_acceptance_promotion_control_v92 (
    id bigint generated by default as identity primary key,
    promotion_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE372_PRODUCTION_PAPER_OBSERVATION_DAILY_AUTOMATION_ACCEPTANCE_PROMOTION_CONTROLLER',

    promotion_state text not null,
    paper_acceptance_eligibility_promoted boolean not null default false,

    readiness_state text not null default 'UNKNOWN',
    observation_state text not null default 'UNKNOWN',
    lifecycle_state text not null default 'UNKNOWN',

    observation_days integer not null default 0,
    remaining_days integer not null default 0,
    lifecycle_pass_rate numeric not null default 0,
    safety_revocation_days integer not null default 0,
    evidence_chain_break_count integer not null default 0,
    max_drawdown numeric not null default 0,
    signal_days integer not null default 0,
    fill_days integer not null default 0,

    observation_validated boolean not null default false,
    acceptance_candidate boolean not null default false,

    reason_codes jsonb not null default '[]'::jsonb,
    hard_failures jsonb not null default '[]'::jsonb,

    source_readiness_evidence_sha256 text,
    source_observation_evidence_sha256 text,
    source_lifecycle_evidence_sha256 text,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase372_promotion_state check (
        promotion_state in (
            'OBSERVATION_CONTINUES',
            'PAPER_ACCEPTANCE_ELIGIBLE',
            'PAPER_ACCEPTANCE_LIMITED_COVERAGE',
            'PROMOTION_HELD',
            'FAIL_CLOSED'
        )
    ),
    constraint ck_phase372_paper_only check (paper_only = true),
    constraint ck_phase372_no_broker_api check (broker_api_used = false),
    constraint ck_phase372_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase372_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase372_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase372_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase372_fail_closed check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_acceptance_promotion_control_v92_portfolio_date
    on public.paper_acceptance_promotion_control_v92 (portfolio_id, promotion_date);

create index if not exists ix_paper_acceptance_promotion_control_v92_state_date
    on public.paper_acceptance_promotion_control_v92 (promotion_state, promotion_date desc);

create table if not exists public.paper_acceptance_promotion_control_audit_v92 (
    id bigint generated by default as identity primary key,
    promotion_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE372_PRODUCTION_PAPER_OBSERVATION_DAILY_AUTOMATION_ACCEPTANCE_PROMOTION_CONTROLLER',

    promotion_state text not null,
    paper_acceptance_eligibility_promoted boolean not null default false,

    readiness_state text not null default 'UNKNOWN',
    observation_state text not null default 'UNKNOWN',
    lifecycle_state text not null default 'UNKNOWN',

    observation_days integer not null default 0,
    remaining_days integer not null default 0,
    lifecycle_pass_rate numeric not null default 0,
    safety_revocation_days integer not null default 0,
    evidence_chain_break_count integer not null default 0,
    max_drawdown numeric not null default 0,
    signal_days integer not null default 0,
    fill_days integer not null default 0,

    observation_validated boolean not null default false,
    acceptance_candidate boolean not null default false,

    reason_codes jsonb not null default '[]'::jsonb,
    hard_failures jsonb not null default '[]'::jsonb,

    source_readiness_evidence_sha256 text,
    source_observation_evidence_sha256 text,
    source_lifecycle_evidence_sha256 text,
    evidence_document jsonb not null default '{}'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),

    constraint ck_phase372_audit_paper_only check (paper_only = true),
    constraint ck_phase372_audit_no_broker_api check (broker_api_used = false),
    constraint ck_phase372_audit_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase372_audit_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase372_audit_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase372_audit_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase372_audit_fail_closed check (fail_closed_policy = true)
);

create index if not exists ix_paper_acceptance_promotion_control_audit_v92_portfolio_created
    on public.paper_acceptance_promotion_control_audit_v92 (portfolio_id, created_at desc);

alter table public.paper_acceptance_promotion_control_v92 enable row level security;
alter table public.paper_acceptance_promotion_control_audit_v92 enable row level security;

comment on table public.paper_acceptance_promotion_control_v92 is
'GPT Quant V9.2 Phase 3.7.2 automated Production Paper observation acceptance-promotion state. No real-money authority.';

comment on table public.paper_acceptance_promotion_control_audit_v92 is
'GPT Quant V9.2 Phase 3.7.2 immutable-style acceptance-promotion audit evidence.';

notify pgrst, 'reload schema';

commit;