begin;

create table if not exists public.paper_runtime_supervision_state_v92 (
    id bigint generated by default as identity primary key,
    supervision_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE367_PRODUCTION_PAPER_AUTONOMOUS_RUNTIME_SUPERVISION_SAFETY_REVOCATION_ENGINE',

    supervision_state text not null,
    supervision_score numeric not null default 0,
    autonomous_paper_operations_continued boolean not null default false,
    safety_revocation_triggered boolean not null default false,

    activation_state text not null default 'UNKNOWN',
    qualification_state text not null default 'UNKNOWN',
    qualification_score numeric not null default 0,
    readiness_state text not null default 'UNKNOWN',
    readiness_score numeric not null default 0,
    health_state text not null default 'UNKNOWN',
    health_score numeric not null default 0,
    sla_state text not null default 'UNKNOWN',
    sla_score numeric not null default 0,
    master_cycle_state text not null default 'UNKNOWN',

    open_incident boolean not null default false,
    incident_severity text not null default 'NONE',

    critical_failures jsonb not null default '[]'::jsonb,
    warning_failures jsonb not null default '[]'::jsonb,
    reason_codes jsonb not null default '[]'::jsonb,
    canonical_dates jsonb not null default '{}'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase367_supervision_state
        check (supervision_state in (
            'CONTINUE_ACTIVE',
            'CONTINUE_WITH_OBSERVATION',
            'SUSPENDED',
            'REVOKED',
            'FAIL_CLOSED'
        )),
    constraint ck_phase367_paper_only
        check (paper_only = true),
    constraint ck_phase367_no_broker_api
        check (broker_api_used = false),
    constraint ck_phase367_no_broker_credentials
        check (broker_credentials_used = false),
    constraint ck_phase367_no_broker_submission
        check (broker_order_submission_enabled = false),
    constraint ck_phase367_no_real_money
        check (real_money_trading_enabled = false),
    constraint ck_phase367_no_live_release
        check (live_money_release_authorized = false),
    constraint ck_phase367_fail_closed
        check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_runtime_supervision_state_v92_portfolio_date
    on public.paper_runtime_supervision_state_v92 (portfolio_id, supervision_date);

create index if not exists ix_paper_runtime_supervision_state_v92_state
    on public.paper_runtime_supervision_state_v92 (supervision_state, supervision_date desc);

create table if not exists public.paper_runtime_supervision_audit_v92 (
    id bigint generated by default as identity primary key,
    supervision_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',

    supervision_state text not null,
    supervision_score numeric not null default 0,
    autonomous_paper_operations_continued boolean not null default false,
    safety_revocation_triggered boolean not null default false,

    activation_state text not null default 'UNKNOWN',
    qualification_state text not null default 'UNKNOWN',

    reason_codes jsonb not null default '[]'::jsonb,
    evidence_sha256 text not null,

    paper_only boolean not null default true,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    created_at timestamptz not null default now(),

    constraint ck_phase367_audit_paper_only
        check (paper_only = true),
    constraint ck_phase367_audit_no_broker
        check (broker_order_submission_enabled = false),
    constraint ck_phase367_audit_no_real_money
        check (real_money_trading_enabled = false),
    constraint ck_phase367_audit_no_live_release
        check (live_money_release_authorized = false),
    constraint ck_phase367_audit_fail_closed
        check (fail_closed_policy = true)
);

create index if not exists ix_paper_runtime_supervision_audit_v92_portfolio_created
    on public.paper_runtime_supervision_audit_v92 (portfolio_id, created_at desc);

alter table public.paper_runtime_supervision_state_v92 enable row level security;
alter table public.paper_runtime_supervision_audit_v92 enable row level security;

comment on table public.paper_runtime_supervision_state_v92 is
'GPT Quant V9.2 Phase 3.6.7 active Production Paper runtime supervision state with automatic safety revocation.';

comment on table public.paper_runtime_supervision_audit_v92 is
'GPT Quant V9.2 Phase 3.6.7 immutable-style runtime supervision and revocation audit.';

commit;