-- GPT Quant V9.2
-- Phase 3.4.8.2 — Canonical Signal Persistence + Runtime Source Adapter
--
-- Apply once in Supabase SQL Editor.
-- This creates a dedicated paper-only canonical runtime store.
--
-- NO broker credentials.
-- NO broker orders.
-- NO real-money state.

begin;

create table if not exists public.paper_canonical_signals_v92 (
    id bigint generated by default as identity primary key,
    strategy_version text not null,
    trade_date date not null,
    symbol text not null,
    signal text not null check (signal in ('BUY','LONG')),
    total_score numeric not null,
    source_table text not null,
    source_row_hash text not null,
    canonical_batch_id text not null,
    synthetic_evidence boolean not null default false check (synthetic_evidence = false),
    created_at timestamptz not null default now(),
    unique (strategy_version, trade_date, symbol, canonical_batch_id)
);

create index if not exists idx_paper_canonical_signals_v92_lookup
    on public.paper_canonical_signals_v92
    (strategy_version, trade_date desc, total_score desc);

create table if not exists public.paper_canonical_market_prices_v92 (
    id bigint generated by default as identity primary key,
    trade_date date not null,
    symbol text not null,
    close numeric not null check (close > 0),
    source_table text not null,
    source_row_hash text not null,
    canonical_batch_id text not null,
    synthetic_evidence boolean not null default false check (synthetic_evidence = false),
    created_at timestamptz not null default now(),
    unique (trade_date, symbol, canonical_batch_id)
);

create index if not exists idx_paper_canonical_market_prices_v92_lookup
    on public.paper_canonical_market_prices_v92
    (trade_date desc, symbol);

create table if not exists public.paper_canonical_runtime_batches_v92 (
    canonical_batch_id text primary key,
    strategy_version text not null,
    trade_date date,
    signal_source_table text,
    market_source_table text,
    canonical_signals integer not null default 0 check (canonical_signals >= 0),
    canonical_prices integer not null default 0 check (canonical_prices >= 0),
    status text not null check (
        status in (
            'PERSISTED',
            'NO_SIGNAL',
            'NO_REAL_PRICE',
            'BLOCKED'
        )
    ),
    runtime_execution_gate text not null,
    synthetic_fallback_allowed boolean not null default false check (synthetic_fallback_allowed = false),
    broker_order_submission_enabled boolean not null default false check (broker_order_submission_enabled = false),
    real_money_trading_enabled boolean not null default false check (real_money_trading_enabled = false),
    evidence_sha256 text,
    created_at timestamptz not null default now()
);

alter table public.paper_canonical_signals_v92 enable row level security;
alter table public.paper_canonical_market_prices_v92 enable row level security;
alter table public.paper_canonical_runtime_batches_v92 enable row level security;

-- Intentionally create NO anon/authenticated write policies.
-- GitHub Actions uses the server-side service-role secret for this paper-only store.

comment on table public.paper_canonical_signals_v92 is
'GPT Quant V9.2 paper-only canonical signal persistence. Synthetic evidence forbidden.';

comment on table public.paper_canonical_market_prices_v92 is
'GPT Quant V9.2 paper-only canonical market-price persistence. Synthetic evidence forbidden.';

comment on table public.paper_canonical_runtime_batches_v92 is
'GPT Quant V9.2 canonical runtime batch audit ledger. Broker and real-money flags hard-disabled.';

commit;
