begin;

create table if not exists public.paper_operations_observation_validation_v92 (
    id bigint generated by default as identity primary key,
    observation_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE370_PRODUCTION_PAPER_AUTONOMOUS_OPERATIONS_OBSERVATION_VALIDATION',

    observation_state text not null,
    validated boolean not null default false,
    acceptance_candidate boolean not null default false,

    observation_days integer not null default 0,
    remaining_minimum_days integer not null default 0,
    passed_days integer not null default 0,
    pass_rate numeric not null default 0,

    controller_executed_days integer not null default 0,
    authorized_days integer not null default 0,
    signal_days integer not null default 0,
    order_days integer not null default 0,
    fill_days integer not null default 0,
    settled_fill_days integer not null default 0,

    fail_closed_days integer not null default 0,
    safety_revocation_days integer not null default 0,
    evidence_chain_break_count integer not null default 0,

    initial_nav numeric not null default 0,
    latest_nav numeric not null default 0,
    cumulative_return numeric not null default 0,
    max_drawdown numeric not null default 0,

    hard_failures jsonb not null default '[]'::jsonb,
    observations jsonb not null default '[]'::jsonb,
    policy jsonb not null default '{}'::jsonb,

    source_tail_evidence_sha256 text not null,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase370_observation_state check (
        observation_state in (
            'OBSERVING',
            'VALIDATED',
            'VALIDATED_WITH_LIMITED_TRADE_COVERAGE',
            'FAIL_CLOSED'
        )
    ),
    constraint ck_phase370_paper_only check (paper_only = true),
    constraint ck_phase370_no_broker_api check (broker_api_used = false),
    constraint ck_phase370_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase370_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase370_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase370_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase370_fail_closed check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_operations_observation_validation_v92_portfolio_date
    on public.paper_operations_observation_validation_v92 (portfolio_id, observation_date);

create index if not exists ix_paper_operations_observation_validation_v92_state_date
    on public.paper_operations_observation_validation_v92 (observation_state, observation_date desc);

create table if not exists public.paper_operations_observation_validation_audit_v92 (
    id bigint generated by default as identity primary key,
    observation_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE370_PRODUCTION_PAPER_AUTONOMOUS_OPERATIONS_OBSERVATION_VALIDATION',

    observation_state text not null,
    validated boolean not null default false,
    acceptance_candidate boolean not null default false,

    observation_days integer not null default 0,
    remaining_minimum_days integer not null default 0,
    passed_days integer not null default 0,
    pass_rate numeric not null default 0,

    controller_executed_days integer not null default 0,
    authorized_days integer not null default 0,
    signal_days integer not null default 0,
    order_days integer not null default 0,
    fill_days integer not null default 0,
    settled_fill_days integer not null default 0,

    fail_closed_days integer not null default 0,
    safety_revocation_days integer not null default 0,
    evidence_chain_break_count integer not null default 0,

    initial_nav numeric not null default 0,
    latest_nav numeric not null default 0,
    cumulative_return numeric not null default 0,
    max_drawdown numeric not null default 0,

    hard_failures jsonb not null default '[]'::jsonb,
    observations jsonb not null default '[]'::jsonb,
    policy jsonb not null default '{}'::jsonb,

    source_tail_evidence_sha256 text not null,
    evidence_document jsonb not null default '{}'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),

    constraint ck_phase370_audit_paper_only check (paper_only = true),
    constraint ck_phase370_audit_no_broker_api check (broker_api_used = false),
    constraint ck_phase370_audit_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase370_audit_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase370_audit_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase370_audit_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase370_audit_fail_closed check (fail_closed_policy = true)
);

create index if not exists ix_paper_operations_observation_validation_audit_v92_portfolio_created
    on public.paper_operations_observation_validation_audit_v92 (portfolio_id, created_at desc);

alter table public.paper_operations_observation_validation_v92 enable row level security;
alter table public.paper_operations_observation_validation_audit_v92 enable row level security;

comment on table public.paper_operations_observation_validation_v92 is
'GPT Quant V9.2 Phase 3.7.0 multi-day Production Paper autonomous operations observation and validation state.';

comment on table public.paper_operations_observation_validation_audit_v92 is
'GPT Quant V9.2 Phase 3.7.0 immutable-style observation/validation audit evidence.';

notify pgrst, 'reload schema';

commit;