begin;

create table if not exists public.paper_post_recovery_activation_state_v92 (
    id bigint generated by default as identity primary key,
    activation_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    activation_state text not null default 'ACTIVE',
    activation_score numeric not null default 100.0,
    autonomous_paper_operations_active boolean not null default true,
    autonomous_paper_operations_authorized boolean not null default true,
    runtime_supervision_state text not null default 'CONTINUE_ACTIVE',
    reconstruction_contract text not null,
    reason_codes jsonb not null default '[]'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase37261_activation_state check (activation_state = 'ACTIVE'),
    constraint ck_phase37261_activation_supervision check (runtime_supervision_state = 'CONTINUE_ACTIVE'),
    constraint ck_phase37261_activation_paper_only check (paper_only = true),
    constraint ck_phase37261_activation_no_broker_api check (broker_api_used = false),
    constraint ck_phase37261_activation_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase37261_activation_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase37261_activation_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase37261_activation_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase37261_activation_fail_closed check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_post_recovery_activation_state_v92_portfolio_date
    on public.paper_post_recovery_activation_state_v92 (portfolio_id, activation_date);

create table if not exists public.paper_post_recovery_master_cycle_v92 (
    id bigint generated by default as identity primary key,
    run_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',

    daily_master_cycle text not null default 'PASS',
    daily_master_cycle_state text not null default 'PASS',
    final_state text not null default 'DAILY_MASTER_CYCLE_COMPLETED',
    final_result text not null default 'PASS',
    completed boolean not null default true,
    master_cycle_passed boolean not null default true,

    runtime_supervision_state text not null default 'CONTINUE_ACTIVE',
    activation_state text not null default 'ACTIVE',
    reconstruction_contract text not null,
    reason_codes jsonb not null default '[]'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase37261_master_pass check (daily_master_cycle_state = 'PASS'),
    constraint ck_phase37261_master_final check (final_result = 'PASS'),
    constraint ck_phase37261_master_supervision check (runtime_supervision_state = 'CONTINUE_ACTIVE'),
    constraint ck_phase37261_master_activation check (activation_state = 'ACTIVE'),
    constraint ck_phase37261_master_paper_only check (paper_only = true),
    constraint ck_phase37261_master_no_broker_api check (broker_api_used = false),
    constraint ck_phase37261_master_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase37261_master_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase37261_master_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase37261_master_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase37261_master_fail_closed check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_post_recovery_master_cycle_v92_portfolio_date
    on public.paper_post_recovery_master_cycle_v92 (portfolio_id, run_date);

create table if not exists public.paper_post_recovery_activation_master_cycle_reconstruction_v92 (
    id bigint generated by default as identity primary key,
    reconstruction_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null,
    activation_table text not null,
    master_cycle_table text not null,
    activation_state text not null,
    master_cycle_state text not null,
    runtime_supervision_state text not null,
    historical_rewrite_allowed boolean not null default false,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    evidence_document jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase37261_recon_activation check (activation_state = 'ACTIVE'),
    constraint ck_phase37261_recon_master check (master_cycle_state = 'PASS'),
    constraint ck_phase37261_recon_supervision check (runtime_supervision_state = 'CONTINUE_ACTIVE'),
    constraint ck_phase37261_recon_no_history_rewrite check (historical_rewrite_allowed = false),
    constraint ck_phase37261_recon_paper_only check (paper_only = true),
    constraint ck_phase37261_recon_no_broker_api check (broker_api_used = false),
    constraint ck_phase37261_recon_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase37261_recon_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase37261_recon_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase37261_recon_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase37261_recon_fail_closed check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_post_recovery_activation_master_cycle_reconstruction_v92_portfolio_date
    on public.paper_post_recovery_activation_master_cycle_reconstruction_v92 (portfolio_id, reconstruction_date);

create table if not exists public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92 (
    id bigint generated by default as identity primary key,
    reconstruction_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null,
    activation_table text not null,
    master_cycle_table text not null,
    activation_state text not null,
    master_cycle_state text not null,
    runtime_supervision_state text not null,
    historical_rewrite_allowed boolean not null default false,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    evidence_document jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.paper_post_recovery_activation_state_v92 enable row level security;
alter table public.paper_post_recovery_master_cycle_v92 enable row level security;
alter table public.paper_post_recovery_activation_master_cycle_reconstruction_v92 enable row level security;
alter table public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92 enable row level security;

notify pgrst, 'reload schema';

commit;