begin;

create table if not exists public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92 (
    id bigint generated by default as identity primary key,

    reconstruction_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE37261_POST_RECOVERY_ACTIVATION_MASTER_CYCLE_CANONICAL_STATE_RECONSTRUCTION',

    activation_table text not null,
    master_cycle_table text not null,

    activation_state text not null,
    master_cycle_state text not null,
    runtime_supervision_state text not null,

    historical_rewrite_allowed boolean not null default false,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    evidence_document jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),

    constraint ck_phase37261_v3_audit_activation_state
        check (activation_state = 'ACTIVE'),

    constraint ck_phase37261_v3_audit_master_cycle_state
        check (master_cycle_state = 'PASS'),

    constraint ck_phase37261_v3_audit_runtime_supervision
        check (runtime_supervision_state = 'CONTINUE_ACTIVE'),

    constraint ck_phase37261_v3_audit_no_history_rewrite
        check (historical_rewrite_allowed = false),

    constraint ck_phase37261_v3_audit_paper_only
        check (paper_only = true),

    constraint ck_phase37261_v3_audit_no_broker_api
        check (broker_api_used = false),

    constraint ck_phase37261_v3_audit_no_broker_credentials
        check (broker_credentials_used = false),

    constraint ck_phase37261_v3_audit_no_broker_submission
        check (broker_order_submission_enabled = false),

    constraint ck_phase37261_v3_audit_no_real_money
        check (real_money_trading_enabled = false),

    constraint ck_phase37261_v3_audit_no_live_release
        check (live_money_release_authorized = false),

    constraint ck_phase37261_v3_audit_fail_closed
        check (fail_closed_policy = true)
);

create index if not exists ix_phase37261_v3_reconstruction_audit_portfolio_created
    on public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    (portfolio_id, created_at desc);

alter table public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    enable row level security;

comment on table public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92 is
'GPT Quant V9.2 Phase 3.7.2.6.1 canonical immutable-style reconstruction audit table. Paper-only and fail-closed.';

notify pgrst, 'reload schema';

commit;