begin;

create table if not exists public.paper_autonomous_activation_state_v92 (
    id bigint generated by default as identity primary key,
    activation_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE366_PRODUCTION_PAPER_AUTONOMOUS_OPERATIONAL_ACTIVATION_CONTROL_ENGINE',

    activation_state text not null,
    activation_score numeric not null default 0,
    autonomous_paper_operations_active boolean not null default false,

    qualification_state text not null default 'UNKNOWN',
    qualification_score numeric not null default 0,
    readiness_state text not null default 'UNKNOWN',
    readiness_score numeric not null default 0,
    health_state text not null default 'UNKNOWN',
    health_score numeric not null default 0,
    sla_state text not null default 'UNKNOWN',
    sla_score numeric not null default 0,
    master_cycle_state text not null default 'UNKNOWN',

    open_incident boolean not null default false,
    incident_severity text not null default 'NONE',

    critical_failures jsonb not null default '[]'::jsonb,
    warning_failures jsonb not null default '[]'::jsonb,
    reason_codes jsonb not null default '[]'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase366_activation_state
        check (activation_state in (
            'ACTIVE',
            'ACTIVE_WITH_OBSERVATION',
            'INACTIVE',
            'BLOCKED',
            'FAIL_CLOSED'
        )),
    constraint ck_phase366_paper_only
        check (paper_only = true),
    constraint ck_phase366_no_broker_api
        check (broker_api_used = false),
    constraint ck_phase366_no_broker_credentials
        check (broker_credentials_used = false),
    constraint ck_phase366_no_broker_submission
        check (broker_order_submission_enabled = false),
    constraint ck_phase366_no_real_money
        check (real_money_trading_enabled = false),
    constraint ck_phase366_no_live_release
        check (live_money_release_authorized = false),
    constraint ck_phase366_fail_closed
        check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_autonomous_activation_state_v92_portfolio_date
    on public.paper_autonomous_activation_state_v92 (portfolio_id, activation_date);

create index if not exists ix_paper_autonomous_activation_state_v92_active
    on public.paper_autonomous_activation_state_v92
    (autonomous_paper_operations_active, activation_date desc);

create table if not exists public.paper_autonomous_activation_audit_v92 (
    id bigint generated by default as identity primary key,
    activation_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',

    activation_state text not null,
    activation_score numeric not null default 0,
    autonomous_paper_operations_active boolean not null default false,
    qualification_state text not null default 'UNKNOWN',

    reason_codes jsonb not null default '[]'::jsonb,
    evidence_sha256 text not null,

    paper_only boolean not null default true,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    created_at timestamptz not null default now(),

    constraint ck_phase366_audit_paper_only
        check (paper_only = true),
    constraint ck_phase366_audit_no_broker
        check (broker_order_submission_enabled = false),
    constraint ck_phase366_audit_no_real_money
        check (real_money_trading_enabled = false),
    constraint ck_phase366_audit_no_live_release
        check (live_money_release_authorized = false),
    constraint ck_phase366_audit_fail_closed
        check (fail_closed_policy = true)
);

create index if not exists ix_paper_autonomous_activation_audit_v92_portfolio_created
    on public.paper_autonomous_activation_audit_v92
    (portfolio_id, created_at desc);

alter table public.paper_autonomous_activation_state_v92 enable row level security;
alter table public.paper_autonomous_activation_audit_v92 enable row level security;

comment on table public.paper_autonomous_activation_state_v92 is
'GPT Quant V9.2 Phase 3.6.6 autonomous Production Paper activation state. Paper-only; broker and real-money authorization hard-disabled.';

comment on table public.paper_autonomous_activation_audit_v92 is
'GPT Quant V9.2 Phase 3.6.6 activation decision audit ledger.';

commit;