begin;

create table if not exists public.paper_continuous_qualification_v92 (
    id bigint generated by default as identity primary key,
    qualification_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE3651_CONTINUOUS_QUALIFICATION_CANONICAL_INPUT_ALIGNMENT_FIX',

    previous_qualification_state text not null default 'NONE',
    qualification_state text not null,
    qualification_score numeric not null default 0,
    autonomous_paper_operations_authorized boolean not null default false,

    readiness_state text not null default 'UNKNOWN',
    readiness_score numeric not null default 0,
    health_state text not null default 'UNKNOWN',
    health_score numeric not null default 0,
    sla_state text not null default 'UNKNOWN',
    sla_score numeric not null default 0,
    master_cycle_state text not null default 'UNKNOWN',

    open_incident boolean not null default false,
    incident_severity text not null default 'NONE',
    reason_codes jsonb not null default '[]'::jsonb,

    evidence_sha256 text not null,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase365_qualification_state
        check (qualification_state in (
            'QUALIFIED',
            'QUALIFIED_WITH_OBSERVATION',
            'NOT_QUALIFIED',
            'REVOKED',
            'FAIL_CLOSED'
        )),
    constraint ck_phase365_paper_only check (paper_only = true),
    constraint ck_phase365_no_broker_api check (broker_api_used = false),
    constraint ck_phase365_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase365_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase365_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase365_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase365_fail_closed check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_continuous_qualification_v92_portfolio_date
    on public.paper_continuous_qualification_v92 (portfolio_id, qualification_date);

create index if not exists ix_paper_continuous_qualification_v92_state
    on public.paper_continuous_qualification_v92 (qualification_state, qualification_date desc);

create table if not exists public.paper_promotion_control_audit_v92 (
    id bigint generated by default as identity primary key,
    qualification_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    from_state text not null,
    to_state text not null,
    autonomous_paper_operations_authorized boolean not null default false,
    reason_codes jsonb not null default '[]'::jsonb,
    evidence_sha256 text not null,
    created_at timestamptz not null default now()
);

create index if not exists ix_paper_promotion_control_audit_v92_portfolio_created
    on public.paper_promotion_control_audit_v92 (portfolio_id, created_at desc);

alter table public.paper_continuous_qualification_v92 enable row level security;
alter table public.paper_promotion_control_audit_v92 enable row level security;

comment on table public.paper_continuous_qualification_v92 is
'GPT Quant V9.2 Phase 3.6.5.1 persistent continuous qualification state. Paper-only; broker and real-money capabilities hard-disabled.';

comment on table public.paper_promotion_control_audit_v92 is
'GPT Quant V9.2 Phase 3.6.5.1 immutable-style promotion/revocation transition audit for autonomous paper operations.';

commit;