-- ============================================================
-- GPT Quant V14 Enterprise AI Trading Platform
-- SINGLE COPY-PASTE SUPABASE SETUP
-- Paste this ENTIRE file into Supabase SQL Editor and press Run.
-- It is idempotent and may be run again safely.
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.autotrader_configs_v13 (
  id bigint generated by default as identity primary key,
  account_name text not null default 'paper-main',
  mode text not null default 'PAPER'
    check (mode in ('PAPER','APPROVAL','LIVE_LOCKED')),
  enabled boolean not null default false,
  kill_switch boolean not null default false,
  starting_cash numeric not null default 1000000,
  reserve_cash_pct numeric not null default 30,
  max_positions integer not null default 5,
  max_position_pct numeric not null default 15,
  min_score numeric not null default 40,
  max_risk_score numeric not null default 60,
  require_approval boolean not null default true,
  auto_fill boolean not null default false,
  max_daily_orders integer not null default 5,
  lot_size integer not null default 1,
  commission_rate numeric not null default 0.001425,
  sell_tax_rate numeric not null default 0.003,
  stop_loss_pct numeric not null default 8,
  take_profit_pct numeric not null default 15,
  exit_score numeric not null default 25,
  max_holding_days integer not null default 20,
  price_source text not null default 'LATEST_CLOSE',
  last_run_at timestamptz,
  last_run_status text,
  last_run_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists autotrader_configs_v13_account_uidx
  on public.autotrader_configs_v13(account_name);

create table if not exists public.trade_orders_v13 (
  id uuid primary key default gen_random_uuid(),
  account_name text not null default 'paper-main',
  symbol text not null,
  side text not null check (side in ('BUY','SELL')),
  quantity integer not null check (quantity > 0),
  reference_price numeric not null,
  fill_price numeric,
  notional numeric not null,
  score numeric,
  risk_score numeric,
  confidence numeric,
  reason text,
  exit_reason text,
  mode text not null default 'PAPER',
  status text not null default 'PROPOSED'
    check (status in ('PROPOSED','APPROVED','REJECTED','FILLED','CANCELLED','FAILED')),
  signal_date date,
  execution_date date,
  commission numeric not null default 0,
  transaction_tax numeric not null default 0,
  realized_pnl numeric not null default 0,
  idempotency_key text,
  broker_order_id text,
  error_message text,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  filled_at timestamptz
);

create unique index if not exists trade_orders_v13_idempotency_uidx
  on public.trade_orders_v13(idempotency_key)
  where idempotency_key is not null;

create table if not exists public.paper_positions_v13 (
  account_name text not null default 'paper-main',
  symbol text not null,
  stock_id bigint,
  name text,
  quantity integer not null default 0,
  average_price numeric not null default 0,
  last_price numeric not null default 0,
  cost_basis numeric not null default 0,
  market_value numeric not null default 0,
  unrealized_pnl numeric not null default 0,
  realized_pnl numeric not null default 0,
  opened_at timestamptz not null default now(),
  last_trade_date date,
  holding_days integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (account_name, symbol)
);

create table if not exists public.paper_accounts_v13 (
  account_name text primary key,
  starting_cash numeric not null default 1000000,
  cash numeric not null default 1000000,
  equity numeric not null default 1000000,
  realized_pnl numeric not null default 0,
  unrealized_pnl numeric not null default 0,
  total_fees numeric not null default 0,
  total_tax numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.paper_fills_v13 (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references public.trade_orders_v13(id) on delete set null,
  account_name text not null,
  symbol text not null,
  side text not null check (side in ('BUY','SELL')),
  quantity integer not null check (quantity > 0),
  fill_price numeric not null check (fill_price > 0),
  gross_amount numeric not null,
  commission numeric not null default 0,
  transaction_tax numeric not null default 0,
  net_cash_flow numeric not null,
  realized_pnl numeric not null default 0,
  trade_date date not null,
  filled_at timestamptz not null default now()
);

create table if not exists public.paper_equity_snapshots_v13 (
  account_name text not null,
  snapshot_date date not null,
  cash numeric not null,
  market_value numeric not null,
  equity numeric not null,
  realized_pnl numeric not null default 0,
  unrealized_pnl numeric not null default 0,
  total_return numeric not null default 0,
  positions_count integer not null default 0,
  created_at timestamptz not null default now(),
  primary key (account_name, snapshot_date)
);

create table if not exists public.paper_engine_runs_v13 (
  id uuid primary key default gen_random_uuid(),
  account_name text not null,
  run_date date not null,
  status text not null
    check (status in ('RUNNING','SUCCESS','SKIPPED','FAILED')),
  signals_date date,
  buy_orders integer not null default 0,
  sell_orders integer not null default 0,
  fills integer not null default 0,
  message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

alter table public.autotrader_configs_v13 enable row level security;
alter table public.trade_orders_v13 enable row level security;
alter table public.paper_positions_v13 enable row level security;
alter table public.paper_accounts_v13 enable row level security;
alter table public.paper_fills_v13 enable row level security;
alter table public.paper_equity_snapshots_v13 enable row level security;
alter table public.paper_engine_runs_v13 enable row level security;

-- Remove and recreate read-only public dashboard policies.
drop policy if exists "v14 read paper config" on public.autotrader_configs_v13;
drop policy if exists "v14 read paper orders" on public.trade_orders_v13;
drop policy if exists "v14 read paper positions" on public.paper_positions_v13;
drop policy if exists "v14 read paper accounts" on public.paper_accounts_v13;
drop policy if exists "v14 read paper fills" on public.paper_fills_v13;
drop policy if exists "v14 read paper snapshots" on public.paper_equity_snapshots_v13;
drop policy if exists "v14 read paper runs" on public.paper_engine_runs_v13;

create policy "v14 read paper config"
  on public.autotrader_configs_v13 for select
  to anon, authenticated using (true);

create policy "v14 read paper orders"
  on public.trade_orders_v13 for select
  to anon, authenticated using (mode = 'PAPER');

create policy "v14 read paper positions"
  on public.paper_positions_v13 for select
  to anon, authenticated using (true);

create policy "v14 read paper accounts"
  on public.paper_accounts_v13 for select
  to anon, authenticated using (true);

create policy "v14 read paper fills"
  on public.paper_fills_v13 for select
  to anon, authenticated using (true);

create policy "v14 read paper snapshots"
  on public.paper_equity_snapshots_v13 for select
  to anon, authenticated using (true);

create policy "v14 read paper runs"
  on public.paper_engine_runs_v13 for select
  to anon, authenticated using (true);

-- No browser write policy is created. Writes require service_role.

insert into public.autotrader_configs_v13 (
  account_name, mode, enabled, kill_switch, starting_cash,
  reserve_cash_pct, max_positions, max_position_pct,
  min_score, max_risk_score, require_approval, auto_fill
)
values (
  'paper-main', 'PAPER', false, false, 1000000,
  30, 5, 15, 40, 60, true, false
)
on conflict (account_name) do nothing;

insert into public.paper_accounts_v13 (
  account_name, starting_cash, cash, equity
)
values ('paper-main', 1000000, 1000000, 1000000)
on conflict (account_name) do nothing;

select
  'GPT Quant V14 database setup complete' as result,
  account_name,
  mode,
  enabled,
  require_approval,
  auto_fill
from public.autotrader_configs_v13
where account_name = 'paper-main';
