#requires -Version 5.1
<#
PHASE3482_CANONICAL_SIGNAL_PERSISTENCE_RUNTIME_SOURCE_ADAPTER_DEPLOY.ps1

GPT Quant V9.2
Phase 3.4.8.2 — Canonical Signal Persistence + Runtime Source Adapter

This deployer creates:
  1) supabase/PHASE3482_CANONICAL_RUNTIME_STORE.sql
  2) automation/v92/paper_trading_phase3482_canonical_signal_persistence_runtime_source_adapter.py
  3) .github/workflows/gpt-quant-v92-paper-trading-phase3482-canonical-signal-persistence-runtime-source-adapter.yml

Design
------
- Discover real signal + market rows from existing Supabase data.
- Persist a canonical, normalized Production Paper runtime snapshot into dedicated
  Phase 3.4.8.2 Supabase tables.
- Re-read the persisted rows as the canonical runtime source.
- Feed those persisted rows directly into Phase 3.4.8 by explicit JSON paths.
- Never use synthetic signals or fake prices.
- Never submit broker orders or touch real money.

IMPORTANT
---------
The SQL file must be applied once in Supabase SQL Editor before the GitHub Action
can persist runtime rows. Until then, the workflow will FAIL-CLOSED with an
actionable "canonical runtime store missing" message.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Section([string]$Text) {
    Write-Host ""
    Write-Host ("=" * 92) -ForegroundColor DarkCyan
    Write-Host $Text -ForegroundColor Cyan
    Write-Host ("=" * 92) -ForegroundColor DarkCyan
}

function Fail([string]$Message) {
    Write-Host ""
    Write-Host "DEPLOY FAILED: $Message" -ForegroundColor Red
    exit 1
}

Section "GPT Quant V9.2 — Phase 3.4.8.2 Deploy"

$repoRoot = $null
try {
    $repoRoot = (& git rev-parse --show-toplevel 2>$null).Trim()
} catch {
    $repoRoot = $null
}

if ([string]::IsNullOrWhiteSpace($repoRoot)) {
    Fail "Run this script inside the GPT Git repository."
}

Set-Location $repoRoot
Write-Host "Repository: $repoRoot" -ForegroundColor Green

$required = @(
    "automation/v92/paper_trading_phase346_production_paper_runtime_execution_gate.py",
    "automation/v92/paper_trading_phase348_canonical_market_signal_to_paper_execution_bridge.py",
    "automation/v92/paper_trading_phase3481_canonical_signal_source_runtime_bridge.py"
)

foreach ($item in $required) {
    if (-not (Test-Path $item)) {
        Fail "Required upstream file not found: $item"
    }
}

$sqlTarget = "supabase/PHASE3482_CANONICAL_RUNTIME_STORE.sql"
$pythonTarget = "automation/v92/paper_trading_phase3482_canonical_signal_persistence_runtime_source_adapter.py"
$workflowTarget = ".github/workflows/gpt-quant-v92-paper-trading-phase3482-canonical-signal-persistence-runtime-source-adapter.yml"

New-Item -ItemType Directory -Force -Path (Split-Path $sqlTarget) | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path $pythonTarget) | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path $workflowTarget) | Out-Null

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backupRoot = Join-Path $repoRoot ".phase3482-backup-$stamp"
New-Item -ItemType Directory -Force -Path $backupRoot | Out-Null

foreach ($target in @($sqlTarget, $pythonTarget, $workflowTarget)) {
    if (Test-Path $target) {
        $dest = Join-Path $backupRoot ($target -replace '[\\/]', '__')
        Copy-Item $target $dest -Force
        Write-Host "Backup: $target -> $dest" -ForegroundColor DarkGray
    }
}

Section "Writing Supabase canonical runtime store SQL"

$sql = @'
-- GPT Quant V9.2
-- Phase 3.4.8.2 — Canonical Signal Persistence + Runtime Source Adapter
--
-- Apply once in Supabase SQL Editor.
-- This creates a dedicated paper-only canonical runtime store.
--
-- NO broker credentials.
-- NO broker orders.
-- NO real-money state.

begin;

create table if not exists public.paper_canonical_signals_v92 (
    id bigint generated by default as identity primary key,
    strategy_version text not null,
    trade_date date not null,
    symbol text not null,
    signal text not null check (signal in ('BUY','LONG')),
    total_score numeric not null,
    source_table text not null,
    source_row_hash text not null,
    canonical_batch_id text not null,
    synthetic_evidence boolean not null default false check (synthetic_evidence = false),
    created_at timestamptz not null default now(),
    unique (strategy_version, trade_date, symbol, canonical_batch_id)
);

create index if not exists idx_paper_canonical_signals_v92_lookup
    on public.paper_canonical_signals_v92
    (strategy_version, trade_date desc, total_score desc);

create table if not exists public.paper_canonical_market_prices_v92 (
    id bigint generated by default as identity primary key,
    trade_date date not null,
    symbol text not null,
    close numeric not null check (close > 0),
    source_table text not null,
    source_row_hash text not null,
    canonical_batch_id text not null,
    synthetic_evidence boolean not null default false check (synthetic_evidence = false),
    created_at timestamptz not null default now(),
    unique (trade_date, symbol, canonical_batch_id)
);

create index if not exists idx_paper_canonical_market_prices_v92_lookup
    on public.paper_canonical_market_prices_v92
    (trade_date desc, symbol);

create table if not exists public.paper_canonical_runtime_batches_v92 (
    canonical_batch_id text primary key,
    strategy_version text not null,
    trade_date date,
    signal_source_table text,
    market_source_table text,
    canonical_signals integer not null default 0 check (canonical_signals >= 0),
    canonical_prices integer not null default 0 check (canonical_prices >= 0),
    status text not null check (
        status in (
            'PERSISTED',
            'NO_SIGNAL',
            'NO_REAL_PRICE',
            'BLOCKED'
        )
    ),
    runtime_execution_gate text not null,
    synthetic_fallback_allowed boolean not null default false check (synthetic_fallback_allowed = false),
    broker_order_submission_enabled boolean not null default false check (broker_order_submission_enabled = false),
    real_money_trading_enabled boolean not null default false check (real_money_trading_enabled = false),
    evidence_sha256 text,
    created_at timestamptz not null default now()
);

alter table public.paper_canonical_signals_v92 enable row level security;
alter table public.paper_canonical_market_prices_v92 enable row level security;
alter table public.paper_canonical_runtime_batches_v92 enable row level security;

-- Intentionally create NO anon/authenticated write policies.
-- GitHub Actions uses the server-side service-role secret for this paper-only store.

comment on table public.paper_canonical_signals_v92 is
'GPT Quant V9.2 paper-only canonical signal persistence. Synthetic evidence forbidden.';

comment on table public.paper_canonical_market_prices_v92 is
'GPT Quant V9.2 paper-only canonical market-price persistence. Synthetic evidence forbidden.';

comment on table public.paper_canonical_runtime_batches_v92 is
'GPT Quant V9.2 canonical runtime batch audit ledger. Broker and real-money flags hard-disabled.';

commit;
'@

Set-Content -LiteralPath $sqlTarget -Value $sql -Encoding UTF8
Write-Host "Wrote: $sqlTarget" -ForegroundColor Green

Section "Writing Phase 3.4.8.2 Python adapter"

$python = @'
#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import quote

import requests

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "phase3482_output"
OUT.mkdir(exist_ok=True)

MODE = "SHADOW_ONLY_NO_BROKER"
STRATEGY = os.getenv("PAPER_STRATEGY_VERSION", "V9.1").strip() or "V9.1"
SCORE_THRESHOLD = float(os.getenv("PHASE3482_SCORE_THRESHOLD", "65"))
MAX_CANDIDATES = int(os.getenv("PHASE3482_MAX_CANDIDATES", "3"))

PHASE346 = ROOT / "automation/v92/paper_trading_phase346_production_paper_runtime_execution_gate.py"
PHASE348 = ROOT / "automation/v92/paper_trading_phase348_canonical_market_signal_to_paper_execution_bridge.py"

GATE_JSON = ROOT / "phase346_output/phase346_runtime_gate.json"
P348_JSON = ROOT / "phase348_output/phase348_execution.json"

CANONICAL_SIGNAL_FILE = OUT / "canonical_signals.persisted.json"
CANONICAL_MARKET_FILE = OUT / "canonical_market_prices.persisted.json"
RESULT_FILE = OUT / "phase3482_runtime_adapter.json"

SIGNAL_STORE = "paper_canonical_signals_v92"
MARKET_STORE = "paper_canonical_market_prices_v92"
BATCH_STORE = "paper_canonical_runtime_batches_v92"

CONTRACT = "PHASE3482_CANONICAL_SIGNAL_PERSISTENCE_RUNTIME_SOURCE_ADAPTER"
SAFETY_CONTRACT = "PERSISTED_REAL_EVIDENCE_ONLY_ZERO_SYNTHETIC_ZERO_BROKER_ZERO_REAL_MONEY"

SIGNAL_TABLE_HINTS = [
    "signals",
    "stock_signals",
    "trading_signals",
    "signal_history",
    "signals_v91",
    "strategy_signals",
]

MARKET_TABLE_HINTS = [
    "market_data",
    "stock_prices",
    "daily_prices",
    "market_daily",
    "market_data_daily",
    "ohlcv_daily",
]


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def stable_hash(payload: Any) -> str:
    raw = json.dumps(
        payload,
        sort_keys=True,
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def dump_json(path: Path, payload: Any) -> None:
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def supabase_config() -> tuple[str, dict[str, str]]:
    base = os.getenv("SUPABASE_URL", "").strip().rstrip("/")
    service_key = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "").strip()

    if not base:
        raise RuntimeError("SUPABASE_URL is missing")
    if not service_key:
        raise RuntimeError(
            "SUPABASE_SERVICE_ROLE_KEY is required for canonical persistence"
        )

    return base, {
        "apikey": service_key,
        "Authorization": f"Bearer {service_key}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }


def rest_get(
    table: str,
    params: list[tuple[str, str]],
) -> tuple[list[dict[str, Any]], str | None]:
    base, headers = supabase_config()
    url = f"{base}/rest/v1/{quote(table, safe='')}"

    try:
        response = requests.get(
            url,
            headers=headers,
            params=params,
            timeout=20,
        )
    except requests.RequestException as exc:
        return [], f"{table}: request error: {exc}"

    if response.status_code >= 400:
        return [], f"{table}: HTTP {response.status_code}"

    try:
        data = response.json()
    except ValueError:
        return [], f"{table}: invalid JSON"

    if not isinstance(data, list):
        return [], f"{table}: response is not a row list"

    return [x for x in data if isinstance(x, dict)], None


def rest_insert(
    table: str,
    rows: list[dict[str, Any]],
) -> None:
    if not rows:
        return

    base, headers = supabase_config()
    headers = dict(headers)
    headers["Prefer"] = "return=minimal,resolution=ignore-duplicates"
    url = f"{base}/rest/v1/{quote(table, safe='')}"

    try:
        response = requests.post(
            url,
            headers=headers,
            data=json.dumps(rows, ensure_ascii=False),
            timeout=20,
        )
    except requests.RequestException as exc:
        raise RuntimeError(f"{table}: persistence request error: {exc}")

    if response.status_code >= 400:
        body = response.text[:800]
        if response.status_code in {404, 400} and (
            "Could not find the table" in body
            or "relation" in body.lower()
            or "schema cache" in body.lower()
        ):
            raise RuntimeError(
                "CANONICAL_RUNTIME_STORE_MISSING: apply "
                "supabase/PHASE3482_CANONICAL_RUNTIME_STORE.sql in Supabase SQL Editor first. "
                f"Underlying error: {table} HTTP {response.status_code}: {body}"
            )
        raise RuntimeError(
            f"{table}: persistence HTTP {response.status_code}: {body}"
        )


def run_script(script: Path, args: list[str], env: dict[str, str]) -> None:
    proc = subprocess.run(
        [sys.executable, str(script), *args],
        cwd=str(ROOT),
        env=env,
        text=True,
        capture_output=True,
    )

    if proc.stdout:
        print(proc.stdout, end="" if proc.stdout.endswith("\n") else "\n")
    if proc.stderr:
        print(proc.stderr, file=sys.stderr, end="" if proc.stderr.endswith("\n") else "\n")

    if proc.returncode != 0:
        raise RuntimeError(
            f"{script.name} failed with exit code {proc.returncode}"
        )


def run_gate(approver: str) -> dict[str, Any]:
    env = os.environ.copy()
    env["PAPER_TRADING_MODE"] = MODE
    env["PAPER_STRATEGY_VERSION"] = STRATEGY
    env["STRATEGY_VERSION"] = STRATEGY

    run_script(
        PHASE346,
        [
            "--approver",
            approver,
            "--note",
            "Phase 3.4.8.2 canonical persistence runtime gate reconstruction",
        ],
        env,
    )

    if not GATE_JSON.exists():
        raise RuntimeError("Phase 3.4.6 gate output missing")

    gate = load_json(GATE_JSON)

    expected = {
        "status": "PASS",
        "runtime_execution_gate": "OPEN",
        "paper_execution_authorized": True,
        "production_paper_release_state": "ACTIVE",
        "broker_order_submission_enabled": False,
        "real_money_trading_enabled": False,
        "live_money_release_authorized": False,
    }

    errors = [
        f"{key}={gate.get(key)!r}, expected={value!r}"
        for key, value in expected.items()
        if gate.get(key) != value
    ]

    if errors:
        raise RuntimeError(
            "Runtime gate validation failed: " + "; ".join(errors)
        )

    return gate


def normalize_signal(row: dict[str, Any], source: str) -> dict[str, Any] | None:
    symbol = str(
        row.get("symbol")
        or row.get("stock_id")
        or row.get("ticker")
        or row.get("stock_symbol")
        or ""
    ).strip()

    if not symbol:
        return None

    signal = str(
        row.get("signal")
        or row.get("action")
        or row.get("recommendation")
        or ""
    ).strip().upper()

    if signal not in {"BUY", "LONG"}:
        return None

    score_raw = (
        row.get("total_score")
        if row.get("total_score") is not None
        else row.get("score")
    )

    try:
        score = float(score_raw)
    except (TypeError, ValueError):
        return None

    if score < SCORE_THRESHOLD:
        return None

    explicit_strategy = row.get("strategy_version") or row.get("strategy")
    if explicit_strategy and str(explicit_strategy).strip().upper() != STRATEGY.upper():
        return None

    trade_date = str(
        row.get("trade_date")
        or row.get("market_date")
        or row.get("date")
        or ""
    ).strip()

    if not trade_date:
        return None

    normalized = {
        "strategy_version": STRATEGY,
        "trade_date": trade_date,
        "symbol": symbol,
        "signal": "BUY",
        "total_score": round(score, 4),
        "source_table": source,
        "synthetic_evidence": False,
    }
    normalized["source_row_hash"] = stable_hash(normalized)
    return normalized


def normalize_market(row: dict[str, Any], source: str) -> dict[str, Any] | None:
    symbol = str(
        row.get("symbol")
        or row.get("stock_id")
        or row.get("ticker")
        or row.get("stock_symbol")
        or ""
    ).strip()

    if not symbol:
        return None

    price = None
    for key in (
        "close",
        "price",
        "last_price",
        "market_price",
        "close_price",
        "reference_price",
    ):
        if row.get(key) is None:
            continue
        try:
            value = float(row[key])
        except (TypeError, ValueError):
            continue
        if value > 0:
            price = value
            break

    if price is None:
        return None

    trade_date = str(
        row.get("trade_date")
        or row.get("market_date")
        or row.get("date")
        or ""
    ).strip()

    if not trade_date:
        return None

    normalized = {
        "trade_date": trade_date,
        "symbol": symbol,
        "close": price,
        "source_table": source,
        "synthetic_evidence": False,
    }
    normalized["source_row_hash"] = stable_hash(normalized)
    return normalized


def discover_signals() -> tuple[list[dict[str, Any]], str | None, list[str]]:
    diagnostics: list[str] = []

    for table in SIGNAL_TABLE_HINTS:
        rows, error = rest_get(
            table,
            [
                ("select", "*"),
                ("order", "trade_date.desc"),
                ("limit", "100"),
            ],
        )

        if error:
            diagnostics.append(error)
            continue

        normalized = [
            item
            for row in rows
            if (item := normalize_signal(row, table)) is not None
        ]

        if not normalized:
            continue

        latest_date = max(x["trade_date"] for x in normalized)
        normalized = [x for x in normalized if x["trade_date"] == latest_date]
        normalized.sort(key=lambda x: (-float(x["total_score"]), x["symbol"]))

        return normalized[:MAX_CANDIDATES], table, diagnostics

    return [], None, diagnostics


def discover_market(
    signals: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], str | None, list[str]]:
    diagnostics: list[str] = []
    symbols = {x["symbol"] for x in signals}

    for table in MARKET_TABLE_HINTS:
        rows, error = rest_get(
            table,
            [
                ("select", "*"),
                ("order", "trade_date.desc"),
                ("limit", "1000"),
            ],
        )

        if error:
            diagnostics.append(error)
            continue

        normalized = [
            item
            for row in rows
            if (item := normalize_market(row, table)) is not None
            and item["symbol"] in symbols
        ]

        if not normalized:
            continue

        latest_by_symbol: dict[str, dict[str, Any]] = {}

        for row in normalized:
            existing = latest_by_symbol.get(row["symbol"])
            if existing is None or row["trade_date"] > existing["trade_date"]:
                latest_by_symbol[row["symbol"]] = row

        return list(latest_by_symbol.values()), table, diagnostics

    return [], None, diagnostics


def persist_canonical(
    gate: dict[str, Any],
    signals: list[dict[str, Any]],
    market_rows: list[dict[str, Any]],
    signal_source: str | None,
    market_source: str | None,
) -> str:
    latest_dates = [x["trade_date"] for x in signals]
    batch_trade_date = max(latest_dates) if latest_dates else None

    seed = {
        "strategy_version": STRATEGY,
        "trade_date": batch_trade_date,
        "signal_hashes": sorted(x["source_row_hash"] for x in signals),
        "market_hashes": sorted(x["source_row_hash"] for x in market_rows),
        "gate_evidence": gate.get("evidence_sha256"),
    }
    batch_id = "P3482-" + stable_hash(seed)[:24]

    signal_rows = [
        {
            **x,
            "canonical_batch_id": batch_id,
        }
        for x in signals
    ]

    market_rows_for_store = [
        {
            **x,
            "canonical_batch_id": batch_id,
        }
        for x in market_rows
    ]

    rest_insert(SIGNAL_STORE, signal_rows)
    rest_insert(MARKET_STORE, market_rows_for_store)

    if not signals:
        status = "NO_SIGNAL"
    elif not market_rows:
        status = "NO_REAL_PRICE"
    else:
        status = "PERSISTED"

    batch_row = {
        "canonical_batch_id": batch_id,
        "strategy_version": STRATEGY,
        "trade_date": batch_trade_date,
        "signal_source_table": signal_source,
        "market_source_table": market_source,
        "canonical_signals": len(signals),
        "canonical_prices": len(market_rows),
        "status": status,
        "runtime_execution_gate": gate["runtime_execution_gate"],
        "synthetic_fallback_allowed": False,
        "broker_order_submission_enabled": False,
        "real_money_trading_enabled": False,
        "evidence_sha256": stable_hash(
            {
                "signals": signal_rows,
                "market": market_rows_for_store,
            }
        ),
    }

    rest_insert(BATCH_STORE, [batch_row])
    return batch_id


def read_persisted_batch(
    batch_id: str,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    signal_rows, signal_error = rest_get(
        SIGNAL_STORE,
        [
            ("select", "*"),
            ("canonical_batch_id", f"eq.{batch_id}"),
            ("order", "total_score.desc"),
        ],
    )

    if signal_error:
        raise RuntimeError(signal_error)

    market_rows, market_error = rest_get(
        MARKET_STORE,
        [
            ("select", "*"),
            ("canonical_batch_id", f"eq.{batch_id}"),
        ],
    )

    if market_error:
        raise RuntimeError(market_error)

    return signal_rows, market_rows


def build_phase348_files(
    signals: list[dict[str, Any]],
    market_rows: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    phase348_signals = [
        {
            "symbol": row["symbol"],
            "trade_date": row["trade_date"],
            "strategy_version": row["strategy_version"],
            "total_score": float(row["total_score"]),
            "signal": row["signal"],
            "canonical_batch_id": row["canonical_batch_id"],
            "source": f"supabase:{SIGNAL_STORE}",
            "synthetic_evidence": False,
        }
        for row in signals
    ]

    phase348_market = [
        {
            "symbol": row["symbol"],
            "market_date": row["trade_date"],
            "close": float(row["close"]),
            "canonical_batch_id": row["canonical_batch_id"],
            "source": f"supabase:{MARKET_STORE}",
            "synthetic_evidence": False,
        }
        for row in market_rows
    ]

    dump_json(CANONICAL_SIGNAL_FILE, {"signals": phase348_signals})
    dump_json(CANONICAL_MARKET_FILE, {"data": phase348_market})

    return phase348_signals, phase348_market


def run_phase348(
    approver: str,
) -> dict[str, Any]:
    env = os.environ.copy()
    env["PAPER_TRADING_MODE"] = MODE
    env["PAPER_STRATEGY_VERSION"] = STRATEGY
    env["STRATEGY_VERSION"] = STRATEGY
    env["PHASE348_SIGNAL_JSON"] = str(CANONICAL_SIGNAL_FILE)
    env["PHASE348_MARKET_JSON"] = str(CANONICAL_MARKET_FILE)
    env["PHASE348_SCORE_THRESHOLD"] = str(SCORE_THRESHOLD)
    env["PHASE348_MAX_CANDIDATES"] = str(MAX_CANDIDATES)

    run_script(PHASE348, ["--approver", approver], env)

    if not P348_JSON.exists():
        raise RuntimeError("Phase 3.4.8 output missing")

    result = load_json(P348_JSON)

    if result.get("status") != "PASS":
        raise RuntimeError("Phase 3.4.8 did not PASS")

    if result.get("synthetic_fallback_allowed") is not False:
        raise RuntimeError("Synthetic fallback safety violation")

    if result.get("synthetic_evidence_present") is not False:
        raise RuntimeError("Synthetic evidence safety violation")

    return result


def write_summary(result: dict[str, Any]) -> None:
    result["evidence_sha256"] = stable_hash(result)
    dump_json(RESULT_FILE, result)

    lines = [
        "# GPT Quant V9.2 Paper Trading - Phase 3.4.8.2",
        "",
        "## Canonical Signal Persistence + Runtime Source Adapter",
        "",
        f"- Strategy: `{result['strategy_version']}`",
        f"- Trading Mode: `{result['trading_mode']}`",
        f"- Adapter Contract: **{result['adapter_contract']}**",
        f"- Runtime Execution Gate: **{result['runtime_execution_gate']}**",
        "",
        "### Canonical Persistence",
        "",
        f"- Canonical Batch ID: `{result['canonical_batch_id'] or 'NONE'}`",
        f"- Discovered Signal Source: `{result['discovered_signal_source'] or 'NONE'}`",
        f"- Discovered Market Source: `{result['discovered_market_source'] or 'NONE'}`",
        f"- Signals Persisted: **{result['signals_persisted']}**",
        f"- Market Prices Persisted: **{result['market_prices_persisted']}**",
        f"- Runtime Signal Source: `{result['runtime_signal_source']}`",
        f"- Runtime Market Source: `{result['runtime_market_source']}`",
        "",
        "### Phase 3.4.8 Execution",
        "",
        f"- Execution State: **{result['phase348_execution_state']}**",
        f"- Paper Orders Created: **{result['paper_orders_created']}**",
        f"- Simulated Fills: **{result['simulated_fills']}**",
        f"- Open Paper Positions: **{result['open_positions']}**",
        "",
        "### Safety Boundary",
        "",
        "- Synthetic fallback allowed: **NO**",
        "- Synthetic evidence present: **NO**",
        "- Broker API used: **NO**",
        "- Broker credentials used: **NO**",
        "- Broker order submission: **DISABLED**",
        "- Real-money trading: **DISABLED**",
        "- Live-money release authorized: **NO**",
        "- Fail-closed policy: **ENABLED**",
        (
            "- Fail-closed triggered: "
            f"**{'YES' if result['fail_closed_triggered'] else 'NO'}**"
        ),
        f"- Evidence SHA256: `{result['evidence_sha256']}`",
    ]

    if result.get("diagnostics"):
        lines.extend(["", "### Source Diagnostics", ""])
        lines.extend(f"- {x}" for x in result["diagnostics"][:24])

    text = "\n".join(lines) + "\n"
    (OUT / "phase3482_runtime_adapter.md").write_text(text, encoding="utf-8")

    gh = os.getenv("GITHUB_STEP_SUMMARY")
    if gh:
        with open(gh, "a", encoding="utf-8") as handle:
            handle.write(text)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--approver",
        default=os.getenv("PHASE3482_APPROVER", "rchu9246"),
    )
    args = parser.parse_args()

    approver = args.approver.strip()
    if not approver:
        raise RuntimeError("Approver must not be empty")

    if MODE != "SHADOW_ONLY_NO_BROKER":
        raise RuntimeError(
            "Safety violation: mode must remain SHADOW_ONLY_NO_BROKER"
        )

    gate = run_gate(approver)

    signals, signal_source, signal_diag = discover_signals()
    diagnostics = list(signal_diag)

    market_rows: list[dict[str, Any]] = []
    market_source: str | None = None

    if signals:
        market_rows, market_source, market_diag = discover_market(signals)
        diagnostics.extend(market_diag)

    batch_id = persist_canonical(
        gate,
        signals,
        market_rows,
        signal_source,
        market_source,
    )

    persisted_signals, persisted_market = read_persisted_batch(batch_id)

    # Persistence round-trip is the source of truth from here onward.
    phase348_signals, phase348_market = build_phase348_files(
        persisted_signals,
        persisted_market,
    )

    phase348 = run_phase348(approver)

    result = {
        "version": "3.4.8.2",
        "status": "PASS",
        "checked_at": now_iso(),
        "strategy_version": STRATEGY,
        "trading_mode": MODE,
        "adapter_contract": CONTRACT,
        "safety_contract": SAFETY_CONTRACT,
        "runtime_execution_gate": gate["runtime_execution_gate"],
        "canonical_batch_id": batch_id,
        "discovered_signal_source": signal_source,
        "discovered_market_source": market_source,
        "signals_persisted": len(persisted_signals),
        "market_prices_persisted": len(persisted_market),
        "runtime_signal_source": f"supabase:{SIGNAL_STORE}",
        "runtime_market_source": f"supabase:{MARKET_STORE}",
        "phase348_execution_state": phase348.get("execution_state"),
        "paper_orders_created": phase348.get("paper_orders_created", 0),
        "simulated_fills": phase348.get("simulated_fills", 0),
        "open_positions": phase348.get("open_positions", 0),
        "synthetic_fallback_allowed": False,
        "synthetic_evidence_present": False,
        "broker_api_used": False,
        "broker_credentials_used": False,
        "broker_order_submission_enabled": False,
        "real_money_trading_enabled": False,
        "live_money_release_authorized": False,
        "fail_closed_policy": True,
        "fail_closed_triggered": False,
        "diagnostics": diagnostics,
    }

    if result["paper_orders_created"] > 0:
        if result["signals_persisted"] <= 0 or result["market_prices_persisted"] <= 0:
            raise RuntimeError(
                "Safety violation: paper orders exist without persisted canonical evidence"
            )
        if result["phase348_execution_state"] != "REAL_CANONICAL_EVIDENCE_EXECUTED":
            raise RuntimeError(
                "Unexpected Phase 3.4.8 execution state for non-zero orders"
            )

    for order in phase348.get("orders", []):
        if order.get("synthetic_evidence") is not False:
            raise RuntimeError("Synthetic order evidence detected")
        if order.get("broker_submitted") is not False:
            raise RuntimeError("Broker submission safety violation")
        if order.get("real_money") is not False:
            raise RuntimeError("Real-money safety violation")

    write_summary(result)
    print(json.dumps(result, ensure_ascii=False, indent=2))
    print(
        "PHASE3482 PASS: canonical persistence round-trip complete. "
        f"signals={len(persisted_signals)}, prices={len(persisted_market)}, "
        f"orders={result['paper_orders_created']}, fills={result['simulated_fills']}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'@

Set-Content -LiteralPath $pythonTarget -Value $python -Encoding UTF8
Write-Host "Wrote: $pythonTarget" -ForegroundColor Green

Section "Writing Phase 3.4.8.2 GitHub Actions workflow"

$workflow = @'
name: GPT Quant Phase 3.4.8.2 - Canonical Signal Persistence Runtime Source Adapter

on:
  workflow_dispatch:
    inputs:
      strategy_version:
        description: Strategy version
        required: true
        default: V9.1
        type: string

      approver:
        description: Human approver/operator ID for same-run gate reconstruction
        required: true
        default: rchu9246
        type: string

      score_threshold:
        description: Minimum canonical signal score
        required: true
        default: "65"
        type: string

      max_candidates:
        description: Maximum canonical signals per runtime batch
        required: true
        default: "3"
        type: string

permissions:
  contents: read

concurrency:
  group: gpt-quant-phase3482-canonical-persistence-runtime-adapter
  cancel-in-progress: false

jobs:
  canonical-persistence-runtime-adapter:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      PAPER_STRATEGY_VERSION: ${{ inputs.strategy_version || 'V9.1' }}
      STRATEGY_VERSION: ${{ inputs.strategy_version || 'V9.1' }}
      PAPER_TRADING_MODE: SHADOW_ONLY_NO_BROKER

      PHASE3421_REQUIRED_PASS_DAYS: "5"
      PHASE344_REQUIRED_PASS_DAYS: "5"
      PHASE345_REQUIRED_PASS_DAYS: "5"
      PHASE346_REQUIRED_PASS_DAYS: "5"

      PHASE3482_SCORE_THRESHOLD: ${{ inputs.score_threshold || '65' }}
      PHASE3482_MAX_CANDIDATES: ${{ inputs.max_candidates || '3' }}

      PHASE348_SCORE_THRESHOLD: ${{ inputs.score_threshold || '65' }}
      PHASE348_MAX_CANDIDATES: ${{ inputs.max_candidates || '3' }}
      PHASE348_INITIAL_CASH: "1000000"
      PHASE348_MAX_POSITION_PCT: "0.20"
      PHASE348_ROUND_LOT: "1000"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install runtime dependency
        run: python -m pip install --upgrade pip requests

      - name: Validate Phase 3.4.8.2 safety contract
        shell: bash
        run: |
          set -euo pipefail

          test -n "${SUPABASE_URL:-}"
          test -n "${SUPABASE_SERVICE_ROLE_KEY:-}"

          test -f automation/v92/paper_trading_phase3482_canonical_signal_persistence_runtime_source_adapter.py
          test -f automation/v92/paper_trading_phase348_canonical_market_signal_to_paper_execution_bridge.py
          test -f supabase/PHASE3482_CANONICAL_RUNTIME_STORE.sql

          grep -q 'PERSISTED_REAL_EVIDENCE_ONLY_ZERO_SYNTHETIC_ZERO_BROKER_ZERO_REAL_MONEY' \
            automation/v92/paper_trading_phase3482_canonical_signal_persistence_runtime_source_adapter.py

          grep -q '"synthetic_fallback_allowed": False' \
            automation/v92/paper_trading_phase3482_canonical_signal_persistence_runtime_source_adapter.py

          grep -q '"broker_order_submission_enabled": False' \
            automation/v92/paper_trading_phase3482_canonical_signal_persistence_runtime_source_adapter.py

          grep -q '"real_money_trading_enabled": False' \
            automation/v92/paper_trading_phase3482_canonical_signal_persistence_runtime_source_adapter.py

          echo "Phase 3.4.8.2 safety contract: PASS"

      - name: Execute Phase 3.4.8.2 canonical persistence adapter
        shell: bash
        run: |
          set -euo pipefail

          python automation/v92/paper_trading_phase3482_canonical_signal_persistence_runtime_source_adapter.py \
            --approver "${{ inputs.approver }}"

      - name: Validate Phase 3.4.8.2 output
        shell: bash
        run: |
          set -euo pipefail

          test -f phase3482_output/phase3482_runtime_adapter.json
          test -f phase3482_output/canonical_signals.persisted.json
          test -f phase3482_output/canonical_market_prices.persisted.json
          test -f phase348_output/phase348_execution.json

          python - <<'PY'
          import json
          from pathlib import Path

          data = json.loads(
              Path("phase3482_output/phase3482_runtime_adapter.json").read_text(
                  encoding="utf-8"
              )
          )

          p348 = json.loads(
              Path("phase348_output/phase348_execution.json").read_text(
                  encoding="utf-8"
              )
          )

          assert data["version"] == "3.4.8.2", data
          assert data["status"] == "PASS", data
          assert data["runtime_execution_gate"] == "OPEN", data
          assert data["canonical_batch_id"], data

          assert data["runtime_signal_source"] == "supabase:paper_canonical_signals_v92", data
          assert data["runtime_market_source"] == "supabase:paper_canonical_market_prices_v92", data

          assert data["synthetic_fallback_allowed"] is False, data
          assert data["synthetic_evidence_present"] is False, data
          assert data["broker_api_used"] is False, data
          assert data["broker_credentials_used"] is False, data
          assert data["broker_order_submission_enabled"] is False, data
          assert data["real_money_trading_enabled"] is False, data
          assert data["live_money_release_authorized"] is False, data
          assert data["fail_closed_policy"] is True, data
          assert data["fail_closed_triggered"] is False, data

          assert p348["synthetic_fallback_allowed"] is False, p348
          assert p348["synthetic_evidence_present"] is False, p348

          if data["paper_orders_created"] > 0:
              assert data["signals_persisted"] > 0, data
              assert data["market_prices_persisted"] > 0, data
              assert data["phase348_execution_state"] == "REAL_CANONICAL_EVIDENCE_EXECUTED", data
              assert data["simulated_fills"] == data["paper_orders_created"], data
          else:
              assert data["phase348_execution_state"] in {
                  "NO_CANONICAL_SIGNAL_ZERO_ORDERS",
                  "NO_REAL_MARKET_PRICE_ZERO_ORDERS",
                  "REAL_EVIDENCE_BUT_ZERO_SIZED_ORDERS",
              }, data

          print("Phase 3.4.8.2 output validation: PASS")
          PY

      - name: Upload Phase 3.4.8.2 evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phase3482-canonical-persistence-${{ github.run_id }}
          path: |
            phase3421_output/
            phase342_output/
            phase3442_output/
            phase344_output/
            phase345_output/
            phase3451_output/
            phase346_output/
            phase348_output/
            phase3482_output/
          if-no-files-found: warn
          retention-days: 90
'@

Set-Content -LiteralPath $workflowTarget -Value $workflow -Encoding UTF8
Write-Host "Wrote: $workflowTarget" -ForegroundColor Green

Section "Static validation"

$pythonCmd = $null
if (Get-Command python -ErrorAction SilentlyContinue) {
    $pythonCmd = "python"
} elseif (Get-Command py -ErrorAction SilentlyContinue) {
    $pythonCmd = "py"
} else {
    Fail "Python was not found in PATH."
}

if ($pythonCmd -eq "py") {
    & py -3 -m py_compile $pythonTarget
} else {
    & python -m py_compile $pythonTarget
}

if ($LASTEXITCODE -ne 0) {
    Fail "Python compile validation failed."
}

Write-Host "Python compile: PASS" -ForegroundColor Green

$source = Get-Content -LiteralPath $pythonTarget -Raw
$needles = @(
    'PHASE3482_CANONICAL_SIGNAL_PERSISTENCE_RUNTIME_SOURCE_ADAPTER',
    'PERSISTED_REAL_EVIDENCE_ONLY_ZERO_SYNTHETIC_ZERO_BROKER_ZERO_REAL_MONEY',
    'paper_canonical_signals_v92',
    'paper_canonical_market_prices_v92',
    'paper_canonical_runtime_batches_v92',
    '"synthetic_fallback_allowed": False',
    '"broker_order_submission_enabled": False',
    '"real_money_trading_enabled": False'
)

foreach ($needle in $needles) {
    if (-not $source.Contains($needle)) {
        Fail "Required Phase 3.4.8.2 token missing: $needle"
    }
}

Write-Host "Phase 3.4.8.2 static contract scan: PASS" -ForegroundColor Green

Section "Git diff"
& git status --short
& git diff -- $sqlTarget $pythonTarget $workflowTarget

Section "DEPLOY COMPLETE"

Write-Host "Created/updated:" -ForegroundColor Green
Write-Host "  $sqlTarget"
Write-Host "  $pythonTarget"
Write-Host "  $workflowTarget"
Write-Host ""

Write-Host "IMPORTANT — one-time Supabase step:" -ForegroundColor Yellow
Write-Host "  Open Supabase -> SQL Editor"
Write-Host "  Paste and run: supabase/PHASE3482_CANONICAL_RUNTIME_STORE.sql"
Write-Host "  Do this BEFORE running the Phase 3.4.8.2 GitHub Action."
Write-Host ""

Write-Host "Desired runtime result:" -ForegroundColor Cyan
Write-Host "  Runtime Signal Source: supabase:paper_canonical_signals_v92"
Write-Host "  Runtime Market Source: supabase:paper_canonical_market_prices_v92"
Write-Host "  Signals Persisted: > 0 (when eligible source rows exist)"
Write-Host "  Market Prices Persisted: > 0 (when real prices exist)"
Write-Host "  Phase 3.4.8 Execution State: REAL_CANONICAL_EVIDENCE_EXECUTED"
Write-Host ""

Write-Host "Safe zero-order states remain valid:" -ForegroundColor Yellow
Write-Host "  NO_CANONICAL_SIGNAL_ZERO_ORDERS"
Write-Host "  NO_REAL_MARKET_PRICE_ZERO_ORDERS"
Write-Host ""

Write-Host "Hard safety locks:" -ForegroundColor Yellow
Write-Host "  Synthetic fallback: DISABLED"
Write-Host "  Broker API used: NO"
Write-Host "  Broker order submission: DISABLED"
Write-Host "  Real-money trading: DISABLED"
Write-Host "  Live-money release authorized: NO"
Write-Host ""

Write-Host "Next:" -ForegroundColor Yellow
Write-Host "  1) Apply the generated SQL once in Supabase SQL Editor."
Write-Host "  2) Review GitHub Desktop changes."
Write-Host "  3) Commit and Push origin."
Write-Host "  4) GitHub Actions -> GPT Quant Phase 3.4.8.2."
Write-Host "  5) Run with defaults and inspect persistence + execution state."
Write-Host ""
Write-Host "Backup folder: $backupRoot" -ForegroundColor DarkGray
