#requires -Version 5.1
<#
PHASE3691_DAILY_EVIDENCE_LIFECYCLE_PERSISTENCE_SCHEMA_RECOVERY_FIX_DEPLOY.ps1

GPT Quant V9.2
Phase 3.6.9.1 — Daily Evidence Lifecycle Persistence Schema Recovery Fix

Root cause addressed
--------------------
The Phase 3.6.9 SQL file existed but was empty, so Supabase never created:
  public.paper_daily_lifecycle_evidence_v92
  public.paper_daily_lifecycle_evidence_audit_v92

That caused GitHub Actions / PostgREST:
  PGRST205
  Could not find public.paper_daily_lifecycle_evidence_v92

This recovery package:
  1) overwrites the Phase 3.6.9 SQL with a complete non-empty schema;
  2) preserves canonical table names used by the Phase 3.6.9 Python engine;
  3) adds schema-cache notification;
  4) validates SQL file size/content locally;
  5) validates Phase 3.6.9 Python canonical table references;
  6) leaves all broker / real-money capabilities hard-disabled.

Created/overwritten
-------------------
  supabase/PHASE369_PRODUCTION_PAPER_AUTONOMOUS_DAILY_EVIDENCE_LIFECYCLE_GOVERNANCE_ENGINE.sql
  supabase/PHASE3691_DAILY_EVIDENCE_LIFECYCLE_PERSISTENCE_SCHEMA_RECOVERY_FIX.sql
  .github/workflows/gpt-quant-v92-paper-trading-phase3691-daily-evidence-lifecycle-persistence-schema-recovery-fix.yml
#>

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Section([string]$Text) {
    Write-Host ""
    Write-Host ("=" * 118) -ForegroundColor DarkCyan
    Write-Host $Text -ForegroundColor Cyan
    Write-Host ("=" * 118) -ForegroundColor DarkCyan
}

function Fail([string]$Text) {
    Write-Host ""
    Write-Host "DEPLOY FAILED: $Text" -ForegroundColor Red
    exit 1
}

function Write-Utf8NoBom([string]$Path, [string]$Content) {
    $parent = Split-Path -Parent $Path
    if ($parent -and -not (Test-Path $parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $enc)
}

Section "GPT Quant V9.2 — Phase 3.6.9.1 Lifecycle Persistence Schema Recovery"

$repo = $null
try {
    $repo = (& git rev-parse --show-toplevel 2>$null).Trim()
} catch {
    $repo = $null
}

if ([string]::IsNullOrWhiteSpace($repo)) {
    Fail "Run this package from inside the GPT Git repository."
}

Set-Location $repo
Write-Host "Repository: $repo" -ForegroundColor Green

$phase369Py = Join-Path $repo "automation\v92\paper_trading_phase369_production_paper_autonomous_daily_evidence_lifecycle_governance_engine.py"
if (-not (Test-Path $phase369Py)) {
    Fail "Phase 3.6.9 Python engine not found: $phase369Py"
}

$phase369Sql = Join-Path $repo "supabase\PHASE369_PRODUCTION_PAPER_AUTONOMOUS_DAILY_EVIDENCE_LIFECYCLE_GOVERNANCE_ENGINE.sql"
$phase3691Sql = Join-Path $repo "supabase\PHASE3691_DAILY_EVIDENCE_LIFECYCLE_PERSISTENCE_SCHEMA_RECOVERY_FIX.sql"
$phase3691Yml = Join-Path $repo ".github\workflows\gpt-quant-v92-paper-trading-phase3691-daily-evidence-lifecycle-persistence-schema-recovery-fix.yml"

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backupRoot = Join-Path $repo ".phase3691-backup-$stamp"
New-Item -ItemType Directory -Force -Path $backupRoot | Out-Null

foreach ($target in @($phase369Sql, $phase3691Sql, $phase3691Yml)) {
    if (Test-Path $target) {
        Copy-Item $target (Join-Path $backupRoot ([IO.Path]::GetFileName($target))) -Force
    }
}

Section "Writing canonical Phase 3.6.9 schema"

$sql = @'
begin;

create table if not exists public.paper_daily_lifecycle_evidence_v92 (
    id bigint generated by default as identity primary key,
    evidence_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE369_PRODUCTION_PAPER_AUTONOMOUS_DAILY_EVIDENCE_LIFECYCLE_GOVERNANCE_ENGINE',

    lifecycle_sequence bigint not null,
    lifecycle_state text not null,
    lifecycle_passed boolean not null default false,

    controller_state text not null default 'UNKNOWN',
    activation_state text not null default 'UNKNOWN',
    qualification_state text not null default 'UNKNOWN',
    runtime_supervision_state text not null default 'UNKNOWN',
    runtime_supervision_score numeric not null default 0,
    master_cycle_state text not null default 'UNKNOWN',

    autonomous_daily_operations_authorized boolean not null default false,
    daily_paper_cycle_executed boolean not null default false,
    safety_revocation_triggered boolean not null default false,

    eligible_signals integer not null default 0,
    sized_candidates integer not null default 0,
    order_intents_created integer not null default 0,
    simulated_fills_created integer not null default 0,
    fills_settled integer not null default 0,

    cash numeric not null default 0,
    market_value numeric not null default 0,
    nav numeric not null default 0,
    realized_pnl numeric not null default 0,
    unrealized_pnl numeric not null default 0,
    open_positions integer not null default 0,

    previous_evidence_sha256 text not null,
    source_controller_evidence_sha256 text,
    source_master_evidence_sha256 text,
    reason_codes jsonb not null default '[]'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase369_lifecycle_state check (
        lifecycle_state in (
            'PASS',
            'PASS_WITH_OBSERVATION',
            'BLOCKED',
            'FAIL_CLOSED'
        )
    ),
    constraint ck_phase369_paper_only check (paper_only = true),
    constraint ck_phase369_no_broker_api check (broker_api_used = false),
    constraint ck_phase369_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase369_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase369_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase369_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase369_fail_closed check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_daily_lifecycle_evidence_v92_portfolio_date
    on public.paper_daily_lifecycle_evidence_v92 (portfolio_id, evidence_date);

create unique index if not exists uq_paper_daily_lifecycle_evidence_v92_portfolio_sequence
    on public.paper_daily_lifecycle_evidence_v92 (portfolio_id, lifecycle_sequence);

create index if not exists ix_paper_daily_lifecycle_evidence_v92_state_date
    on public.paper_daily_lifecycle_evidence_v92 (lifecycle_state, evidence_date desc);

create table if not exists public.paper_daily_lifecycle_evidence_audit_v92 (
    id bigint generated by default as identity primary key,
    evidence_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE369_PRODUCTION_PAPER_AUTONOMOUS_DAILY_EVIDENCE_LIFECYCLE_GOVERNANCE_ENGINE',

    lifecycle_sequence bigint not null,
    lifecycle_state text not null,
    lifecycle_passed boolean not null default false,

    controller_state text not null default 'UNKNOWN',
    activation_state text not null default 'UNKNOWN',
    qualification_state text not null default 'UNKNOWN',
    runtime_supervision_state text not null default 'UNKNOWN',
    runtime_supervision_score numeric not null default 0,
    master_cycle_state text not null default 'UNKNOWN',

    autonomous_daily_operations_authorized boolean not null default false,
    daily_paper_cycle_executed boolean not null default false,
    safety_revocation_triggered boolean not null default false,

    eligible_signals integer not null default 0,
    sized_candidates integer not null default 0,
    order_intents_created integer not null default 0,
    simulated_fills_created integer not null default 0,
    fills_settled integer not null default 0,

    cash numeric not null default 0,
    market_value numeric not null default 0,
    nav numeric not null default 0,
    realized_pnl numeric not null default 0,
    unrealized_pnl numeric not null default 0,
    open_positions integer not null default 0,

    previous_evidence_sha256 text not null,
    source_controller_evidence_sha256 text,
    source_master_evidence_sha256 text,
    reason_codes jsonb not null default '[]'::jsonb,
    evidence_document jsonb not null default '{}'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),

    constraint ck_phase369_audit_paper_only check (paper_only = true),
    constraint ck_phase369_audit_no_broker_api check (broker_api_used = false),
    constraint ck_phase369_audit_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase369_audit_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase369_audit_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase369_audit_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase369_audit_fail_closed check (fail_closed_policy = true)
);

create index if not exists ix_paper_daily_lifecycle_evidence_audit_v92_portfolio_created
    on public.paper_daily_lifecycle_evidence_audit_v92 (portfolio_id, created_at desc);

alter table public.paper_daily_lifecycle_evidence_v92 enable row level security;
alter table public.paper_daily_lifecycle_evidence_audit_v92 enable row level security;

comment on table public.paper_daily_lifecycle_evidence_v92 is
'GPT Quant V9.2 Phase 3.6.9 canonical daily autonomous lifecycle evidence state. Paper-only and fail-closed.';

comment on table public.paper_daily_lifecycle_evidence_audit_v92 is
'GPT Quant V9.2 Phase 3.6.9 immutable-style lifecycle evidence audit with SHA256 chain.';

-- Ask PostgREST to reload schema metadata after DDL.
notify pgrst, 'reload schema';

commit;
'@

Write-Utf8NoBom $phase369Sql $sql
Write-Utf8NoBom $phase3691Sql $sql

Write-Host "Wrote canonical SQL: $phase369Sql" -ForegroundColor Green
Write-Host "Wrote recovery SQL : $phase3691Sql" -ForegroundColor Green

Section "Writing Phase 3.6.9.1 verification workflow"

$yml = @'
name: GPT Quant Phase 3.6.9.1 - Daily Evidence Lifecycle Persistence Schema Recovery Fix

on:
  workflow_dispatch:
    inputs:
      strategy_version:
        description: Strategy version
        required: true
        default: V9.1
        type: string
      portfolio_id:
        description: Persistent paper portfolio ID
        required: true
        default: V92_PRODUCTION_PAPER_V91
        type: string

permissions:
  contents: read

jobs:
  lifecycle-persistence-schema-recovery:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      STRATEGY_VERSION: ${{ inputs.strategy_version || 'V9.1' }}
      PORTFOLIO_ID: ${{ inputs.portfolio_id || 'V92_PRODUCTION_PAPER_V91' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Compile Phase 3.6.9
        shell: bash
        run: |
          python -m py_compile automation/v92/paper_trading_phase369_production_paper_autonomous_daily_evidence_lifecycle_governance_engine.py

      - name: Validate canonical persistence contract
        shell: bash
        run: |
          set -euo pipefail

          test -s supabase/PHASE369_PRODUCTION_PAPER_AUTONOMOUS_DAILY_EVIDENCE_LIFECYCLE_GOVERNANCE_ENGINE.sql

          grep -q 'create table if not exists public.paper_daily_lifecycle_evidence_v92' \
            supabase/PHASE369_PRODUCTION_PAPER_AUTONOMOUS_DAILY_EVIDENCE_LIFECYCLE_GOVERNANCE_ENGINE.sql

          grep -q 'create table if not exists public.paper_daily_lifecycle_evidence_audit_v92' \
            supabase/PHASE369_PRODUCTION_PAPER_AUTONOMOUS_DAILY_EVIDENCE_LIFECYCLE_GOVERNANCE_ENGINE.sql

          grep -q '"paper_daily_lifecycle_evidence_v92"' \
            automation/v92/paper_trading_phase369_production_paper_autonomous_daily_evidence_lifecycle_governance_engine.py

          grep -q '"paper_daily_lifecycle_evidence_audit_v92"' \
            automation/v92/paper_trading_phase369_production_paper_autonomous_daily_evidence_lifecycle_governance_engine.py

          echo "Phase 3.6.9.1 canonical persistence contract: PASS"

      - name: Verify Supabase lifecycle tables through REST
        shell: python
        run: |
          import json
          import os
          import urllib.error
          import urllib.parse
          import urllib.request

          url = os.environ["SUPABASE_URL"].rstrip("/")
          key = os.environ["SUPABASE_SERVICE_ROLE_KEY"]
          portfolio_id = os.environ["PORTFOLIO_ID"]

          tables = [
              "paper_daily_lifecycle_evidence_v92",
              "paper_daily_lifecycle_evidence_audit_v92",
          ]

          lines = [
              "# GPT Quant V9.2 Paper Trading - Phase 3.6.9.1",
              "",
              "## Daily Evidence Lifecycle Persistence Schema Recovery Fix",
              "",
          ]

          for table in tables:
              endpoint = (
                  f"{url}/rest/v1/{table}"
                  "?select=id"
                  "&limit=1"
              )
              req = urllib.request.Request(
                  endpoint,
                  headers={
                      "apikey": key,
                      "Authorization": f"Bearer {key}",
                      "Accept": "application/json",
                  },
              )
              try:
                  with urllib.request.urlopen(req, timeout=30) as response:
                      response.read()
                  lines.append(f"- `{table}`: **FOUND**")
              except urllib.error.HTTPError as exc:
                  body = exc.read().decode("utf-8", errors="replace")
                  raise SystemExit(f"{table} REST verification failed: HTTP {exc.code}: {body}")

          lines += [
              "",
              "## Recovery Result",
              "",
              "- Canonical lifecycle evidence table: **PASS**",
              "- Canonical lifecycle audit table: **PASS**",
              "- PostgREST schema visibility: **PASS**",
              "- Phase 3.6.9 ready to re-run: **YES**",
              "",
              "## Safety Boundary",
              "",
              "- Paper only: **ENABLED**",
              "- Broker order submission: **DISABLED**",
              "- Real-money trading: **DISABLED**",
              "- Live-money release authorized: **NO**",
              "- Fail-closed policy: **ENABLED**",
          ]

          summary = "\n".join(lines)
          print(summary)

          with open(os.environ["GITHUB_STEP_SUMMARY"], "a", encoding="utf-8") as f:
              f.write(summary + "\n")
'@

Write-Utf8NoBom $phase3691Yml $yml
Write-Host "Wrote: $phase3691Yml" -ForegroundColor Green

Section "Static validation"

$phase369SqlText = Get-Content -LiteralPath $phase369Sql -Raw
$phase3691SqlText = Get-Content -LiteralPath $phase3691Sql -Raw
$phase369PyText = Get-Content -LiteralPath $phase369Py -Raw

if ([string]::IsNullOrWhiteSpace($phase369SqlText)) {
    Fail "Canonical Phase 3.6.9 SQL is still empty."
}

if ((Get-Item $phase369Sql).Length -lt 4000) {
    Fail "Canonical Phase 3.6.9 SQL is unexpectedly small: $((Get-Item $phase369Sql).Length) bytes"
}

foreach ($token in @(
    "paper_daily_lifecycle_evidence_v92",
    "paper_daily_lifecycle_evidence_audit_v92",
    "previous_evidence_sha256",
    "evidence_sha256",
    "notify pgrst"
)) {
    if (-not $phase369SqlText.Contains($token)) {
        Fail "Canonical Phase 3.6.9 SQL token missing: $token"
    }
}

foreach ($token in @(
    '"paper_daily_lifecycle_evidence_v92"',
    '"paper_daily_lifecycle_evidence_audit_v92"'
)) {
    if (-not $phase369PyText.Contains($token)) {
        Fail "Phase 3.6.9 Python canonical table reference missing: $token"
    }
}

foreach ($forbidden in @(
    "broker_api_used boolean not null default true",
    "broker_credentials_used boolean not null default true",
    "broker_order_submission_enabled boolean not null default true",
    "real_money_trading_enabled boolean not null default true",
    "live_money_release_authorized boolean not null default true"
)) {
    if ($phase369SqlText.ToLowerInvariant().Contains($forbidden)) {
        Fail "Forbidden safety capability enabled in SQL: $forbidden"
    }
}

Write-Host "Canonical Phase 3.6.9 SQL non-empty check: PASS" -ForegroundColor Green
Write-Host "Canonical lifecycle table-name alignment: PASS" -ForegroundColor Green
Write-Host "PostgREST schema reload contract: PASS" -ForegroundColor Green
Write-Host "Paper-only safety boundary scan: PASS" -ForegroundColor Green

Section "Git status"
& git status --short

Section "DEPLOY COMPLETE"

Write-Host "Generated/overwritten:" -ForegroundColor Green
Write-Host "  supabase/PHASE369_PRODUCTION_PAPER_AUTONOMOUS_DAILY_EVIDENCE_LIFECYCLE_GOVERNANCE_ENGINE.sql"
Write-Host "  supabase/PHASE3691_DAILY_EVIDENCE_LIFECYCLE_PERSISTENCE_SCHEMA_RECOVERY_FIX.sql"
Write-Host "  .github/workflows/gpt-quant-v92-paper-trading-phase3691-daily-evidence-lifecycle-persistence-schema-recovery-fix.yml"
Write-Host ""
Write-Host "Recovered canonical tables:" -ForegroundColor Cyan
Write-Host "  public.paper_daily_lifecycle_evidence_v92"
Write-Host "  public.paper_daily_lifecycle_evidence_audit_v92"
Write-Host ""
Write-Host "Expected local validation:" -ForegroundColor Cyan
Write-Host "  Canonical Phase 3.6.9 SQL non-empty check: PASS"
Write-Host "  Canonical lifecycle table-name alignment: PASS"
Write-Host "  PostgREST schema reload contract: PASS"
Write-Host "  Paper-only safety boundary scan: PASS"
Write-Host ""
Write-Host "Next:" -ForegroundColor Yellow
Write-Host "  1) Open supabase/PHASE3691_DAILY_EVIDENCE_LIFECYCLE_PERSISTENCE_SCHEMA_RECOVERY_FIX.sql."
Write-Host "  2) Confirm the file is NOT empty."
Write-Host "  3) Run that SQL once in Supabase SQL Editor."
Write-Host "  4) Commit and Push generated changes."
Write-Host "  5) Run Phase 3.6.9.1 GitHub Action and confirm both tables FOUND."
Write-Host "  6) Then re-run Phase 3.6.9."
Write-Host ""
Write-Host "Backup: $backupRoot" -ForegroundColor DarkGray
