#requires -Version 5.1
<#
GPT Quant V9.2
Phase 3.7.2.6.1 V6
Canonical Audit Table PostgREST Exposure Recovery

Purpose
-------
Repair the remaining PostgREST 404/PGRST205 for the canonical audit table:

  public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92

Observed state
--------------
V5/V5.1 successfully forced the verifier to request the correct canonical table,
but PostgREST still returned HTTP 404.

This V6 deployment creates/repairs the canonical audit table, applies explicit
API grants, reloads PostgREST schema metadata, and installs a verifier workflow.

Safety boundary
---------------
- Historical rewrite: DISABLED
- Broker API: NOT USED
- Broker credentials: NOT USED
- Broker order submission: DISABLED
- Real-money trading: DISABLED
- Live-money release: NOT AUTHORIZED
- Paper-only: ENFORCED

Generated
---------
  supabase/PHASE37261_V6_CANONICAL_AUDIT_TABLE_POSTGREST_EXPOSURE_RECOVERY.sql
  automation/v92/paper_trading_phase37261_v6_canonical_audit_table_postgrest_exposure_recovery_verify.py
  .github/workflows/gpt-quant-v92-paper-trading-phase37261-v6-canonical-audit-table-postgrest-exposure-recovery.yml
#>

param(
    [switch]$AutoGit
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Section([string]$Text) {
    Write-Host ""
    Write-Host ("=" * 118) -ForegroundColor DarkCyan
    Write-Host $Text -ForegroundColor Cyan
    Write-Host ("=" * 118) -ForegroundColor DarkCyan
}

function Fail([string]$Text) {
    Write-Host ""
    Write-Host "PHASE37261_V6_FATAL: $Text" -ForegroundColor Red
    exit 1
}

function WriteUtf8([string]$Path, [string]$Text) {
    $parent = Split-Path -Parent $Path
    if ($parent -and -not (Test-Path $parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Text, $enc)
}

Section "GPT Quant V9.2 — Phase 3.7.2.6.1 V6 PostgREST Exposure Recovery"

try {
    $repo = (& git rev-parse --show-toplevel 2>$null).Trim()
} catch {
    $repo = ""
}

if ([string]::IsNullOrWhiteSpace($repo)) {
    Fail "Run this deployment from inside the GPT Git repository."
}

Set-Location $repo
Write-Host "Repository: $repo" -ForegroundColor Green

$required = @(
    "automation/v92/paper_trading_phase37261_post_recovery_activation_master_cycle_canonical_state_reconstruction.py",
    "automation/v92/paper_trading_phase37261_v3_reconstruction_audit_schema_recovery_verify.py"
)

foreach ($item in $required) {
    if (-not (Test-Path $item)) {
        Fail "Required dependency missing: $item"
    }
}

$sqlTarget = Join-Path $repo "supabase\PHASE37261_V6_CANONICAL_AUDIT_TABLE_POSTGREST_EXPOSURE_RECOVERY.sql"
$pyTarget  = Join-Path $repo "automation\v92\paper_trading_phase37261_v6_canonical_audit_table_postgrest_exposure_recovery_verify.py"
$ymlTarget = Join-Path $repo ".github\workflows\gpt-quant-v92-paper-trading-phase37261-v6-canonical-audit-table-postgrest-exposure-recovery.yml"

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backup = Join-Path $repo ".phase37261-v6-backup-$stamp"
New-Item -ItemType Directory -Force -Path $backup | Out-Null

foreach ($target in @($sqlTarget, $pyTarget, $ymlTarget)) {
    if (Test-Path $target) {
        Copy-Item $target (Join-Path $backup ([IO.Path]::GetFileName($target))) -Force
    }
}

Section "1/4 — Write canonical audit table exposure-recovery SQL"

$sql = @'
begin;

create table if not exists public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92 (
    id bigint generated by default as identity primary key,

    reconstruction_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE37261_POST_RECOVERY_ACTIVATION_MASTER_CYCLE_CANONICAL_STATE_RECONSTRUCTION',

    activation_table text not null,
    master_cycle_table text not null,

    activation_state text not null,
    master_cycle_state text not null,
    runtime_supervision_state text not null,

    historical_rewrite_allowed boolean not null default false,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    evidence_document jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now()
);

-- Repair missing columns safely in case an earlier partial table exists.
alter table public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    add column if not exists reconstruction_date date,
    add column if not exists portfolio_id text,
    add column if not exists strategy_version text default 'V9.1',
    add column if not exists contract text default 'PHASE37261_POST_RECOVERY_ACTIVATION_MASTER_CYCLE_CANONICAL_STATE_RECONSTRUCTION',
    add column if not exists activation_table text,
    add column if not exists master_cycle_table text,
    add column if not exists activation_state text,
    add column if not exists master_cycle_state text,
    add column if not exists runtime_supervision_state text,
    add column if not exists historical_rewrite_allowed boolean default false,
    add column if not exists paper_only boolean default true,
    add column if not exists broker_api_used boolean default false,
    add column if not exists broker_credentials_used boolean default false,
    add column if not exists broker_order_submission_enabled boolean default false,
    add column if not exists real_money_trading_enabled boolean default false,
    add column if not exists live_money_release_authorized boolean default false,
    add column if not exists fail_closed_policy boolean default true,
    add column if not exists evidence_sha256 text,
    add column if not exists evidence_document jsonb default '{}'::jsonb,
    add column if not exists created_at timestamptz default now();

create index if not exists ix_phase37261_v6_reconstruction_audit_portfolio_created
    on public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    (portfolio_id, created_at desc);

alter table public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    enable row level security;

-- Explicit API visibility/grants. Service-role writes remain the intended runtime path.
grant usage on schema public to anon, authenticated, service_role;
grant select on public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    to anon, authenticated, service_role;
grant insert on public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    to service_role;
grant usage, select on sequence public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92_id_seq
    to service_role;

comment on table public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92 is
'GPT Quant V9.2 Phase 3.7.2.6.1 canonical reconstruction audit table. Paper-only, append-only runtime usage.';

-- Ask PostgREST to refresh its schema cache.
notify pgrst, 'reload schema';

commit;
'@

WriteUtf8 $sqlTarget $sql
Write-Host "Wrote: $sqlTarget" -ForegroundColor Green

Section "2/4 — Write deterministic PostgREST verifier"

$py = @'
#!/usr/bin/env python3

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone

CONTRACT = "PHASE37261_V6_CANONICAL_AUDIT_TABLE_POSTGREST_EXPOSURE_RECOVERY"
CANONICAL_AUDIT_TABLE = "paper_post_recovery_activation_master_cycle_reconstruction_audit_v92"

BROKER_API_USED = False
BROKER_CREDENTIALS_USED = False
BROKER_ORDER_SUBMISSION_ENABLED = False
REAL_MONEY_TRADING_ENABLED = False
LIVE_MONEY_RELEASE_AUTHORIZED = False
HISTORICAL_REWRITE_ALLOWED = False


def require(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value


def main() -> int:
    supabase_url = require("SUPABASE_URL").rstrip("/")
    service_key = require("SUPABASE_SERVICE_ROLE_KEY")

    query = urllib.parse.urlencode({
        "select": "id,reconstruction_date,portfolio_id,activation_state,master_cycle_state,runtime_supervision_state",
        "limit": "1",
    })

    target = f"/rest/v1/{CANONICAL_AUDIT_TABLE}"
    url = f"{supabase_url}{target}?{query}"

    req = urllib.request.Request(
        url,
        method="GET",
        headers={
            "apikey": service_key,
            "Authorization": f"Bearer {service_key}",
            "Accept": "application/json",
        },
    )

    print("# GPT Quant V9.2 Paper Trading - Phase 3.7.2.6.1 V6")
    print("")
    print("## Canonical Audit Table PostgREST Exposure Recovery")
    print("")
    print(f"- Contract: `{CONTRACT}`")
    print(f"- Verification Date: `{datetime.now(timezone.utc).date().isoformat()}`")
    print(f"- Resolved Audit Table: `{CANONICAL_AUDIT_TABLE}`")
    print(f"- PostgREST Request Target: `{target}`")
    print("- Verification Mode: **READ_ONLY**")
    print("- Historical Rewrite Allowed: **NO**")
    print("")

    try:
        with urllib.request.urlopen(req, timeout=45) as response:
            status = response.getcode()
            body = response.read().decode("utf-8", errors="replace")

        if not (200 <= status < 300):
            raise RuntimeError(f"Unexpected HTTP status: {status}")

        rows = json.loads(body or "[]")
        if not isinstance(rows, list):
            raise RuntimeError("Canonical audit endpoint did not return a JSON array")

        print("## Verification Result")
        print("")
        print("- PostgREST Schema Visibility: **PASS**")
        print(f"- HTTP Status: **{status}**")
        print("- Canonical Resolver: **LOCKED_TO_V92**")
        print("- PGRST205: **NOT_PRESENT**")
        print(f"- Rows Sampled: **{len(rows)}**")
        print("")
        print("## Safety Boundary")
        print("")
        print("- Paper only: **ENABLED**")
        print("- Broker API used: **NO**")
        print("- Broker credentials used: **NO**")
        print("- Broker order submission: **DISABLED**")
        print("- Real-money trading: **DISABLED**")
        print("- Live-money release authorized: **NO**")
        print("- Historical evidence rewrite: **DISABLED**")
        return 0

    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        print("## Verification Result")
        print("")
        print("- PostgREST Schema Visibility: **FAIL**")
        print(f"- HTTP Status: **{exc.code}**")
        print(f"- Resolved Audit Table: `{CANONICAL_AUDIT_TABLE}`")
        print(f"- Actual Request Target: `{target}`")
        print("")
        print("```json")
        print(body[:4000])
        print("```")
        raise RuntimeError(
            f"Canonical audit table exposure verification failed: HTTP {exc.code}: {body}"
        ) from exc


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"PHASE37261_V6_FATAL: {exc}", file=sys.stderr)
        raise
'@

WriteUtf8 $pyTarget $py
Write-Host "Wrote: $pyTarget" -ForegroundColor Green

Section "3/4 — Write verification workflow"

$yml = @'
name: GPT Quant Phase 3.7.2.6.1 V6 - Canonical Audit Table PostgREST Exposure Recovery

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: phase37261-v6-postgrest-exposure-recovery
  cancel-in-progress: false

jobs:
  canonical-audit-postgrest-exposure-recovery:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Compile V6 verifier
        shell: bash
        run: |
          python -m py_compile automation/v92/paper_trading_phase37261_v6_canonical_audit_table_postgrest_exposure_recovery_verify.py

      - name: Validate V6 contract
        shell: bash
        run: |
          set -euo pipefail

          test -n "${SUPABASE_URL:-}"
          test -n "${SUPABASE_SERVICE_ROLE_KEY:-}"

          FILE="automation/v92/paper_trading_phase37261_v6_canonical_audit_table_postgrest_exposure_recovery_verify.py"

          grep -q 'PHASE37261_V6_CANONICAL_AUDIT_TABLE_POSTGREST_EXPOSURE_RECOVERY' "$FILE"
          grep -q 'paper_post_recovery_activation_master_cycle_reconstruction_audit_v92' "$FILE"
          grep -q 'BROKER_ORDER_SUBMISSION_ENABLED = False' "$FILE"
          grep -q 'REAL_MONEY_TRADING_ENABLED = False' "$FILE"
          grep -q 'HISTORICAL_REWRITE_ALLOWED = False' "$FILE"

          echo "Phase 3.7.2.6.1 V6 verifier contract: PASS"

      - name: Verify canonical audit PostgREST exposure
        shell: bash
        run: |
          mkdir -p artifacts/phase37261-v6

          python automation/v92/paper_trading_phase37261_v6_canonical_audit_table_postgrest_exposure_recovery_verify.py \
            | tee artifacts/phase37261-v6/summary.md

      - name: Publish summary
        if: always()
        shell: bash
        run: |
          if [ -f artifacts/phase37261-v6/summary.md ]; then
            cat artifacts/phase37261-v6/summary.md >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Upload verification evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phase37261-v6-postgrest-exposure-recovery
          path: artifacts/phase37261-v6/
          if-no-files-found: warn
          retention-days: 120
'@

WriteUtf8 $ymlTarget $yml
Write-Host "Wrote: $ymlTarget" -ForegroundColor Green

Section "4/4 — Static validation"

$pythonExe = $null
if (Get-Command python -ErrorAction SilentlyContinue) {
    $pythonExe = "python"
} elseif (Get-Command py -ErrorAction SilentlyContinue) {
    $pythonExe = "py"
} else {
    Fail "Python is not available in PATH."
}

if ($pythonExe -eq "py") {
    & py -3 -m py_compile $pyTarget
} else {
    & python -m py_compile $pyTarget
}

if ($LASTEXITCODE -ne 0) {
    Fail "V6 verifier Python compile failed."
}

$combined = (Get-Content -LiteralPath $sqlTarget -Raw) + "`n" +
            (Get-Content -LiteralPath $pyTarget -Raw) + "`n" +
            (Get-Content -LiteralPath $ymlTarget -Raw)

foreach ($token in @(
    "PHASE37261_V6_CANONICAL_AUDIT_TABLE_POSTGREST_EXPOSURE_RECOVERY",
    "paper_post_recovery_activation_master_cycle_reconstruction_audit_v92",
    "notify pgrst, 'reload schema'",
    "grant select on public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92",
    "PostgREST Schema Visibility: **PASS**"
)) {
    if (-not $combined.Contains($token)) {
        Fail "Required V6 token missing: $token"
    }
}

foreach ($forbidden in @(
    '"broker_api_used": True',
    '"broker_credentials_used": True',
    '"broker_order_submission_enabled": True',
    '"real_money_trading_enabled": True',
    '"live_money_release_authorized": True'
)) {
    if ($combined.Contains($forbidden)) {
        Fail "Forbidden capability detected: $forbidden"
    }
}

Write-Host "Python compile: PASS" -ForegroundColor Green
Write-Host "Canonical audit table schema recovery scan: PASS" -ForegroundColor Green
Write-Host "PostgREST schema reload scan: PASS" -ForegroundColor Green
Write-Host "API grants scan: PASS" -ForegroundColor Green
Write-Host "Paper-only safety boundary scan: PASS" -ForegroundColor Green

Section "Git status"
& git status --short

if ($AutoGit) {
    $branch = (& git rev-parse --abbrev-ref HEAD).Trim()
    if ($branch -ne "main") {
        Fail "AutoGit requires branch main. Current branch: $branch"
    }

    & git add -- $sqlTarget $pyTarget $ymlTarget
    if ($LASTEXITCODE -ne 0) {
        Fail "git add failed."
    }

    $staged = (& git diff --cached --name-only)
    if (-not [string]::IsNullOrWhiteSpace(($staged -join "`n"))) {
        & git commit -m "Deploy Phase 37261 V6 PostgREST exposure recovery"
        if ($LASTEXITCODE -ne 0) {
            Fail "git commit failed."
        }

        & git push origin main
        if ($LASTEXITCODE -ne 0) {
            Fail "git push failed."
        }

        Write-Host "Commit + Push: PASS" -ForegroundColor Green
    }
}

Section "PHASE37261 V6 DEPLOYMENT COMPLETE"

Write-Host "Generated:" -ForegroundColor Green
Write-Host "  supabase/PHASE37261_V6_CANONICAL_AUDIT_TABLE_POSTGREST_EXPOSURE_RECOVERY.sql"
Write-Host "  automation/v92/paper_trading_phase37261_v6_canonical_audit_table_postgrest_exposure_recovery_verify.py"
Write-Host "  .github/workflows/gpt-quant-v92-paper-trading-phase37261-v6-canonical-audit-table-postgrest-exposure-recovery.yml"
Write-Host ""
Write-Host "IMPORTANT: This V6 DOES require the Supabase SQL to be run once." -ForegroundColor Yellow
Write-Host ""
Write-Host "Next:" -ForegroundColor Yellow
Write-Host "  1) Run the generated V6 SQL in Supabase SQL Editor."
Write-Host "  2) Commit and Push generated files."
Write-Host "  3) Run GitHub Action:"
Write-Host "     GPT Quant Phase 3.7.2.6.1 V6 - Canonical Audit Table PostgREST Exposure Recovery"
Write-Host "  4) Confirm PostgREST Schema Visibility = PASS."
Write-Host "  5) Then re-run Phase 3.7.2.6.1 reconstruction."
Write-Host ""
Write-Host "Backup: $backup" -ForegroundColor DarkGray
