#requires -Version 5.1
<#
GPT Quant V9.2
Phase 3.7.2.6.1 V6.1
Canonical Audit Sequence + PostgREST Exposure Compatibility Fix

Purpose
-------
Fix the Supabase SQL failure:

  ERROR: 42809:
  "..._audit" is not a sequence

Root cause
----------
V6 hard-coded a sequence grant for:
  paper_post_recovery_activation_master_cycle_reconstruction_audit_v92_id_seq

The actual identity/sequence ownership in the deployed schema can differ, and a
hard-coded sequence name is not portable.

This V6.1 patch:
  1) replaces the V6 SQL with a compatibility-safe version;
  2) removes hard-coded sequence grants;
  3) grants table access explicitly;
  4) dynamically discovers the serial/identity sequence with pg_get_serial_sequence;
  5) grants sequence usage/select only if a real sequence exists;
  6) reloads PostgREST schema cache;
  7) keeps paper-only and fail-closed boundaries intact;
  8) does not rewrite historical evidence.

Target SQL
----------
supabase/PHASE37261_V6_CANONICAL_AUDIT_TABLE_POSTGREST_EXPOSURE_RECOVERY.sql

No Python or workflow changes are required for V6.1.
#>

param(
    [switch]$AutoGit
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Section([string]$Text) {
    Write-Host ""
    Write-Host ("=" * 118) -ForegroundColor DarkCyan
    Write-Host $Text -ForegroundColor Cyan
    Write-Host ("=" * 118) -ForegroundColor DarkCyan
}

function Fail([string]$Text) {
    Write-Host ""
    Write-Host "PHASE37261_V61_FATAL: $Text" -ForegroundColor Red
    exit 1
}

function WriteUtf8([string]$Path, [string]$Text) {
    $parent = Split-Path -Parent $Path
    if ($parent -and -not (Test-Path $parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Text, $enc)
}

Section "GPT Quant V9.2 — Phase 3.7.2.6.1 V6.1 Sequence + PostgREST Compatibility Fix"

try {
    $repo = (& git rev-parse --show-toplevel 2>$null).Trim()
} catch {
    $repo = ""
}

if ([string]::IsNullOrWhiteSpace($repo)) {
    Fail "Run this patch from inside the GPT Git repository."
}

Set-Location $repo
Write-Host "Repository: $repo" -ForegroundColor Green

$sqlTarget = Join-Path $repo "supabase\PHASE37261_V6_CANONICAL_AUDIT_TABLE_POSTGREST_EXPOSURE_RECOVERY.sql"

if (-not (Test-Path $sqlTarget)) {
    Fail "V6 SQL target not found: $sqlTarget"
}

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backup = Join-Path $repo ".phase37261-v61-backup-$stamp"
New-Item -ItemType Directory -Force -Path $backup | Out-Null
Copy-Item $sqlTarget (Join-Path $backup ([IO.Path]::GetFileName($sqlTarget))) -Force

Section "1/3 — Overwrite V6 SQL with sequence-compatible exposure recovery"

$sql = @'
begin;

create table if not exists public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92 (
    id bigint generated by default as identity primary key,

    reconstruction_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE37261_POST_RECOVERY_ACTIVATION_MASTER_CYCLE_CANONICAL_STATE_RECONSTRUCTION',

    activation_table text not null,
    master_cycle_table text not null,

    activation_state text not null,
    master_cycle_state text not null,
    runtime_supervision_state text not null,

    historical_rewrite_allowed boolean not null default false,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    evidence_document jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now()
);

-- Compatibility repair in case an earlier partial table exists.
alter table public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    add column if not exists reconstruction_date date,
    add column if not exists portfolio_id text,
    add column if not exists strategy_version text default 'V9.1',
    add column if not exists contract text default 'PHASE37261_POST_RECOVERY_ACTIVATION_MASTER_CYCLE_CANONICAL_STATE_RECONSTRUCTION',
    add column if not exists activation_table text,
    add column if not exists master_cycle_table text,
    add column if not exists activation_state text,
    add column if not exists master_cycle_state text,
    add column if not exists runtime_supervision_state text,
    add column if not exists historical_rewrite_allowed boolean default false,
    add column if not exists paper_only boolean default true,
    add column if not exists broker_api_used boolean default false,
    add column if not exists broker_credentials_used boolean default false,
    add column if not exists broker_order_submission_enabled boolean default false,
    add column if not exists real_money_trading_enabled boolean default false,
    add column if not exists live_money_release_authorized boolean default false,
    add column if not exists fail_closed_policy boolean default true,
    add column if not exists evidence_sha256 text,
    add column if not exists evidence_document jsonb default '{}'::jsonb,
    add column if not exists created_at timestamptz default now();

create index if not exists ix_phase37261_v6_reconstruction_audit_portfolio_created
    on public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    (portfolio_id, created_at desc);

alter table public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    enable row level security;

-- Explicit API visibility.
grant usage on schema public to anon, authenticated, service_role;

grant select on public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    to anon, authenticated, service_role;

grant insert on public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    to service_role;

-- Sequence compatibility:
-- Discover the actual identity/serial sequence instead of assuming its name.
do $$
declare
    seq_name text;
begin
    seq_name := pg_get_serial_sequence(
        'public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92',
        'id'
    );

    if seq_name is not null then
        execute format(
            'grant usage, select on sequence %s to service_role',
            seq_name
        );
    end if;
end
$$;

comment on table public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92 is
'GPT Quant V9.2 Phase 3.7.2.6.1 canonical reconstruction audit table. Paper-only, append-only runtime usage.';

-- Refresh PostgREST metadata after DDL/grants.
notify pgrst, 'reload schema';

commit;
'@

WriteUtf8 $sqlTarget $sql
Write-Host "Patched: $sqlTarget" -ForegroundColor Green

Section "2/3 — Static validation"

$final = Get-Content -LiteralPath $sqlTarget -Raw

foreach ($token in @(
    "pg_get_serial_sequence",
    "grant select on public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92",
    "grant insert on public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92",
    "notify pgrst, 'reload schema'",
    "paper_post_recovery_activation_master_cycle_reconstruction_audit_v92"
)) {
    if (-not $final.Contains($token)) {
        Fail "Required V6.1 SQL token missing: $token"
    }
}

if ($final.Contains("paper_post_recovery_activation_master_cycle_reconstruction_audit_v92_id_seq")) {
    Fail "Hard-coded sequence name still exists."
}

Write-Host "Dynamic sequence discovery: PASS" -ForegroundColor Green
Write-Host "Hard-coded sequence grant removal: PASS" -ForegroundColor Green
Write-Host "Canonical table grants: PASS" -ForegroundColor Green
Write-Host "PostgREST schema reload: PASS" -ForegroundColor Green
Write-Host "Historical rewrite behavior: UNCHANGED" -ForegroundColor Green

Section "3/3 — Git status"

& git status --short

if ($AutoGit) {
    $branch = (& git rev-parse --abbrev-ref HEAD).Trim()

    if ($branch -ne "main") {
        Fail "AutoGit requires branch main. Current branch: $branch"
    }

    & git add -- $sqlTarget
    if ($LASTEXITCODE -ne 0) {
        Fail "git add failed."
    }

    $staged = (& git diff --cached --name-only)
    if (-not [string]::IsNullOrWhiteSpace(($staged -join "`n"))) {
        & git commit -m "Fix Phase 37261 V6 audit sequence compatibility"
        if ($LASTEXITCODE -ne 0) {
            Fail "git commit failed."
        }

        & git push origin main
        if ($LASTEXITCODE -ne 0) {
            Fail "git push failed."
        }

        Write-Host "Commit + Push: PASS" -ForegroundColor Green
    } else {
        Write-Host "No staged SQL changes." -ForegroundColor Yellow
    }
}

Section "PHASE37261 V6.1 PATCH COMPLETE"

Write-Host "This patch modifies only the V6 Supabase SQL." -ForegroundColor Cyan
Write-Host ""
Write-Host "Next:" -ForegroundColor Yellow
Write-Host "  1) Re-open:"
Write-Host "     supabase/PHASE37261_V6_CANONICAL_AUDIT_TABLE_POSTGREST_EXPOSURE_RECOVERY.sql"
Write-Host "  2) Copy ALL SQL into Supabase SQL Editor."
Write-Host "  3) Run it once."
Write-Host "  4) Expected result: Success. No rows returned."
Write-Host "  5) Commit + Push the patched SQL."
Write-Host "  6) Run:"
Write-Host "     GPT Quant Phase 3.7.2.6.1 V6 - Canonical Audit Table PostgREST Exposure Recovery"
Write-Host "  7) Confirm:"
Write-Host "     PostgREST Schema Visibility: PASS"
Write-Host "     HTTP Status: 200"
Write-Host "     PGRST205: NOT_PRESENT"
Write-Host ""
Write-Host "Backup: $backup" -ForegroundColor DarkGray
