$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

Write-Host "PHASE379 - Production Paper Qualification State Reconciliation + Automatic Promotion Readiness" -ForegroundColor Cyan
Write-Host "Safety boundary: PAPER ONLY / broker submission DISABLED / real money DISABLED" -ForegroundColor Green

$repo = (Get-Location).Path
$sqlRel = "supabase/PHASE379_PRODUCTION_PAPER_QUALIFICATION_STATE_RECONCILIATION_AUTOMATIC_PROMOTION_READINESS.sql"
$pyRel = "automation/v92/paper_trading_phase379_production_paper_qualification_state_reconciliation_automatic_promotion_readiness.py"
$ymlRel = ".github/workflows/gpt-quant-v92-paper-trading-phase379-production-paper-qualification-state-reconciliation-automatic-promotion-readiness.yml"

$sqlPath = Join-Path $repo $sqlRel
$pyPath = Join-Path $repo $pyRel
$ymlPath = Join-Path $repo $ymlRel

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backup = Join-Path $repo ".phase379-backup-$stamp"
New-Item -ItemType Directory -Force -Path $backup | Out-Null

foreach ($p in @($sqlPath,$pyPath,$ymlPath)) {
    if (Test-Path $p) {
        Copy-Item $p (Join-Path $backup (Split-Path $p -Leaf)) -Force
    }
}

$sqlText = @'
-- GPT Quant V9.2
-- Phase 3.7.9 — Production Paper Qualification State Reconciliation
-- + Automatic Promotion Readiness

create table if not exists public.paper_production_promotion_readiness_v92 (
    id bigint generated by default as identity primary key,
    portfolio_id text not null,
    strategy_version text not null,
    readiness_date date not null,
    qualification_state text not null,
    promotion_readiness_state text not null,
    promotion_ready boolean not null default false,
    observed_cycles integer not null default 0,
    valid_cycles integer not null default 0,
    blocked_cycles integer not null default 0,
    runtime_supervision_pass boolean not null default false,
    paper_only_boundary_pass boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    historical_rewrite_allowed boolean not null default false,
    source_phase375_run_id text,
    source_phase376_run_id text,
    reconciliation_hash text not null,
    raw_state jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists uq_paper_production_promotion_readiness_v92_day
on public.paper_production_promotion_readiness_v92
(portfolio_id, strategy_version, readiness_date);

create unique index if not exists uq_paper_production_promotion_readiness_v92_hash
on public.paper_production_promotion_readiness_v92
(reconciliation_hash);

create index if not exists ix_paper_production_promotion_readiness_v92_state
on public.paper_production_promotion_readiness_v92
(portfolio_id, strategy_version, readiness_date desc);

alter table public.paper_production_promotion_readiness_v92 enable row level security;

revoke all on table public.paper_production_promotion_readiness_v92 from anon, authenticated;
grant select, insert, update on table public.paper_production_promotion_readiness_v92 to service_role;

comment on table public.paper_production_promotion_readiness_v92 is
'GPT Quant Phase 3.7.9 canonical production-paper qualification reconciliation and automatic promotion-readiness state. Paper-only; no broker or real-money execution.';

notify pgrst, 'reload schema';

select
  'PHASE379_READY' as phase379_state,
  to_regclass('public.paper_production_promotion_readiness_v92') as canonical_table;
'@
$pyText = @'
#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import os
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

CONTRACT = "PHASE379_PRODUCTION_PAPER_QUALIFICATION_STATE_RECONCILIATION_AUTOMATIC_PROMOTION_READINESS"
PORTFOLIO_ID = os.getenv("GPT_QUANT_PORTFOLIO_ID", "V92_PRODUCTION_PAPER_V91")
STRATEGY_VERSION = os.getenv("GPT_QUANT_STRATEGY_VERSION", "V9.1")

PHASE375_RESULT_PATH = Path(os.getenv("PHASE375_RESULT_PATH", "artifacts/phase379/input/phase375_result.json"))
PHASE376_RESULT_PATH = Path(os.getenv("PHASE376_RESULT_PATH", "artifacts/phase379/input/phase376_result.json"))

TARGET_TABLE = "paper_production_promotion_readiness_v92"

PAPER_ONLY = True
BROKER_ORDER_SUBMISSION_ENABLED = False
REAL_MONEY_TRADING_ENABLED = False
HISTORICAL_REWRITE_ALLOWED = False

def env_first(*names: str) -> Optional[str]:
    for n in names:
        v = os.getenv(n)
        if v and v.strip():
            return v.strip().rstrip("/")
    return None

SUPABASE_URL = env_first("SUPABASE_URL", "VITE_SUPABASE_URL")
SUPABASE_KEY = env_first("SUPABASE_SERVICE_ROLE_KEY", "SUPABASE_SERVICE_KEY")

def request(method: str, path: str, body: Optional[Any] = None, prefer: str = "") -> Any:
    if not SUPABASE_URL or not SUPABASE_KEY:
        raise RuntimeError("SUPABASE_CONFIGURATION_MISSING")
    data = None if body is None else json.dumps(body).encode("utf-8")
    headers = {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Accept": "application/json",
        "Content-Type": "application/json",
    }
    if prefer:
        headers["Prefer"] = prefer

    req = urllib.request.Request(
        f"{SUPABASE_URL}/rest/v1/{path}",
        data=data,
        headers=headers,
        method=method,
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            raw = r.read().decode("utf-8")
            return json.loads(raw) if raw else None
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {e.code}: {detail}") from e

def load_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        obj = json.loads(path.read_text(encoding="utf-8"))
        return obj if isinstance(obj, dict) else {}
    except Exception:
        return {}

def b(v: Any) -> bool:
    if isinstance(v, bool):
        return v
    return str(v).strip().upper() in {"TRUE", "YES", "Y", "1", "PASS", "ENABLED"}

def digest(payload: Dict[str, Any]) -> str:
    stable = json.dumps(payload, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(stable.encode("utf-8")).hexdigest()

def main() -> int:
    art = Path("artifacts/phase379")
    art.mkdir(parents=True, exist_ok=True)

    p375 = load_json(PHASE375_RESULT_PATH)
    p376 = load_json(PHASE376_RESULT_PATH)

    blockers: List[str] = []

    p375_present = bool(p375)
    p376_present = bool(p376)

    p375_state = str(p375.get("state", "")).strip().upper()
    p375_qualified = b(p375.get("qualified", False))
    p375_operational = b(p375.get("operational", False))

    p375_checks = p375.get("checks", {}) if isinstance(p375.get("checks"), dict) else {}
    p375_counts = p375.get("evidence_counts", {}) if isinstance(p375.get("evidence_counts"), dict) else {}

    runtime_pass = str(p375_checks.get("runtime_supervision", "")).upper() == "PASS"
    observed = int(p375_counts.get("observed", 0) or 0)
    valid = int(p375_counts.get("valid", 0) or 0)
    blocked = int(p375_counts.get("blocked", 0) or 0)

    p376_state = str(p376.get("state", "")).strip().upper()
    p376_authorized = b(p376.get("promotion_authorized", False))
    p376_operational = b(p376.get("operational", False))

    if p375_present and p375_state == "MULTI_CYCLE_STABILITY_BLOCKED":
        blockers.append("PHASE375_BLOCKED")
    if p376_present and p376_state == "PRODUCTION_PAPER_PROMOTION_BLOCKED":
        blockers.append("PHASE376_BLOCKED")
    if blocked > 0:
        blockers.append(f"BLOCKED_CYCLES_PRESENT:{blocked}")

    qualification_ready = (
        p375_present
        and p375_state == "MULTI_CYCLE_STABILITY_QUALIFIED"
        and p375_qualified
        and p375_operational
        and runtime_pass
        and observed >= 3
        and valid >= 3
        and blocked == 0
    )

    gate_ready = (
        p376_present
        and p376_state == "PRODUCTION_PAPER_PROMOTION_AUTHORIZED"
        and p376_authorized
        and p376_operational
    )

    if blockers:
        state = "PROMOTION_READINESS_BLOCKED"
        promotion_ready = False
        operational = False
    elif qualification_ready and gate_ready:
        state = "PROMOTION_READINESS_READY"
        promotion_ready = True
        operational = True
    else:
        state = "PROMOTION_READINESS_WAITING"
        promotion_ready = False
        operational = True

    payload = {
        "contract": CONTRACT,
        "portfolio_id": PORTFOLIO_ID,
        "strategy_version": STRATEGY_VERSION,
        "evaluated_at": datetime.now(timezone.utc).isoformat(),
        "qualification_state": p375_state or "NOT_AVAILABLE",
        "promotion_gate_state": p376_state or "NOT_AVAILABLE",
        "promotion_readiness_state": state,
        "promotion_ready": promotion_ready,
        "operational": operational,
        "blockers": blockers,
        "counts": {
            "observed": observed,
            "valid": valid,
            "blocked": blocked,
        },
        "checks": {
            "phase375_present": p375_present,
            "phase376_present": p376_present,
            "runtime_supervision_pass": runtime_pass,
            "phase375_qualified": p375_qualified,
            "phase376_authorized": p376_authorized,
            "qualification_ready": qualification_ready,
            "gate_ready": gate_ready,
        },
        "safety": {
            "paper_only": PAPER_ONLY,
            "broker_order_submission_enabled": BROKER_ORDER_SUBMISSION_ENABLED,
            "real_money_trading_enabled": REAL_MONEY_TRADING_ENABLED,
            "historical_rewrite_allowed": HISTORICAL_REWRITE_ALLOWED,
        },
    }

    readiness_date = datetime.now(timezone.utc).date().isoformat()
    row = {
        "portfolio_id": PORTFOLIO_ID,
        "strategy_version": STRATEGY_VERSION,
        "readiness_date": readiness_date,
        "qualification_state": payload["qualification_state"],
        "promotion_readiness_state": state,
        "promotion_ready": promotion_ready,
        "observed_cycles": observed,
        "valid_cycles": valid,
        "blocked_cycles": blocked,
        "runtime_supervision_pass": runtime_pass,
        "paper_only_boundary_pass": True,
        "broker_order_submission_enabled": False,
        "real_money_trading_enabled": False,
        "historical_rewrite_allowed": False,
        "source_phase375_run_id": os.getenv("PHASE375_RUN_ID"),
        "source_phase376_run_id": os.getenv("PHASE376_RUN_ID"),
        "raw_state": payload,
    }
    row["reconciliation_hash"] = digest({
        "portfolio_id": PORTFOLIO_ID,
        "strategy_version": STRATEGY_VERSION,
        "readiness_date": readiness_date,
        "qualification_state": row["qualification_state"],
        "promotion_readiness_state": state,
        "promotion_ready": promotion_ready,
        "observed_cycles": observed,
        "valid_cycles": valid,
        "blocked_cycles": blocked,
    })

    persisted = False
    if p375_present or p376_present:
        request(
            "POST",
            f"{TARGET_TABLE}?on_conflict=portfolio_id,strategy_version,readiness_date",
            [row],
            prefer="resolution=merge-duplicates,return=minimal",
        )
        persisted = True

    payload["persisted"] = persisted
    payload["target_table"] = TARGET_TABLE

    (art / "phase379_result.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    summary = [
        "# GPT Quant V9.2 Paper Trading — Phase 3.7.9",
        "",
        "## Production Paper Qualification State Reconciliation + Automatic Promotion Readiness",
        "",
        f"- State: **{state}**",
        f"- Operational: **{'YES' if operational else 'NO'}**",
        f"- Promotion Ready: **{'YES' if promotion_ready else 'NO'}**",
        f"- Persisted: **{'YES' if persisted else 'NO'}**",
        "",
        "## Reconciled Qualification Evidence",
        "",
        f"- Phase 3.7.5 State: **{p375_state or 'NOT_AVAILABLE'}**",
        f"- Observed Cycles: **{observed}**",
        f"- Valid Cycles: **{valid}**",
        f"- Blocked Cycles: **{blocked}**",
        f"- Runtime Supervision: **{'PASS' if runtime_pass else 'WAITING'}**",
        "",
        "## Promotion Gate",
        "",
        f"- Phase 3.7.6 State: **{p376_state or 'NOT_AVAILABLE'}**",
        f"- Promotion Authorized: **{'YES' if p376_authorized else 'NO'}**",
        "",
        "## Safety Boundary",
        "",
        "- Paper Trading Only: **YES**",
        "- Broker Order Submission: **DISABLED**",
        "- Real-Money Trading: **DISABLED**",
        "- Historical Rewrite Allowed: **NO**",
    ]
    if blockers:
        summary += ["", "## Blockers", ""] + [f"- **{x}**" for x in blockers]

    (art / "phase379_summary.md").write_text("\n".join(summary) + "\n", encoding="utf-8")

    print(f"State: {state}")
    print(f"Promotion Ready: {'YES' if promotion_ready else 'NO'}")
    print(f"Observed Cycles: {observed}")
    print(f"Valid Cycles: {valid}")
    print(f"Blocked Cycles: {blocked}")
    print(f"Persisted: {'YES' if persisted else 'NO'}")
    if blockers:
        print("Blockers: " + ", ".join(blockers))

    return 1 if state == "PROMOTION_READINESS_BLOCKED" else 0

if __name__ == "__main__":
    raise SystemExit(main())
'@
$ymlText = @'
name: GPT Quant Phase 3.7.9 - Production Paper Qualification State Reconciliation Automatic Promotion Readiness

on:
  workflow_dispatch:
  schedule:
    # Weekdays 15:35 UTC / 23:35 Asia-Taipei, after Phase 3.7.8.
    - cron: "35 15 * * 1-5"

permissions:
  contents: read
  actions: read

jobs:
  qualification-state-reconciliation:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      GPT_QUANT_PORTFOLIO_ID: V92_PRODUCTION_PAPER_V91
      GPT_QUANT_STRATEGY_VERSION: V9.1
      PHASE375_RESULT_PATH: artifacts/phase379/input/phase375_result.json
      PHASE376_RESULT_PATH: artifacts/phase379/input/phase376_result.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Compile Phase 3.7.9
        run: python -m py_compile automation/v92/paper_trading_phase379_production_paper_qualification_state_reconciliation_automatic_promotion_readiness.py

      - name: Validate readiness safety contract
        shell: bash
        run: |
          set -euo pipefail
          f="automation/v92/paper_trading_phase379_production_paper_qualification_state_reconciliation_automatic_promotion_readiness.py"
          grep -q 'BROKER_ORDER_SUBMISSION_ENABLED = False' "$f"
          grep -q 'REAL_MONEY_TRADING_ENABLED = False' "$f"
          grep -q 'HISTORICAL_REWRITE_ALLOWED = False' "$f"
          grep -q 'PROMOTION_READINESS_READY' "$f"
          grep -q 'PROMOTION_READINESS_WAITING' "$f"
          grep -q 'PROMOTION_READINESS_BLOCKED' "$f"
          echo "Phase 3.7.9 readiness safety contract: PASS"

      - name: Resolve latest Phase 3.7.5 qualification evidence
        id: resolve375
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          mkdir -p artifacts/phase379/input /tmp/phase375
          workflow="gpt-quant-v92-paper-trading-phase375-production-paper-multi-cycle-stability-evidence-qualification.yml"

          run_id="$(gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow}/runs?branch=main&status=success&per_page=20" \
            --jq '.workflow_runs[0].id // empty' || true)"

          if [ -z "$run_id" ]; then
            echo "No successful Phase 3.7.5 run found."
            exit 0
          fi

          echo "PHASE375_RUN_ID=$run_id" >> "$GITHUB_ENV"

          artifact_id="$(gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/actions/runs/${run_id}/artifacts" \
            --jq '.artifacts[] | select(.expired==false) | .id' \
            | head -n 1 || true)"

          if [ -z "$artifact_id" ]; then
            echo "No Phase 3.7.5 artifact found."
            exit 0
          fi

          gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/actions/artifacts/${artifact_id}/zip" \
            > /tmp/phase375/evidence.zip

          unzip -o /tmp/phase375/evidence.zip -d /tmp/phase375/unpacked >/dev/null
          result="$(find /tmp/phase375/unpacked -type f -name 'phase375_result.json' | head -n 1 || true)"
          if [ -n "$result" ]; then
            cp "$result" artifacts/phase379/input/phase375_result.json
          fi

      - name: Resolve latest Phase 3.7.6 promotion evidence
        id: resolve376
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          mkdir -p artifacts/phase379/input /tmp/phase376
          workflow="gpt-quant-v92-paper-trading-phase376-production-paper-multi-cycle-qualification-promotion-gate.yml"

          run_id="$(gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow}/runs?branch=main&status=success&per_page=20" \
            --jq '.workflow_runs[0].id // empty' || true)"

          if [ -z "$run_id" ]; then
            echo "No successful Phase 3.7.6 run found."
            exit 0
          fi

          echo "PHASE376_RUN_ID=$run_id" >> "$GITHUB_ENV"

          artifact_id="$(gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/actions/runs/${run_id}/artifacts" \
            --jq '.artifacts[] | select(.expired==false) | .id' \
            | head -n 1 || true)"

          if [ -z "$artifact_id" ]; then
            echo "No Phase 3.7.6 artifact found."
            exit 0
          fi

          gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/actions/artifacts/${artifact_id}/zip" \
            > /tmp/phase376/evidence.zip

          unzip -o /tmp/phase376/evidence.zip -d /tmp/phase376/unpacked >/dev/null
          result="$(find /tmp/phase376/unpacked -type f -name 'phase376_result.json' | head -n 1 || true)"
          if [ -n "$result" ]; then
            cp "$result" artifacts/phase379/input/phase376_result.json
          fi

      - name: Execute Phase 3.7.9
        id: phase379
        continue-on-error: true
        run: python automation/v92/paper_trading_phase379_production_paper_qualification_state_reconciliation_automatic_promotion_readiness.py

      - name: Publish summary
        if: always()
        shell: bash
        run: |
          if [ -f artifacts/phase379/phase379_summary.md ]; then
            cat artifacts/phase379/phase379_summary.md >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Upload readiness evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phase379-production-paper-promotion-readiness
          path: artifacts/phase379
          if-no-files-found: warn
          retention-days: 90

      - name: Enforce readiness safety result
        if: always()
        shell: bash
        run: |
          if [ "${{ steps.phase379.outcome }}" != "success" ]; then
            echo "Phase 3.7.9 promotion readiness is BLOCKED."
            exit 1
          fi
          echo "Phase 3.7.9 promotion readiness is healthy."
'@

$utf8 = New-Object System.Text.UTF8Encoding($false)
foreach ($p in @($sqlPath,$pyPath,$ymlPath)) {
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $p) | Out-Null
}

[System.IO.File]::WriteAllText($sqlPath, $sqlText + [Environment]::NewLine, $utf8)
[System.IO.File]::WriteAllText($pyPath, $pyText + [Environment]::NewLine, $utf8)
[System.IO.File]::WriteAllText($ymlPath, $ymlText + [Environment]::NewLine, $utf8)

python -m py_compile $pyPath
if ($LASTEXITCODE -ne 0) {
    throw "Python compile failed."
}

$combined = (Get-Content -LiteralPath $sqlPath -Raw) + "`n" +
            (Get-Content -LiteralPath $pyPath -Raw) + "`n" +
            (Get-Content -LiteralPath $ymlPath -Raw)

$required = @(
  'paper_production_promotion_readiness_v92',
  'PROMOTION_READINESS_READY',
  'PROMOTION_READINESS_WAITING',
  'PROMOTION_READINESS_BLOCKED',
  'BROKER_ORDER_SUBMISSION_ENABLED = False',
  'REAL_MONEY_TRADING_ENABLED = False',
  'HISTORICAL_REWRITE_ALLOWED = False',
  'phase375_result.json',
  'phase376_result.json'
)

foreach ($token in $required) {
    if ($combined -notmatch [regex]::Escape($token)) {
        throw "Verification failed: missing $token"
    }
}

Write-Host ""
Write-Host "Python compile: PASS" -ForegroundColor Green
Write-Host "Qualification reconciliation contract: PASS" -ForegroundColor Green
Write-Host "Automatic promotion readiness contract: PASS" -ForegroundColor Green
Write-Host "Phase 3.7.5 evidence bridge: PASS" -ForegroundColor Green
Write-Host "Phase 3.7.6 promotion gate bridge: PASS" -ForegroundColor Green
Write-Host "Paper-only safety boundary: PASS" -ForegroundColor Green
Write-Host "Historical rewrite prohibition: PASS" -ForegroundColor Green
Write-Host ""
Write-Host "PHASE379 DEPLOYMENT COMPLETE" -ForegroundColor Cyan
Write-Host ""
Write-Host "Generated:"
Write-Host "  $sqlPath"
Write-Host "  $pyPath"
Write-Host "  $ymlPath"
Write-Host ""
Write-Host "IMPORTANT: Run the generated SQL once in Supabase SQL Editor before GitHub Action."
Write-Host ""
Write-Host "Automatic schedule:"
Write-Host "  Weekdays 15:35 UTC / 23:35 Asia-Taipei"
Write-Host ""
Write-Host "Expected current healthy state:"
Write-Host "  PROMOTION_READINESS_WAITING"
Write-Host "  Promotion Ready: NO"
Write-Host ""
Write-Host "Ready state requires:"
Write-Host "  Phase 3.7.5 = MULTI_CYCLE_STABILITY_QUALIFIED"
Write-Host "  Observed >= 3"
Write-Host "  Valid >= 3"
Write-Host "  Blocked = 0"
Write-Host "  Phase 3.7.6 = PRODUCTION_PAPER_PROMOTION_AUTHORIZED"
Write-Host ""
Write-Host "Backup: $backup"
Write-Host ""
Write-Host "NEXT:"
Write-Host '1. Run supabase/PHASE379_PRODUCTION_PAPER_QUALIFICATION_STATE_RECONCILIATION_AUTOMATIC_PROMOTION_READINESS.sql once in Supabase.'
Write-Host '2. git add "supabase/PHASE379_PRODUCTION_PAPER_QUALIFICATION_STATE_RECONCILIATION_AUTOMATIC_PROMOTION_READINESS.sql"'
Write-Host '3. git add "automation/v92/paper_trading_phase379_production_paper_qualification_state_reconciliation_automatic_promotion_readiness.py"'
Write-Host '4. git add ".github/workflows/gpt-quant-v92-paper-trading-phase379-production-paper-qualification-state-reconciliation-automatic-promotion-readiness.yml"'
Write-Host '5. git diff --cached --name-only'
Write-Host '6. git commit -m "Deploy Phase 379 production paper qualification state reconciliation automatic promotion readiness"'
Write-Host '7. git push origin main'
Write-Host '8. Run a NEW Phase 3.7.9 workflow on main.'
