$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

Write-Host "PHASE377 - Production Paper Qualification Evidence Persistence + Cross-Run Accumulation" -ForegroundColor Cyan
Write-Host "Safety boundary: PAPER ONLY / broker submission DISABLED / real money DISABLED" -ForegroundColor Green

$repo = (Get-Location).Path
$sqlRel = "supabase/PHASE377_PRODUCTION_PAPER_QUALIFICATION_EVIDENCE_PERSISTENCE.sql"
$pyRel = "automation/v92/paper_trading_phase377_production_paper_qualification_evidence_persistence_cross_run_accumulation.py"
$ymlRel = ".github/workflows/gpt-quant-v92-paper-trading-phase377-production-paper-qualification-evidence-persistence-cross-run-accumulation.yml"

$sqlPath = Join-Path $repo $sqlRel
$pyPath = Join-Path $repo $pyRel
$ymlPath = Join-Path $repo $ymlRel

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backup = Join-Path $repo ".phase377-backup-$stamp"
New-Item -ItemType Directory -Force -Path $backup | Out-Null
foreach ($p in @($sqlPath,$pyPath,$ymlPath)) {
    if (Test-Path $p) { Copy-Item $p (Join-Path $backup (Split-Path $p -Leaf)) -Force }
}

$sqlText = @'
-- GPT Quant V9.2
-- Phase 3.7.7 — Production Paper Qualification Evidence Persistence + Cross-Run Accumulation
-- Append-safe / idempotent evidence ledger for Production Paper qualification.

create table if not exists public.paper_production_qualification_evidence_v92 (
    id bigint generated by default as identity primary key,
    portfolio_id text not null,
    strategy_version text not null,
    cycle_date date not null,
    cycle_state text not null,
    valid_cycle boolean not null default false,
    blocked_cycle boolean not null default false,
    runtime_supervision_pass boolean not null default false,
    paper_only_boundary_pass boolean not null default false,
    trade_activity_observed boolean not null default false,
    source_workflow text not null,
    source_run_id text not null,
    source_run_attempt integer not null default 1,
    source_commit_sha text,
    evidence_hash text not null,
    raw_evidence jsonb not null default '{}'::jsonb,
    observed_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists uq_paper_production_qualification_evidence_v92_cycle
on public.paper_production_qualification_evidence_v92
(portfolio_id, strategy_version, cycle_date);

create unique index if not exists uq_paper_production_qualification_evidence_v92_hash
on public.paper_production_qualification_evidence_v92
(evidence_hash);

create index if not exists ix_paper_production_qualification_evidence_v92_portfolio_date
on public.paper_production_qualification_evidence_v92
(portfolio_id, strategy_version, cycle_date desc);

create or replace function public.touch_paper_production_qualification_evidence_v92()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_touch_paper_production_qualification_evidence_v92
on public.paper_production_qualification_evidence_v92;

create trigger trg_touch_paper_production_qualification_evidence_v92
before update on public.paper_production_qualification_evidence_v92
for each row execute function public.touch_paper_production_qualification_evidence_v92();

alter table public.paper_production_qualification_evidence_v92 enable row level security;

revoke all on table public.paper_production_qualification_evidence_v92 from anon, authenticated;
grant select, insert, update on table public.paper_production_qualification_evidence_v92 to service_role;

comment on table public.paper_production_qualification_evidence_v92 is
'GPT Quant Phase 3.7.7 canonical Production Paper qualification evidence ledger. One logical cycle per portfolio/strategy/date. Paper-only. No broker or real-money execution.';

notify pgrst, 'reload schema';

select
  'PHASE377_READY' as phase377_state,
  to_regclass('public.paper_production_qualification_evidence_v92') as canonical_table;
'@
$pyText = @'
#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
import os
import urllib.error
import urllib.parse
import urllib.request
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

CONTRACT = "PHASE377_PRODUCTION_PAPER_QUALIFICATION_EVIDENCE_PERSISTENCE_CROSS_RUN_ACCUMULATION"
PORTFOLIO_ID = os.getenv("GPT_QUANT_PORTFOLIO_ID", "V92_PRODUCTION_PAPER_V91")
STRATEGY_VERSION = os.getenv("GPT_QUANT_STRATEGY_VERSION", "V9.1")
TARGET_TABLE = "paper_production_qualification_evidence_v92"

PHASE374_RESULT_PATH = Path(
    os.getenv("PHASE374_RESULT_PATH", "artifacts/phase377/input/phase374_result.json")
)

PAPER_ONLY = True
BROKER_API_USED = False
BROKER_CREDENTIALS_USED = False
BROKER_ORDER_SUBMISSION_ENABLED = False
REAL_MONEY_TRADING_ENABLED = False
HISTORICAL_REWRITE_ALLOWED = False

VALID_STATES = {
    "DAILY_CYCLE_OPERATIONAL_PASS",
    "DAILY_CYCLE_NO_TRADE_VALID",
}
BLOCK_STATES = {
    "DAILY_CYCLE_BLOCKED",
    "BLOCKED",
    "FAIL_CLOSED",
    "FAILED",
    "ERROR",
}

def env_first(*names: str) -> Optional[str]:
    for n in names:
        v = os.getenv(n)
        if v and v.strip():
            return v.strip().rstrip("/")
    return None

SUPABASE_URL = env_first("SUPABASE_URL", "VITE_SUPABASE_URL")
SUPABASE_KEY = env_first(
    "SUPABASE_SERVICE_ROLE_KEY",
    "SUPABASE_SERVICE_KEY",
)

class RestError(RuntimeError):
    pass

def request(method: str, path: str, body: Optional[Any] = None, prefer: str = "") -> Any:
    if not SUPABASE_URL or not SUPABASE_KEY:
        raise RuntimeError("SUPABASE_CONFIGURATION_MISSING")

    data = None if body is None else json.dumps(body).encode("utf-8")
    headers = {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Accept": "application/json",
        "Content-Type": "application/json",
    }
    if prefer:
        headers["Prefer"] = prefer

    req = urllib.request.Request(
        f"{SUPABASE_URL}/rest/v1/{path}",
        data=data,
        headers=headers,
        method=method,
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            raw = r.read().decode("utf-8")
            return json.loads(raw) if raw else None
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", errors="replace")
        raise RestError(f"HTTP {e.code}: {detail}") from e

def load_phase374() -> Dict[str, Any]:
    if not PHASE374_RESULT_PATH.exists():
        return {}
    try:
        obj = json.loads(PHASE374_RESULT_PATH.read_text(encoding="utf-8"))
        return obj if isinstance(obj, dict) else {}
    except Exception:
        return {}

def first_present(d: Dict[str, Any], *keys: str) -> Any:
    for k in keys:
        if k in d and d[k] is not None:
            return d[k]
    return None

def boolish(v: Any) -> bool:
    if isinstance(v, bool):
        return v
    return str(v).strip().upper() in {"TRUE", "T", "1", "YES", "Y", "PASS", "ENABLED"}

def resolve_cycle_date(src: Dict[str, Any]) -> str:
    candidates = [
        first_present(src, "run_date", "validation_date", "cycle_date", "trade_date", "date"),
        os.getenv("GITHUB_RUN_STARTED_AT"),
    ]
    for v in candidates:
        if not v:
            continue
        s = str(v).strip()
        try:
            return datetime.fromisoformat(s.replace("Z", "+00:00")).date().isoformat()
        except Exception:
            try:
                return date.fromisoformat(s[:10]).isoformat()
            except Exception:
                pass
    return datetime.now(timezone.utc).date().isoformat()

def extract_state(src: Dict[str, Any]) -> str:
    for k in ("daily_validation_state", "validation_state", "state", "status", "result"):
        v = src.get(k)
        if v:
            return str(v).strip().upper()
    return "UNKNOWN"

def evidence_digest(payload: Dict[str, Any]) -> str:
    stable = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(stable.encode("utf-8")).hexdigest()

def get_counts() -> Dict[str, int]:
    q = urllib.parse.urlencode({
        "select": "cycle_state,valid_cycle,blocked_cycle,cycle_date",
        "portfolio_id": f"eq.{PORTFOLIO_ID}",
        "strategy_version": f"eq.{STRATEGY_VERSION}",
        "order": "cycle_date.asc",
        "limit": "1000",
    })
    rows = request("GET", f"{TARGET_TABLE}?{q}") or []
    return {
        "observed": len(rows),
        "valid": sum(1 for r in rows if boolish(r.get("valid_cycle"))),
        "blocked": sum(1 for r in rows if boolish(r.get("blocked_cycle"))),
    }

def main() -> int:
    art = Path("artifacts/phase377")
    art.mkdir(parents=True, exist_ok=True)

    src = load_phase374()
    blockers: List[str] = []

    if not src:
        state = "EVIDENCE_PERSISTENCE_WAITING_FOR_PHASE374"
        operational = True
        persisted = False
        counts = {"observed": 0, "valid": 0, "blocked": 0}
    else:
        cycle_state = extract_state(src)
        cycle_date = resolve_cycle_date(src)

        checks = src.get("checks", {}) if isinstance(src.get("checks"), dict) else {}
        safety = src.get("safety", {}) if isinstance(src.get("safety"), dict) else {}

        runtime_pass = str(checks.get("runtime_supervision", "")).upper() == "PASS"
        paper_only_pass = (
            str(checks.get("paper_only_boundary", "")).upper() == "PASS"
            or safety.get("paper_only") is True
        )
        trade_activity = boolish(
            first_present(src, "trade_activity_observed", "trade_activity", "trade_observed")
        )

        valid_cycle = cycle_state in VALID_STATES
        blocked_cycle = cycle_state in BLOCK_STATES

        if blocked_cycle:
            blockers.append(f"UPSTREAM_PHASE374_BLOCKED:{cycle_state}")
        if valid_cycle and not runtime_pass:
            blockers.append("RUNTIME_SUPERVISION_NOT_PASS")
        if valid_cycle and not paper_only_pass:
            blockers.append("PAPER_ONLY_BOUNDARY_NOT_PASS")

        canonical = {
            "portfolio_id": PORTFOLIO_ID,
            "strategy_version": STRATEGY_VERSION,
            "cycle_date": cycle_date,
            "cycle_state": cycle_state,
            "valid_cycle": valid_cycle,
            "blocked_cycle": blocked_cycle,
            "runtime_supervision_pass": runtime_pass,
            "paper_only_boundary_pass": paper_only_pass,
            "trade_activity_observed": trade_activity,
            "source_workflow": os.getenv("GITHUB_WORKFLOW", "manual"),
            "source_run_id": os.getenv("GITHUB_RUN_ID", "local"),
            "source_run_attempt": int(os.getenv("GITHUB_RUN_ATTEMPT", "1")),
            "source_commit_sha": os.getenv("GITHUB_SHA"),
            "raw_evidence": src,
        }
        canonical["evidence_hash"] = evidence_digest({
            "portfolio_id": PORTFOLIO_ID,
            "strategy_version": STRATEGY_VERSION,
            "cycle_date": cycle_date,
            "cycle_state": cycle_state,
            "valid_cycle": valid_cycle,
            "blocked_cycle": blocked_cycle,
            "runtime_supervision_pass": runtime_pass,
            "paper_only_boundary_pass": paper_only_pass,
        })

        if blockers:
            state = "EVIDENCE_PERSISTENCE_BLOCKED"
            operational = False
            persisted = False
            counts = {"observed": 0, "valid": 0, "blocked": 0}
        else:
            # Idempotent per portfolio/strategy/cycle_date.
            path = (
                f"{TARGET_TABLE}"
                "?on_conflict=portfolio_id,strategy_version,cycle_date"
            )
            request(
                "POST",
                path,
                [canonical],
                prefer="resolution=merge-duplicates,return=minimal",
            )
            persisted = True
            counts = get_counts()
            state = "EVIDENCE_PERSISTENCE_OPERATIONAL"
            operational = True

    result = {
        "contract": CONTRACT,
        "portfolio_id": PORTFOLIO_ID,
        "strategy_version": STRATEGY_VERSION,
        "evaluated_at": datetime.now(timezone.utc).isoformat(),
        "state": state,
        "operational": operational,
        "persisted": persisted,
        "blockers": blockers,
        "cross_run_counts": counts,
        "target_table": TARGET_TABLE,
        "safety": {
            "paper_only": PAPER_ONLY,
            "broker_api_used": BROKER_API_USED,
            "broker_credentials_used": BROKER_CREDENTIALS_USED,
            "broker_order_submission_enabled": BROKER_ORDER_SUBMISSION_ENABLED,
            "real_money_trading_enabled": REAL_MONEY_TRADING_ENABLED,
            "historical_rewrite_allowed": HISTORICAL_REWRITE_ALLOWED,
        },
    }

    (art / "phase377_result.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    summary = [
        "# GPT Quant V9.2 Paper Trading — Phase 3.7.7",
        "",
        "## Production Paper Qualification Evidence Persistence + Cross-Run Accumulation",
        "",
        f"- State: **{state}**",
        f"- Operational: **{'YES' if operational else 'NO'}**",
        f"- Persisted Current Cycle: **{'YES' if persisted else 'NO'}**",
        f"- Canonical Table: `{TARGET_TABLE}`",
        "",
        "## Cross-Run Evidence",
        "",
        f"- Observed Cycles: **{counts['observed']}**",
        f"- Valid Cycles: **{counts['valid']}**",
        f"- Blocked Cycles: **{counts['blocked']}**",
        "",
        "## Safety Boundary",
        "",
        "- Paper Trading Only: **YES**",
        "- Broker Order Submission: **DISABLED**",
        "- Real-Money Trading: **DISABLED**",
        "- Historical Rewrite Allowed: **NO**",
    ]
    if blockers:
        summary += ["", "## Blockers", ""] + [f"- **{b}**" for b in blockers]

    (art / "phase377_summary.md").write_text("\n".join(summary) + "\n", encoding="utf-8")

    print(f"State: {state}")
    print(f"Operational: {'YES' if operational else 'NO'}")
    print(f"Persisted: {'YES' if persisted else 'NO'}")
    print(f"Observed Cycles: {counts['observed']}")
    print(f"Valid Cycles: {counts['valid']}")
    print(f"Blocked Cycles: {counts['blocked']}")
    if blockers:
        print("Blockers: " + ", ".join(blockers))

    return 1 if state == "EVIDENCE_PERSISTENCE_BLOCKED" else 0

if __name__ == "__main__":
    raise SystemExit(main())
'@
$ymlText = @'
name: GPT Quant Phase 3.7.7 - Production Paper Qualification Evidence Persistence Cross-Run Accumulation

on:
  workflow_dispatch:
  schedule:
    # Taiwan 22:42 = UTC 14:42, after Phase 3.7.4 daily monitoring and before Phase 3.7.5.
    - cron: "42 14 * * 1-5"

permissions:
  contents: read
  actions: read

jobs:
  evidence-persistence:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      GPT_QUANT_PORTFOLIO_ID: V92_PRODUCTION_PAPER_V91
      GPT_QUANT_STRATEGY_VERSION: V9.1
      PHASE374_RESULT_PATH: artifacts/phase377/input/phase374_result.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Compile Phase 3.7.7
        run: python -m py_compile automation/v92/paper_trading_phase377_production_paper_qualification_evidence_persistence_cross_run_accumulation.py

      - name: Validate evidence persistence safety contract
        shell: bash
        run: |
          set -euo pipefail
          f="automation/v92/paper_trading_phase377_production_paper_qualification_evidence_persistence_cross_run_accumulation.py"
          grep -q 'BROKER_ORDER_SUBMISSION_ENABLED = False' "$f"
          grep -q 'REAL_MONEY_TRADING_ENABLED = False' "$f"
          grep -q 'HISTORICAL_REWRITE_ALLOWED = False' "$f"
          grep -q 'EVIDENCE_PERSISTENCE_OPERATIONAL' "$f"
          grep -q 'EVIDENCE_PERSISTENCE_BLOCKED' "$f"
          echo "Phase 3.7.7 safety contract: PASS"

      - name: Resolve latest Phase 3.7.4 evidence
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          mkdir -p artifacts/phase377/input /tmp/phase374
          workflow="gpt-quant-v92-paper-trading-phase374-production-paper-daily-cycle-monitoring-evidence-accumulation.yml"

          run_id="$(gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow}/runs?branch=main&status=success&per_page=20" \
            --jq '.workflow_runs[0].id // empty' || true)"

          if [ -z "$run_id" ]; then
            echo "No successful Phase 3.7.4 run found; persistence will remain WAITING."
            exit 0
          fi

          artifact_id="$(gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/actions/runs/${run_id}/artifacts" \
            --jq '.artifacts[] | select(.name=="phase374-production-paper-daily-cycle-monitoring-evidence") | .id' \
            | head -n 1 || true)"

          if [ -z "$artifact_id" ]; then
            echo "No Phase 3.7.4 evidence artifact found; persistence will remain WAITING."
            exit 0
          fi

          gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/actions/artifacts/${artifact_id}/zip" \
            > /tmp/phase374/evidence.zip

          unzip -o /tmp/phase374/evidence.zip -d /tmp/phase374/unpacked >/dev/null

          result="$(find /tmp/phase374/unpacked -type f -name 'phase374_result.json' | head -n 1 || true)"
          if [ -n "$result" ]; then
            cp "$result" artifacts/phase377/input/phase374_result.json
            echo "Resolved Phase 3.7.4 evidence from run ${run_id}."
          else
            echo "phase374_result.json not found; persistence will remain WAITING."
          fi

      - name: Execute Phase 3.7.7
        id: phase377
        continue-on-error: true
        run: python automation/v92/paper_trading_phase377_production_paper_qualification_evidence_persistence_cross_run_accumulation.py

      - name: Publish summary
        if: always()
        shell: bash
        run: |
          if [ -f artifacts/phase377/phase377_summary.md ]; then
            cat artifacts/phase377/phase377_summary.md >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Upload persistence evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phase377-production-paper-qualification-evidence-persistence
          path: artifacts/phase377
          if-no-files-found: warn
          retention-days: 120

      - name: Enforce persistence safety result
        if: always()
        shell: bash
        run: |
          if [ "${{ steps.phase377.outcome }}" != "success" ]; then
            echo "Phase 3.7.7 evidence persistence is BLOCKED."
            exit 1
          fi
          echo "Phase 3.7.7 evidence persistence is healthy."
'@

$utf8 = New-Object System.Text.UTF8Encoding($false)
foreach ($p in @($sqlPath,$pyPath,$ymlPath)) {
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $p) | Out-Null
}
[System.IO.File]::WriteAllText($sqlPath, $sqlText + [Environment]::NewLine, $utf8)
[System.IO.File]::WriteAllText($pyPath, $pyText + [Environment]::NewLine, $utf8)
[System.IO.File]::WriteAllText($ymlPath, $ymlText + [Environment]::NewLine, $utf8)

python -m py_compile $pyPath
if ($LASTEXITCODE -ne 0) { throw "Python compile failed." }

$combined = (Get-Content -LiteralPath $sqlPath -Raw) + "`n" +
            (Get-Content -LiteralPath $pyPath -Raw) + "`n" +
            (Get-Content -LiteralPath $ymlPath -Raw)

$required = @(
  'paper_production_qualification_evidence_v92',
  'uq_paper_production_qualification_evidence_v92_cycle',
  'resolution=merge-duplicates',
  'EVIDENCE_PERSISTENCE_OPERATIONAL',
  'EVIDENCE_PERSISTENCE_BLOCKED',
  'BROKER_ORDER_SUBMISSION_ENABLED = False',
  'REAL_MONEY_TRADING_ENABLED = False',
  'HISTORICAL_REWRITE_ALLOWED = False',
  'phase374-production-paper-daily-cycle-monitoring-evidence'
)
foreach ($token in $required) {
    if ($combined -notmatch [regex]::Escape($token)) {
        throw "Verification failed: missing $token"
    }
}

Write-Host ""
Write-Host "Python compile: PASS" -ForegroundColor Green
Write-Host "Canonical evidence table contract: PASS" -ForegroundColor Green
Write-Host "Cross-run persistence contract: PASS" -ForegroundColor Green
Write-Host "Idempotent cycle-date deduplication: PASS" -ForegroundColor Green
Write-Host "Phase 3.7.4 evidence handoff contract: PASS" -ForegroundColor Green
Write-Host "Paper-only safety boundary: PASS" -ForegroundColor Green
Write-Host "Historical rewrite prohibition: PASS" -ForegroundColor Green
Write-Host ""
Write-Host "PHASE377 DEPLOYMENT COMPLETE" -ForegroundColor Cyan
Write-Host ""
Write-Host "Generated:"
Write-Host "  $sqlPath"
Write-Host "  $pyPath"
Write-Host "  $ymlPath"
Write-Host ""
Write-Host "IMPORTANT: Run the generated SQL once in Supabase SQL Editor before GitHub Action."
Write-Host ""
Write-Host "Automatic schedule:"
Write-Host "  Weekdays 14:42 UTC / 22:42 Asia-Taipei"
Write-Host ""
Write-Host "Expected healthy states:"
Write-Host "  EVIDENCE_PERSISTENCE_WAITING_FOR_PHASE374"
Write-Host "  EVIDENCE_PERSISTENCE_OPERATIONAL"
Write-Host "  EVIDENCE_PERSISTENCE_BLOCKED only on genuine upstream/runtime/safety failure"
Write-Host ""
Write-Host "Backup: $backup"
Write-Host ""
Write-Host "NEXT:"
Write-Host '1. Run supabase/PHASE377_PRODUCTION_PAPER_QUALIFICATION_EVIDENCE_PERSISTENCE.sql once in Supabase.'
Write-Host '2. git add "supabase/PHASE377_PRODUCTION_PAPER_QUALIFICATION_EVIDENCE_PERSISTENCE.sql"'
Write-Host '3. git add "automation/v92/paper_trading_phase377_production_paper_qualification_evidence_persistence_cross_run_accumulation.py"'
Write-Host '4. git add ".github/workflows/gpt-quant-v92-paper-trading-phase377-production-paper-qualification-evidence-persistence-cross-run-accumulation.yml"'
Write-Host '5. git status'
Write-Host '6. git commit -m "Deploy Phase 377 production paper qualification evidence persistence cross-run accumulation"'
Write-Host '7. git push origin main'
Write-Host '8. Run a NEW Phase 3.7.7 workflow on main.'
