#requires -Version 5.1
<#
PHASE37261_V3_RECONSTRUCTION_AUDIT_SCHEMA_RECOVERY_DEPLOY.ps1

GPT Quant V9.2
Phase 3.7.2.6.1 V3 — Reconstruction Audit Schema Recovery

Purpose
-------
Recover the missing canonical audit schema required by Phase 3.7.2.6.1:

  public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92

Observed production failure
---------------------------
Phase 3.7.2.6.1 V2 correctly tried both:
  - paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
  - paper_post_recovery_activation_master_cycle_reconstruction_audit

but PostgREST reported both as missing.

This V3 package:
  1) creates the canonical _v92 audit table;
  2) adds constraints that enforce paper-only / no-broker / no-real-money safety;
  3) reloads PostgREST schema metadata;
  4) adds a verification workflow that confirms the table is visible via REST;
  5) leaves Phase 3.7.2.6.1 reconstruction logic unchanged;
  6) does NOT rewrite historical evidence.

Generated
---------
  supabase/PHASE37261_V3_RECONSTRUCTION_AUDIT_SCHEMA_RECOVERY.sql
  automation/v92/paper_trading_phase37261_v3_reconstruction_audit_schema_recovery_verify.py
  .github/workflows/gpt-quant-v92-paper-trading-phase37261-v3-reconstruction-audit-schema-recovery.yml
#>

param(
    [switch]$AutoGit
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Section([string]$Text) {
    Write-Host ""
    Write-Host ("=" * 118) -ForegroundColor DarkCyan
    Write-Host $Text -ForegroundColor Cyan
    Write-Host ("=" * 118) -ForegroundColor DarkCyan
}

function Fail([string]$Text) {
    Write-Host ""
    Write-Host "DEPLOY FAILED: $Text" -ForegroundColor Red
    exit 1
}

function Write-Utf8NoBom([string]$Path, [string]$Content) {
    $parent = Split-Path -Parent $Path
    if ($parent -and -not (Test-Path $parent)) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    $enc = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $enc)
}

Section "GPT Quant V9.2 — Phase 3.7.2.6.1 V3 Reconstruction Audit Schema Recovery"

$repo = $null
try {
    $repo = (& git rev-parse --show-toplevel 2>$null).Trim()
} catch {
    $repo = $null
}

if ([string]::IsNullOrWhiteSpace($repo)) {
    Fail "Run this package from inside the GPT Git repository."
}

Set-Location $repo
Write-Host "Repository: $repo" -ForegroundColor Green

$required = @(
    "automation/v92/paper_trading_phase37261_post_recovery_activation_master_cycle_canonical_state_reconstruction.py",
    "automation/v92/paper_trading_phase3726_post_safety_recovery_canonical_operational_state_requalification.py"
)

foreach ($item in $required) {
    if (-not (Test-Path $item)) {
        Fail "Required dependency missing: $item"
    }
}

$sqlTarget = Join-Path $repo "supabase\PHASE37261_V3_RECONSTRUCTION_AUDIT_SCHEMA_RECOVERY.sql"
$pyTarget  = Join-Path $repo "automation\v92\paper_trading_phase37261_v3_reconstruction_audit_schema_recovery_verify.py"
$ymlTarget = Join-Path $repo ".github\workflows\gpt-quant-v92-paper-trading-phase37261-v3-reconstruction-audit-schema-recovery.yml"

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backupRoot = Join-Path $repo ".phase37261-v3-backup-$stamp"
New-Item -ItemType Directory -Force -Path $backupRoot | Out-Null

foreach ($target in @($sqlTarget, $pyTarget, $ymlTarget)) {
    if (Test-Path $target) {
        Copy-Item $target (Join-Path $backupRoot ([IO.Path]::GetFileName($target))) -Force
    }
}

Section "Writing canonical audit schema recovery SQL"

$sql = @'
begin;

create table if not exists public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92 (
    id bigint generated by default as identity primary key,

    reconstruction_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE37261_POST_RECOVERY_ACTIVATION_MASTER_CYCLE_CANONICAL_STATE_RECONSTRUCTION',

    activation_table text not null,
    master_cycle_table text not null,

    activation_state text not null,
    master_cycle_state text not null,
    runtime_supervision_state text not null,

    historical_rewrite_allowed boolean not null default false,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    evidence_document jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),

    constraint ck_phase37261_v3_audit_activation_state
        check (activation_state = 'ACTIVE'),

    constraint ck_phase37261_v3_audit_master_cycle_state
        check (master_cycle_state = 'PASS'),

    constraint ck_phase37261_v3_audit_runtime_supervision
        check (runtime_supervision_state = 'CONTINUE_ACTIVE'),

    constraint ck_phase37261_v3_audit_no_history_rewrite
        check (historical_rewrite_allowed = false),

    constraint ck_phase37261_v3_audit_paper_only
        check (paper_only = true),

    constraint ck_phase37261_v3_audit_no_broker_api
        check (broker_api_used = false),

    constraint ck_phase37261_v3_audit_no_broker_credentials
        check (broker_credentials_used = false),

    constraint ck_phase37261_v3_audit_no_broker_submission
        check (broker_order_submission_enabled = false),

    constraint ck_phase37261_v3_audit_no_real_money
        check (real_money_trading_enabled = false),

    constraint ck_phase37261_v3_audit_no_live_release
        check (live_money_release_authorized = false),

    constraint ck_phase37261_v3_audit_fail_closed
        check (fail_closed_policy = true)
);

create index if not exists ix_phase37261_v3_reconstruction_audit_portfolio_created
    on public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    (portfolio_id, created_at desc);

alter table public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    enable row level security;

comment on table public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92 is
'GPT Quant V9.2 Phase 3.7.2.6.1 canonical immutable-style reconstruction audit table. Paper-only and fail-closed.';

notify pgrst, 'reload schema';

commit;
'@

Write-Utf8NoBom $sqlTarget $sql
Write-Host "Wrote: $sqlTarget" -ForegroundColor Green

Section "Writing PostgREST schema visibility verifier"

$py = @'
from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request

TABLE = "paper_post_recovery_activation_master_cycle_reconstruction_audit_v92"
CONTRACT = "PHASE37261_V3_RECONSTRUCTION_AUDIT_SCHEMA_RECOVERY"

def env_first(*names: str) -> str:
    for name in names:
        value = os.getenv(name, "").strip()
        if value:
            return value
    return ""

def main() -> int:
    url = env_first("SUPABASE_URL", "VITE_SUPABASE_URL").rstrip("/")
    key = env_first(
        "SUPABASE_SERVICE_ROLE_KEY",
        "SUPABASE_SERVICE_KEY",
        "SUPABASE_KEY",
        "VITE_SUPABASE_PUBLISHABLE_KEY",
    )

    if not url or not key:
        raise RuntimeError("Missing Supabase URL/key")

    endpoint = (
        f"{url}/rest/v1/{TABLE}"
        "?select=id,reconstruction_date,portfolio_id,activation_state,"
        "master_cycle_state,runtime_supervision_state"
        "&limit=1"
    )

    headers = {
        "apikey": key,
        "Authorization": f"Bearer {key}",
        "Accept": "application/json",
    }

    req = urllib.request.Request(endpoint, headers=headers, method="GET")

    try:
        with urllib.request.urlopen(req, timeout=45) as response:
            body = response.read().decode("utf-8")
            rows = json.loads(body) if body.strip() else []
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(
            f"Canonical audit table is not visible through PostgREST: "
            f"HTTP {exc.code}: {body}"
        ) from exc

    print("# GPT Quant V9.2 Paper Trading - Phase 3.7.2.6.1 V3")
    print()
    print("## Reconstruction Audit Schema Recovery Verification")
    print()
    print(f"- Contract: `{CONTRACT}`")
    print(f"- Canonical Audit Table: `{TABLE}`")
    print("- PostgREST Schema Visibility: **PASS**")
    print(f"- Existing Rows Sampled: **{len(rows)}**")
    print()
    print("## Safety Boundary")
    print()
    print("- Paper only: **ENABLED**")
    print("- Broker API used: **NO**")
    print("- Broker credentials used: **NO**")
    print("- Broker order submission: **DISABLED**")
    print("- Real-money trading: **DISABLED**")
    print("- Live-money release authorized: **NO**")
    print("- Historical evidence rewrite: **DISABLED**")
    print("- Fail-closed policy: **ENABLED**")
    print()
    print("## Next")
    print()
    print("- Re-run **Phase 3.7.2.6.1**.")
    print("- If reconstruction = PASS, then re-run **Phase 3.7.2.6**.")
    return 0

if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"PHASE37261_V3_FATAL: {exc}", file=sys.stderr)
        raise
'@

Write-Utf8NoBom $pyTarget $py
Write-Host "Wrote: $pyTarget" -ForegroundColor Green

Section "Writing GitHub Actions verification workflow"

$yml = @'
name: GPT Quant Phase 3.7.2.6.1 V3 - Reconstruction Audit Schema Recovery Verify

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: phase37261-v3-reconstruction-audit-schema-recovery
  cancel-in-progress: false

jobs:
  reconstruction-audit-schema-recovery:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Compile Phase 3.7.2.6.1 V3 verifier
        shell: bash
        run: |
          python -m py_compile automation/v92/paper_trading_phase37261_v3_reconstruction_audit_schema_recovery_verify.py

      - name: Validate V3 contract
        shell: bash
        run: |
          set -euo pipefail

          test -n "${SUPABASE_URL:-}"
          test -n "${SUPABASE_SERVICE_ROLE_KEY:-}"

          grep -q 'PHASE37261_V3_RECONSTRUCTION_AUDIT_SCHEMA_RECOVERY' \
            automation/v92/paper_trading_phase37261_v3_reconstruction_audit_schema_recovery_verify.py

          grep -q 'paper_post_recovery_activation_master_cycle_reconstruction_audit_v92' \
            automation/v92/paper_trading_phase37261_v3_reconstruction_audit_schema_recovery_verify.py

          echo "Phase 3.7.2.6.1 V3 schema recovery verifier contract: PASS"

      - name: Verify PostgREST schema visibility
        shell: bash
        run: |
          mkdir -p artifacts/phase37261-v3

          python automation/v92/paper_trading_phase37261_v3_reconstruction_audit_schema_recovery_verify.py \
            | tee artifacts/phase37261-v3/summary.md

      - name: Publish summary
        if: always()
        shell: bash
        run: |
          if [ -f artifacts/phase37261-v3/summary.md ]; then
            cat artifacts/phase37261-v3/summary.md >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Upload verification evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phase37261-v3-reconstruction-audit-schema-recovery
          path: artifacts/phase37261-v3/
          if-no-files-found: warn
          retention-days: 120
'@

Write-Utf8NoBom $ymlTarget $yml
Write-Host "Wrote: $ymlTarget" -ForegroundColor Green

Section "Static validation"

$pythonExe = $null
if (Get-Command python -ErrorAction SilentlyContinue) {
    $pythonExe = "python"
} elseif (Get-Command py -ErrorAction SilentlyContinue) {
    $pythonExe = "py"
} else {
    Fail "Python not found in PATH."
}

if ($pythonExe -eq "py") {
    & py -3 -m py_compile $pyTarget
} else {
    & python -m py_compile $pyTarget
}

if ($LASTEXITCODE -ne 0) {
    Fail "Phase 3.7.2.6.1 V3 verifier Python compile failed."
}

$combined = (Get-Content -LiteralPath $sqlTarget -Raw) + "`n" +
            (Get-Content -LiteralPath $pyTarget -Raw) + "`n" +
            (Get-Content -LiteralPath $ymlTarget -Raw)

foreach ($token in @(
    "PHASE37261_V3_RECONSTRUCTION_AUDIT_SCHEMA_RECOVERY",
    "paper_post_recovery_activation_master_cycle_reconstruction_audit_v92",
    "PostgREST Schema Visibility",
    "broker_order_submission_enabled boolean not null default false",
    "real_money_trading_enabled boolean not null default false",
    "historical_rewrite_allowed boolean not null default false"
)) {
    if (-not $combined.Contains($token)) {
        Fail "Required V3 token missing: $token"
    }
}

if ((Get-Item $sqlTarget).Length -lt 2500) {
    Fail "V3 SQL unexpectedly small or empty."
}

Write-Host "Python compile: PASS" -ForegroundColor Green
Write-Host "Canonical audit schema definition scan: PASS" -ForegroundColor Green
Write-Host "PostgREST verification workflow scan: PASS" -ForegroundColor Green
Write-Host "Paper-only safety constraints scan: PASS" -ForegroundColor Green
Write-Host "Historical preservation scan: PASS" -ForegroundColor Green

Section "Git status"
& git status --short

if ($AutoGit) {
    Section "Optional AutoGit"

    $branch = (& git rev-parse --abbrev-ref HEAD).Trim()
    if ($branch -ne "main") {
        Fail "AutoGit requires current branch main; current=$branch"
    }

    & git add -- $sqlTarget $pyTarget $ymlTarget
    if ($LASTEXITCODE -ne 0) {
        Fail "git add failed"
    }

    $pending = (& git diff --cached --name-only)
    if (-not [string]::IsNullOrWhiteSpace(($pending -join "`n"))) {
        & git commit -m "Deploy Phase 3.7.2.6.1 V3 reconstruction audit schema recovery"
        if ($LASTEXITCODE -ne 0) {
            Fail "git commit failed"
        }

        & git push origin main
        if ($LASTEXITCODE -ne 0) {
            Fail "git push origin main failed"
        }

        Write-Host "AutoGit commit + push: PASS" -ForegroundColor Green
    }
}

Section "DEPLOY COMPLETE"

Write-Host "Generated:" -ForegroundColor Green
Write-Host "  supabase/PHASE37261_V3_RECONSTRUCTION_AUDIT_SCHEMA_RECOVERY.sql"
Write-Host "  automation/v92/paper_trading_phase37261_v3_reconstruction_audit_schema_recovery_verify.py"
Write-Host "  .github/workflows/gpt-quant-v92-paper-trading-phase37261-v3-reconstruction-audit-schema-recovery.yml"
Write-Host ""
Write-Host "Important:" -ForegroundColor Yellow
Write-Host "  This package DOES require the SQL file to be run once in Supabase."
Write-Host "  It does NOT modify historical safety evidence."
Write-Host "  It does NOT enable broker or real-money trading."
Write-Host ""
Write-Host "Next:" -ForegroundColor Yellow
Write-Host "  1) Run supabase/PHASE37261_V3_RECONSTRUCTION_AUDIT_SCHEMA_RECOVERY.sql in Supabase SQL Editor."
Write-Host "  2) Commit and Push generated files."
Write-Host "  3) Run GitHub Action:"
Write-Host "     GPT Quant Phase 3.7.2.6.1 V3 - Reconstruction Audit Schema Recovery Verify"
Write-Host "  4) Confirm PostgREST Schema Visibility = PASS."
Write-Host "  5) Re-run Phase 3.7.2.6.1."
Write-Host "  6) If reconstruction PASS, re-run Phase 3.7.2.6."
Write-Host ""
Write-Host "Backup: $backupRoot" -ForegroundColor DarkGray
