begin;

create table if not exists public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92 (
    id bigint generated by default as identity primary key,

    reconstruction_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE37261_POST_RECOVERY_ACTIVATION_MASTER_CYCLE_CANONICAL_STATE_RECONSTRUCTION',

    activation_table text not null,
    master_cycle_table text not null,

    activation_state text not null,
    master_cycle_state text not null,
    runtime_supervision_state text not null,

    historical_rewrite_allowed boolean not null default false,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    evidence_document jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now()
);

-- Repair missing columns safely in case an earlier partial table exists.
alter table public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    add column if not exists reconstruction_date date,
    add column if not exists portfolio_id text,
    add column if not exists strategy_version text default 'V9.1',
    add column if not exists contract text default 'PHASE37261_POST_RECOVERY_ACTIVATION_MASTER_CYCLE_CANONICAL_STATE_RECONSTRUCTION',
    add column if not exists activation_table text,
    add column if not exists master_cycle_table text,
    add column if not exists activation_state text,
    add column if not exists master_cycle_state text,
    add column if not exists runtime_supervision_state text,
    add column if not exists historical_rewrite_allowed boolean default false,
    add column if not exists paper_only boolean default true,
    add column if not exists broker_api_used boolean default false,
    add column if not exists broker_credentials_used boolean default false,
    add column if not exists broker_order_submission_enabled boolean default false,
    add column if not exists real_money_trading_enabled boolean default false,
    add column if not exists live_money_release_authorized boolean default false,
    add column if not exists fail_closed_policy boolean default true,
    add column if not exists evidence_sha256 text,
    add column if not exists evidence_document jsonb default '{}'::jsonb,
    add column if not exists created_at timestamptz default now();

create index if not exists ix_phase37261_v6_reconstruction_audit_portfolio_created
    on public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    (portfolio_id, created_at desc);

alter table public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    enable row level security;

-- Explicit API visibility/grants. Service-role writes remain the intended runtime path.
grant usage on schema public to anon, authenticated, service_role;
grant select on public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    to anon, authenticated, service_role;
grant insert on public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92
    to service_role;
grant usage, select on sequence public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92_id_seq
    to service_role;

comment on table public.paper_post_recovery_activation_master_cycle_reconstruction_audit_v92 is
'GPT Quant V9.2 Phase 3.7.2.6.1 canonical reconstruction audit table. Paper-only, append-only runtime usage.';

-- Ask PostgREST to refresh its schema cache.
notify pgrst, 'reload schema';

commit;