export const escapeHtml=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const number=v=>v===null||v===undefined?'—':Number(v).toLocaleString('en-US',{maximumFractionDigits:2});
export const percent=v=>v===null||v===undefined?'—':`${(Number(v)*100).toFixed(2)}%`;
export function validateReport(r){
 if(r.contract!=='V10_FORWARD_DASHBOARD_V1'||r.source!=='V10_FORWARD_STORE'||r.mode!=='FORWARD_SHADOW'||r.paper_only!==true||r.forward_validation_start_date!=='2026-10-05')throw Error('Invalid V10 forward report contract');
 if(r.strategies.length!==18||new Set(r.strategies.map(s=>s.strategy_id)).size!==18)throw Error('Incomplete shadow registry');
 if(r.safety.PAPER_ONLY!==true||r.safety.BROKER_ORDER_SUBMISSION_ENABLED!==false||r.safety.REAL_MONEY_TRADING_ENABLED!==false||r.safety.PRODUCTION_EXECUTION_AVAILABLE!==false)throw Error('Invalid paper safety contract');
 const dates=r.strategies[0].curve.map(p=>p.date);
 if(!dates.length||dates[0]!=='2026-10-05'||dates.at(-1)!==r.latest_business_date||dates.length!==r.forward_trading_days||new Set(dates).size!==dates.length||dates.some((d,i)=>d<'2026-10-05'||(i&&d<=dates[i-1])))throw Error('Invalid forward dates');
 for(const s of r.strategies){if(JSON.stringify(s.curve.map(p=>p.date))!==JSON.stringify(dates)||s.forward_days!==r.forward_trading_days||(s.forward_days<20&&s.validation_status!=='COLLECTING')||(s.forward_days<60&&s.validation_status==='QUALIFIED'))throw Error('Invalid evidence gate/alignment');}
 if(new Set(r.fills.map(f=>f.fill_id)).size!==r.fills.length||r.fills.some(f=>f.status!=='FILLED'||f.signal_date<'2026-10-05'||f.execution_date<=f.signal_date||f.fill_price===null))throw Error('Invalid fill evidence');
 if(r.orders.some(o=>o.status==='PENDING_NEXT_TRADABLE_OPEN'&&(o.fill_price!==null||o.execution_date!==null)))throw Error('Pending order disguised as fill');
 return r;
}
export function sortedStrategies(rows,key){if(!['return','excess_return','sharpe','drawdown'].includes(key))throw Error('Invalid sort');return [...rows].sort((a,b)=>(Number(a[key])-Number(b[key]))*(key==='drawdown'?1:-1)||a.strategy_id.localeCompare(b.strategy_id));}
export function tableHtml(rows,columns,strategyRows=false,selected=''){
 if(!rows.length)return '<div class="empty">No records for this strategy.</div>';
 return `<table><thead><tr>${columns.map(c=>`<th>${escapeHtml(c[0])}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr${strategyRows?` data-strategy="${escapeHtml(r.strategy_id)}" class="${r.strategy_id===selected?'selected':''}"`:''}>${columns.map(([,key,format])=>`<td${format?' class="numeric"':''}>${escapeHtml(format?format(key==='position_count'?r.positions.length:r[key]):r[key])}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
}
export function curveHtml(curve){
 const width=1000,height=290,pad=48,values=curve.flatMap(p=>[Number(p.return),Number(p.benchmark_return)]);let lo=Math.min(0,...values),hi=Math.max(0,...values);if(hi-lo<.002){hi+=.001;lo-=.001;}const x=i=>pad+i*(width-2*pad)/Math.max(1,curve.length-1),y=v=>height-pad-(v-lo)*(height-2*pad)/(hi-lo);
 const lines=Array.from({length:5},(_,i)=>{const v=lo+(hi-lo)*i/4;return `<line x1="${pad}" x2="${width-pad}" y1="${y(v)}" y2="${y(v)}" stroke="#2b3c50"/><text x="6" y="${y(v)+4}" fill="#9aacc1" font-size="12">${percent(v)}</text>`;}).join('');
 const paths=['return','benchmark_return'].map((key,k)=>`<polyline fill="none" stroke="${k?'#8ea5ff':'#64dcbb'}" stroke-width="3" points="${curve.map((p,i)=>`${x(i)},${y(Number(p[key]))}`).join(' ')}"/>${curve.map((p,i)=>`<circle cx="${x(i)}" cy="${y(Number(p[key]))}" r="4" fill="${k?'#8ea5ff':'#64dcbb'}"><title>${escapeHtml(p.date)} · ${key}: ${percent(p[key])}</title></circle>`).join('')}`).join('');
 return `<div class="legend"><span>● Selected Strategy</span><span>● TWSE Benchmark</span></div><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Forward equity return curve from 2026-10-05">${lines}${paths}<text x="${pad}" y="${height-12}" fill="#9aacc1" font-size="12">${escapeHtml(curve[0].date)}</text><text x="${width-pad}" text-anchor="end" y="${height-12}" fill="#9aacc1" font-size="12">${escapeHtml(curve.at(-1).date)}</text></svg><p class="muted">Equity normalized to the initial paper capital; both series use identical completed forward dates.</p>`;
}
const orderColumns=[['Signal Date','signal_date'],['Execution Date','execution_date'],['Symbol','symbol'],['Side / Intent','side'],['Shares','shares',number],['Signal Score','signal_score',number],['Reference','reference'],['Fill Price','fill_price',number],['Transaction Cost','transaction_cost',number],['Status','status'],['Strategy ID','strategy_id']];
function boot(r){
 const el=id=>document.getElementById(id), put=(id,html)=>el(id).innerHTML=html;
 const metrics=(id,items)=>put(id,items.map(([label,value,small])=>`<div class="metric"><span>${escapeHtml(label)}</span><strong class="${small?'small':''}">${escapeHtml(value)}</strong></div>`).join(''));
 let selected=r.best_strategy_id;
 metrics('summary',[['Forward Start',r.forward_validation_start_date],['Latest Business Date',r.latest_business_date],['Forward Trading Days',r.forward_trading_days],['Total Symbols Scanned',number(r.total_symbols)],['Eligible Symbols',number(r.eligible_symbols)],['Excluded Symbols',number(r.excluded_symbols)],['Shadow Strategies',r.strategies.length],['Collecting',r.status_counts.COLLECTING??0],['Preliminary',r.status_counts.INSUFFICIENT_EVIDENCE??0],['Qualified',r.status_counts.QUALIFIED??0],['Rejected',r.status_counts.REJECTED??0],['Latest Run Status',r.latest_run_status]]);
 el('validation').textContent=r.forward_trading_days<20?'COLLECTING':r.forward_trading_days<60?'INSUFFICIENT EVIDENCE':'QUALIFICATION EVALUATION';
 put('progress',[['PRELIMINARY GATE',20],['QUALIFICATION GATE',60]].map(([label,total])=>`<div><p>${label} · ${r.forward_trading_days} / ${total} trading days</p><progress max="${total}" value="${Math.min(total,r.forward_trading_days)}"></progress></div>`).join(''));
 const best=r.strategies.find(s=>s.strategy_id===r.best_strategy_id);el('best-name').textContent=best.strategy_id;el('profit-label').textContent=r.profitability_label;
 metrics('best',[['Forward Net Return',percent(best.return)],['Benchmark Return',percent(best.benchmark_return)],['Excess Return',percent(best.excess_return)],['Total PnL',number(best.cumulative_pnl)],['Max Drawdown',percent(best.drawdown)],['Forward Days',best.forward_days]]);
 metrics('scan',[['Total Symbols',number(r.total_symbols)],['Eligible',number(r.eligible_symbols)],['Excluded',number(r.excluded_symbols)],['Data Date',r.data_date],['Data Freshness',r.data_freshness,true]]);
 put('exclusions',`<div class="chips">${Object.entries(r.exclusion_reasons).map(([key,n])=>`<span class="chip">${escapeHtml(key)}: ${number(n)}</span>`).join('')}</div><p class="muted">Exclusion reason counts may overlap.</p>`);el('run-id').textContent=`Run ID: ${r.run_id}`;
 put('candidates',tableHtml(r.top_candidates.map(c=>({...c,factors:Object.entries(c.factor_scores).map(([k,v])=>`${k}: ${Number(v).toFixed(3)}`).join(' · ')})),[['Rank','rank'],['Symbol','symbol'],['Composite Score','composite_score',number],['Factor Scores','factors'],['Strategy','strategy_id'],['Target Weight','target_weight',percent],['Risk Decision','risk_decision'],['Order Intent','order_intent'],['Execution Status','execution_status']]));
 put('strategy',r.strategies.map(s=>`<option value="${escapeHtml(s.strategy_id)}">${escapeHtml(s.strategy_id)}</option>`).join(''));el('strategy').value=selected;
 function scoreboard(){put('scoreboard',tableHtml(sortedStrategies(r.strategies,el('sort').value),[['Strategy ID','strategy_id'],['Hypothesis','hypothesis'],['Top-N','top_n'],['Rebalance','rebalance_frequency'],['Forward Days','forward_days'],['Equity','equity',number],['Net Return','return',percent],['Benchmark','benchmark_return',percent],['Excess Return','excess_return',percent],['Sharpe','sharpe',number],['Daily PnL','daily_pnl',number],['Cumulative PnL','cumulative_pnl',number],['Max Drawdown','drawdown',percent],['Positions','position_count',number],['Turnover','turnover',percent],['Total Costs','transaction_cost_cumulative',number],['Validation','validation_status']],true,selected));}
 function portfolio(){const s=r.strategies.find(s=>s.strategy_id===selected);metrics('portfolio',[['Cash',number(s.cash)],['Market Value',number(s.market_value)],['Equity',number(s.equity)],['Realized PnL (before costs)',number(s.realized_pnl)],['Unrealized PnL',number(s.unrealized_pnl)]]);put('chart',curveHtml(s.curve));metrics('returns',[['Strategy Return',percent(s.return)],['Benchmark Return',percent(s.benchmark_return)],['Excess Return',percent(s.excess_return)]]);put('positions',tableHtml(s.position_details,[['Symbol','symbol'],['Shares','shares',number],['Average Price','average_price',number],['Last Price','last_price',number],['Market Value','market_value',number],['Unrealized PnL','unrealized_pnl',number],['Weight','weight',percent],['Opened Date','opened_date']]));put('orders',tableHtml(r.orders.filter(o=>o.strategy_id===selected),orderColumns));put('fills',tableHtml(r.fills.filter(o=>o.strategy_id===selected),orderColumns));scoreboard();}
 el('strategy').onchange=()=>{selected=el('strategy').value;portfolio();};el('sort').onchange=scoreboard;el('scoreboard').onclick=e=>{const row=e.target.closest('[data-strategy]');if(row){selected=row.dataset.strategy;el('strategy').value=selected;portfolio();}};
 metrics('first-fill',[['First Signal Date',r.forward_validation_start_date],['First Fill Date',r.first_fill_date],['First-Fill Validation',r.first_fill_validation],['Next-Open Semantics',r.next_open_semantics],['Paper Fills (all accounts)',r.fills.length],['Open Positions (all accounts)',r.strategies.reduce((n,s)=>n+s.positions.length,0)]]);
 put('reconciliation',tableHtml(r.reconciliations,[['Strategy','strategy_id'],['Date','date'],['Opening Cash','opening_cash',number],['Purchases','purchases',number],['Costs','transaction_costs',number],['Sales','sales',number],['Ending Cash','ending_cash',number],['Status','status']]));portfolio();el('content').hidden=false;el('state').textContent=`Verified report generated ${r.generated_at} · refreshed every 5 minutes. Data freshness refers to the reported business date.`;el('footer').textContent+=` · Report source: ${r.source}`;
}
if(typeof document!=='undefined'){
 async function refresh(){try{const response=await fetch(`report.json?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw Error(`Report unavailable (${response.status})`);const r=validateReport(await response.json());boot(r);try{const result=await fetch('https://api.github.com/repos/rchu9246/GPT/actions/workflows/v10-forward-shadow-paper.yml/runs?per_page=1');if(!result.ok)throw Error('Status unavailable');const runs=await result.json();const run=runs.workflow_runs?.[0];document.getElementById('automation-status').textContent=run?`Latest automation run: ${String(run.conclusion??run.status).toUpperCase()} · ${run.created_at} · Run ${run.id}. Performance above uses only verified completed evidence.`:'Latest automation run: UNKNOWN';}catch{document.getElementById('automation-status').textContent='Latest automation run: UNKNOWN (GitHub status unavailable). Evidence run status above remains independently validated.';}}catch(e){document.getElementById('content').hidden=true;const state=document.getElementById('state');state.className='error';state.textContent=`V10 evidence unavailable: ${e.message}. No performance is displayed until validation succeeds.`;}}
 refresh();setInterval(refresh,300000);
}
