import { useEffect, useMemo, useState } from "react";
import MetricCard from "../app/MetricCard";
import { formatNum, loadLatestSignals, marketIntelligence, optimizePortfolio, scenarioLoss } from "../lib/v9Data";
import type { SignalRow } from "../types/v9";
export default function RiskCenterV9() {
  const [signals, setSignals] = useState<SignalRow[]>([]); useEffect(() => { loadLatestSignals().then(setSignals).catch(() => setSignals([])); }, []);
  const allocations = useMemo(() => optimizePortfolio(signals), [signals]); const intel = useMemo(() => marketIntelligence(signals), [signals]);
  const loss5 = scenarioLoss(allocations, -5); const loss10 = scenarioLoss(allocations, -10); const loss20 = scenarioLoss(allocations, -20);
  return <section><div className="page-title"><div><div className="eyebrow">ENTERPRISE RISK CONTROL</div><h1>風險控制中心</h1><p>市場風險、壓力測試與部位限制。</p></div></div><div className="cards"><MetricCard label="市場風險" value={formatNum(intel.averageRisk)} note="去重訊號平均 Risk" /><MetricCard label="警示標的" value={intel.warningCount} note="高風險或避開" /><MetricCard label="市場廣度" value={`${Math.round(intel.breadth * 100)}%`} note="偏多標的比例" /><MetricCard label="健康度" value={Math.round(intel.health)} note="綜合風險評分" /></div><div className="grid2"><div className="panel"><div className="panel-title">壓力測試</div><div className="stress-row"><span>市場下跌 5%</span><strong>{loss5.toFixed(2)}%</strong></div><div className="stress-row"><span>市場下跌 10%</span><strong>{loss10.toFixed(2)}%</strong></div><div className="stress-row"><span>市場下跌 20%</span><strong>{loss20.toFixed(2)}%</strong></div></div><div className="panel"><div className="panel-title">風險限制</div><div className="regime"><span>單股權重</span><strong>≤ 20%</strong></div><div className="regime"><span>高風險持股</span><strong>≤ 2 檔</strong></div><div className="regime"><span>停損風險</span><strong>每筆 ≤ 1%</strong></div><div className="regime"><span>最大總曝險</span><strong>{intel.regime === "RISK_ON" ? "85%" : intel.regime === "NEUTRAL" ? "70%" : "50%"}</strong></div></div></div></section>;
}
