import { useEffect, useMemo, useState } from "react";
import MetricCard from "../app/MetricCard";
import Sparkline from "../app/Sparkline";
import { formatNum, formatPct, loadLatestSignals, loadPriceHistory, ratingLabel, technicalSnapshot } from "../lib/v9Data";
import type { PriceRow, SignalRow } from "../types/v9";
export default function StockIntelligenceV9({ symbol, onBack }: { symbol: string; onBack: () => void }) {
  const [prices, setPrices] = useState<PriceRow[]>([]); const [signal, setSignal] = useState<SignalRow | undefined>(); const [error, setError] = useState("");
  useEffect(() => { Promise.all([loadPriceHistory(symbol), loadLatestSignals()]).then(([p, s]) => { setPrices(p); setSignal(s.find((row) => row.symbol === symbol)); }).catch((err: unknown) => setError(err instanceof Error ? err.message : "資料讀取失敗")); }, [symbol]);
  const tech = useMemo(() => technicalSnapshot(prices), [prices]);
  const closes = prices.map((row) => Number(row.close)).filter(Number.isFinite);
  const stop = tech.latest != null && tech.low60 != null ? Math.max(tech.low60, tech.latest * 0.92) : null;
  const target = tech.latest != null ? tech.latest * (signal && signal.score >= 60 ? 1.15 : 1.08) : null;
  const verdict = !signal ? "等待訊號" : signal.rating === "STRONG_BUY" ? "趨勢、分數與風險條件同步，適合列為優先觀察。" : signal.rating === "BUY" ? "結構偏多，但仍需等待量價確認並分批建立部位。" : signal.rating === "WATCH" ? "方向尚未一致，等待 MA20、RSI 與動能改善。" : "防守優先，避免追價並控制既有曝險。";
  return <section><button className="nav active" onClick={onBack}>← 返回指揮中心</button><div className="page-title"><div><div className="eyebrow">STOCK INTELLIGENCE TERMINAL</div><h1>{symbol} {signal?.name ?? ""}</h1><p>價格、技術面、量化因子與交易風險整合。</p></div>{signal && <span className={`rating rating-${signal.rating.toLowerCase()}`}>{ratingLabel(signal.rating)}</span>}</div>{error && <div className="alert">{error}</div>}<div className="cards"><MetricCard label="最新收盤" value={formatNum(tech.latest, 2)} note={prices.length ? prices[prices.length - 1].trade_date : "—"} /><MetricCard label="5 日報酬" value={formatPct(tech.change5)} note="短期動能" /><MetricCard label="20 日報酬" value={formatPct(tech.change20)} note="波段趨勢" /><MetricCard label="RSI 14" value={formatNum(tech.rsi14)} note="超買超賣參考" /></div><div className="grid2"><div className="panel"><div className="panel-title">180 日價格趨勢</div><Sparkline values={closes.slice(-180)} height={280} /></div><div className="panel"><div className="panel-title">技術面快照</div><div className="regime"><span>MA5</span><strong>{formatNum(tech.ma5, 2)}</strong></div><div className="regime"><span>MA20</span><strong>{formatNum(tech.ma20, 2)}</strong></div><div className="regime"><span>MA60</span><strong>{formatNum(tech.ma60, 2)}</strong></div><div className="regime"><span>60 日回撤</span><strong>{formatPct(tech.drawdown60)}</strong></div></div></div><div className="grid2"><div className="panel"><div className="panel-title">量化診斷</div><div className="factor-row"><span>Score</span><i style={{ width: `${signal?.score ?? 0}%` }} /><strong>{formatNum(signal?.score)}</strong></div><div className="factor-row"><span>Trend</span><i style={{ width: `${signal?.trend_score ?? 0}%` }} /><strong>{formatNum(signal?.trend_score)}</strong></div><div className="factor-row"><span>Quality</span><i style={{ width: `${signal?.quality_score ?? 0}%` }} /><strong>{formatNum(signal?.quality_score)}</strong></div><div className="factor-row"><span>Risk</span><i style={{ width: `${signal?.risk_score ?? 0}%` }} /><strong>{formatNum(signal?.risk_score)}</strong></div></div><div className="panel"><div className="panel-title">交易計畫</div><div className="report-action">{verdict}</div><div className="regime"><span>參考停損</span><strong>{formatNum(stop, 2)}</strong></div><div className="regime"><span>參考目標</span><strong>{formatNum(target, 2)}</strong></div><div className="regime"><span>建議權重</span><strong>{signal && signal.risk_score < 40 ? "15%" : signal && signal.risk_score < 60 ? "10%" : "5%"}</strong></div></div></div></section>;
}
