begin;

create table if not exists public.paper_daily_lifecycle_evidence_v92 (
    id bigint generated by default as identity primary key,
    evidence_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE369_PRODUCTION_PAPER_AUTONOMOUS_DAILY_EVIDENCE_LIFECYCLE_GOVERNANCE_ENGINE',

    lifecycle_sequence bigint not null,
    lifecycle_state text not null,
    lifecycle_passed boolean not null default false,

    controller_state text not null default 'UNKNOWN',
    activation_state text not null default 'UNKNOWN',
    qualification_state text not null default 'UNKNOWN',
    runtime_supervision_state text not null default 'UNKNOWN',
    runtime_supervision_score numeric not null default 0,
    master_cycle_state text not null default 'UNKNOWN',

    autonomous_daily_operations_authorized boolean not null default false,
    daily_paper_cycle_executed boolean not null default false,
    safety_revocation_triggered boolean not null default false,

    eligible_signals integer not null default 0,
    sized_candidates integer not null default 0,
    order_intents_created integer not null default 0,
    simulated_fills_created integer not null default 0,
    fills_settled integer not null default 0,

    cash numeric not null default 0,
    market_value numeric not null default 0,
    nav numeric not null default 0,
    realized_pnl numeric not null default 0,
    unrealized_pnl numeric not null default 0,
    open_positions integer not null default 0,

    previous_evidence_sha256 text not null,
    source_controller_evidence_sha256 text,
    source_master_evidence_sha256 text,
    reason_codes jsonb not null default '[]'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ck_phase369_lifecycle_state check (
        lifecycle_state in (
            'PASS',
            'PASS_WITH_OBSERVATION',
            'BLOCKED',
            'FAIL_CLOSED'
        )
    ),
    constraint ck_phase369_paper_only check (paper_only = true),
    constraint ck_phase369_no_broker_api check (broker_api_used = false),
    constraint ck_phase369_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase369_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase369_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase369_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase369_fail_closed check (fail_closed_policy = true)
);

create unique index if not exists uq_paper_daily_lifecycle_evidence_v92_portfolio_date
    on public.paper_daily_lifecycle_evidence_v92 (portfolio_id, evidence_date);

create unique index if not exists uq_paper_daily_lifecycle_evidence_v92_portfolio_sequence
    on public.paper_daily_lifecycle_evidence_v92 (portfolio_id, lifecycle_sequence);

create index if not exists ix_paper_daily_lifecycle_evidence_v92_state_date
    on public.paper_daily_lifecycle_evidence_v92 (lifecycle_state, evidence_date desc);

create table if not exists public.paper_daily_lifecycle_evidence_audit_v92 (
    id bigint generated by default as identity primary key,
    evidence_date date not null,
    portfolio_id text not null,
    strategy_version text not null default 'V9.1',
    contract text not null default 'PHASE369_PRODUCTION_PAPER_AUTONOMOUS_DAILY_EVIDENCE_LIFECYCLE_GOVERNANCE_ENGINE',

    lifecycle_sequence bigint not null,
    lifecycle_state text not null,
    lifecycle_passed boolean not null default false,

    controller_state text not null default 'UNKNOWN',
    activation_state text not null default 'UNKNOWN',
    qualification_state text not null default 'UNKNOWN',
    runtime_supervision_state text not null default 'UNKNOWN',
    runtime_supervision_score numeric not null default 0,
    master_cycle_state text not null default 'UNKNOWN',

    autonomous_daily_operations_authorized boolean not null default false,
    daily_paper_cycle_executed boolean not null default false,
    safety_revocation_triggered boolean not null default false,

    eligible_signals integer not null default 0,
    sized_candidates integer not null default 0,
    order_intents_created integer not null default 0,
    simulated_fills_created integer not null default 0,
    fills_settled integer not null default 0,

    cash numeric not null default 0,
    market_value numeric not null default 0,
    nav numeric not null default 0,
    realized_pnl numeric not null default 0,
    unrealized_pnl numeric not null default 0,
    open_positions integer not null default 0,

    previous_evidence_sha256 text not null,
    source_controller_evidence_sha256 text,
    source_master_evidence_sha256 text,
    reason_codes jsonb not null default '[]'::jsonb,
    evidence_document jsonb not null default '{}'::jsonb,

    paper_only boolean not null default true,
    broker_api_used boolean not null default false,
    broker_credentials_used boolean not null default false,
    broker_order_submission_enabled boolean not null default false,
    real_money_trading_enabled boolean not null default false,
    live_money_release_authorized boolean not null default false,
    fail_closed_policy boolean not null default true,

    evidence_sha256 text not null,
    created_at timestamptz not null default now(),

    constraint ck_phase369_audit_paper_only check (paper_only = true),
    constraint ck_phase369_audit_no_broker_api check (broker_api_used = false),
    constraint ck_phase369_audit_no_broker_credentials check (broker_credentials_used = false),
    constraint ck_phase369_audit_no_broker_submission check (broker_order_submission_enabled = false),
    constraint ck_phase369_audit_no_real_money check (real_money_trading_enabled = false),
    constraint ck_phase369_audit_no_live_release check (live_money_release_authorized = false),
    constraint ck_phase369_audit_fail_closed check (fail_closed_policy = true)
);

create index if not exists ix_paper_daily_lifecycle_evidence_audit_v92_portfolio_created
    on public.paper_daily_lifecycle_evidence_audit_v92 (portfolio_id, created_at desc);

alter table public.paper_daily_lifecycle_evidence_v92 enable row level security;
alter table public.paper_daily_lifecycle_evidence_audit_v92 enable row level security;

comment on table public.paper_daily_lifecycle_evidence_v92 is
'GPT Quant V9.2 Phase 3.6.9 canonical daily autonomous lifecycle evidence state. Paper-only and fail-closed.';

comment on table public.paper_daily_lifecycle_evidence_audit_v92 is
'GPT Quant V9.2 Phase 3.6.9 immutable-style lifecycle evidence audit with SHA256 chain.';

-- Ask PostgREST to reload schema metadata after DDL.
notify pgrst, 'reload schema';

commit;