create table if not exists public.portfolios (
  id uuid primary key default gen_random_uuid(),
  name varchar(100) not null,
  description text,
  initial_capital numeric not null default 1000000,
  cash_balance numeric not null default 1000000,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.portfolio_positions (
  id bigint generated by default as identity primary key,
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  quantity integer not null check (quantity >= 0),
  average_cost numeric not null check (average_cost >= 0),
  current_price numeric,
  market_value numeric,
  unrealized_pnl numeric,
  unrealized_return numeric,
  weight numeric,
  opened_at date not null default current_date,
  updated_at timestamptz not null default now(),
  unique (portfolio_id, stock_id)
);

create table if not exists public.portfolio_snapshots (
  id bigint generated by default as identity primary key,
  portfolio_id uuid not null references public.portfolios(id) on delete cascade,
  snapshot_date date not null,
  cash_balance numeric not null,
  market_value numeric not null,
  total_equity numeric not null,
  daily_return numeric,
  cumulative_return numeric,
  max_drawdown numeric,
  volatility_20d numeric,
  var_95 numeric,
  created_at timestamptz not null default now(),
  unique (portfolio_id, snapshot_date)
);

create table if not exists public.daily_reports (
  id bigint generated by default as identity primary key,
  report_date date not null unique,
  market_state varchar(30) not null,
  market_score numeric not null,
  strategy_health numeric not null,
  top_signals jsonb not null default '[]'::jsonb,
  risk_flags jsonb not null default '[]'::jsonb,
  summary text not null,
  action_plan text not null,
  generated_by varchar(50) not null default 'V5-RULE-ENGINE',
  created_at timestamptz not null default now()
);

create table if not exists public.risk_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null unique,
  average_score numeric not null,
  bullish_ratio numeric not null,
  average_volatility numeric not null,
  average_drawdown numeric,
  risk_level varchar(20) not null,
  var_95 numeric,
  concentration_risk numeric,
  created_at timestamptz not null default now()
);

create index if not exists portfolio_positions_portfolio_idx
  on public.portfolio_positions(portfolio_id);

create index if not exists portfolio_snapshots_portfolio_date_idx
  on public.portfolio_snapshots(portfolio_id, snapshot_date desc);

create index if not exists daily_reports_date_idx
  on public.daily_reports(report_date desc);

alter table public.portfolios enable row level security;
alter table public.portfolio_positions enable row level security;
alter table public.portfolio_snapshots enable row level security;
alter table public.daily_reports enable row level security;
alter table public.risk_snapshots enable row level security;

drop policy if exists "public read portfolios" on public.portfolios;
create policy "public read portfolios"
  on public.portfolios for select to anon, authenticated using (true);

drop policy if exists "public read portfolio positions" on public.portfolio_positions;
create policy "public read portfolio positions"
  on public.portfolio_positions for select to anon, authenticated using (true);

drop policy if exists "public read portfolio snapshots" on public.portfolio_snapshots;
create policy "public read portfolio snapshots"
  on public.portfolio_snapshots for select to anon, authenticated using (true);

drop policy if exists "public read daily reports" on public.daily_reports;
create policy "public read daily reports"
  on public.daily_reports for select to anon, authenticated using (true);

drop policy if exists "public read risk snapshots" on public.risk_snapshots;
create policy "public read risk snapshots"
  on public.risk_snapshots for select to anon, authenticated using (true);

insert into public.portfolios (name, description, initial_capital, cash_balance)
select
  'V5 Professional Demo',
  'GPT Quant V5 專業模擬投資組合',
  1000000,
  1000000
where not exists (
  select 1 from public.portfolios where name = 'V5 Professional Demo'
);

create or replace view public.latest_strategy_performance as
select distinct on (strategy_version)
  id,
  strategy_version,
  created_at,
  total_return,
  annual_return,
  win_rate,
  profit_factor,
  max_drawdown,
  sharpe_ratio,
  sortino_ratio,
  total_trades,
  status
from public.backtest_runs
where status = 'COMPLETED'
order by strategy_version, created_at desc;

grant select on public.latest_strategy_performance to anon, authenticated;
