-- GPT Quant V13 AutoTrader backend schema.
-- Run manually in Supabase before enabling the server-side paper trader.

create table if not exists public.autotrader_configs_v13 (
  id bigint generated by default as identity primary key,
  account_name text not null default 'paper-main',
  mode text not null default 'PAPER' check (mode in ('PAPER','APPROVAL','LIVE_LOCKED')),
  enabled boolean not null default false,
  kill_switch boolean not null default false,
  starting_cash numeric not null default 1000000,
  reserve_cash_pct numeric not null default 30,
  max_positions integer not null default 5,
  max_position_pct numeric not null default 15,
  min_score numeric not null default 40,
  max_risk_score numeric not null default 60,
  require_approval boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trade_orders_v13 (
  id uuid primary key default gen_random_uuid(),
  account_name text not null default 'paper-main',
  symbol text not null,
  side text not null check (side in ('BUY','SELL')),
  quantity integer not null check (quantity > 0),
  reference_price numeric not null,
  notional numeric not null,
  score numeric,
  risk_score numeric,
  confidence numeric,
  reason text,
  mode text not null default 'PAPER',
  status text not null default 'PROPOSED' check (status in ('PROPOSED','APPROVED','REJECTED','FILLED','CANCELLED','FAILED')),
  broker_order_id text,
  error_message text,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  filled_at timestamptz
);

create table if not exists public.paper_positions_v13 (
  account_name text not null default 'paper-main',
  symbol text not null,
  quantity integer not null default 0,
  average_price numeric not null default 0,
  last_price numeric not null default 0,
  market_value numeric not null default 0,
  unrealized_pnl numeric not null default 0,
  updated_at timestamptz not null default now(),
  primary key (account_name, symbol)
);

alter table public.autotrader_configs_v13 enable row level security;
alter table public.trade_orders_v13 enable row level security;
alter table public.paper_positions_v13 enable row level security;

-- No anonymous write policies are created intentionally.
-- The server-side agent must use SUPABASE_SERVICE_ROLE_KEY.
