from __future__ import annotations

import math
import os
import uuid
from datetime import date, datetime, timezone
from statistics import mean
from typing import Any

from enterprise2.client import SupabaseRestClient

RUN_DATE = os.environ.get("QUANT_RUN_DATE", date.today().isoformat())
ENGINE_VERSION = "5.4.0"


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


def num(value: Any, default: float = 0.0) -> float:
    try:
        value = float(value)
        return value if math.isfinite(value) else default
    except (TypeError, ValueError):
        return default


def read(client, table: str, query: str, required: bool = False):
    try:
        rows = client.get(table, query)
        return rows if isinstance(rows, list) else []
    except Exception:
        if required:
            raise
        return []


def next_version(client) -> str:
    rows = read(client, "parameter_versions_v54", "order=created_at.desc&limit=100")
    versions = []
    for row in rows:
        value = str(row.get("version_no") or "")
        if value.startswith("5.4-candidate-"):
            try:
                versions.append(int(value.rsplit("-", 1)[1]))
            except ValueError:
                pass
    return f"5.4-candidate-{max(versions, default=0) + 1:04d}"


def main() -> None:
    client = SupabaseRestClient()
    run_id = str(uuid.uuid4())

    proposals = read(
        client,
        "agent_weight_adjustments_v53",
        "proposal_status=eq.PROPOSED&auto_apply_enabled=eq.false"
        "&order=proposal_date.desc,agent_key.asc&limit=500",
        required=True,
    )

    min_evidence = int(num(os.getenv("ENTERPRISE54_MIN_EVIDENCE_COUNT"), 5))
    min_reliability = num(os.getenv("ENTERPRISE54_MIN_RELIABILITY_SCORE"), 60)
    max_change = num(os.getenv("ENTERPRISE54_MAX_WEIGHT_CHANGE_PCT"), 10)
    max_calibration_error = num(
        os.getenv("ENTERPRISE54_MAX_CALIBRATION_ERROR"), 25
    )

    created = safety_count = shadow_count = review_ready = rejected = 0
    candidate_items = []
    proposal_ids = []
    reliabilities = []

    for source in proposals:
        agent = str(source.get("agent_key") or "UNKNOWN")
        source_id = str(source["id"])
        current = num(source.get("current_weight"), 1)
        proposed = num(source.get("proposed_weight"), current)
        change_pct = num(source.get("adjustment_pct"), 0)
        evidence_count = int(num(source.get("evidence_count"), 0))
        reliability = num(source.get("reliability_score"), 0)
        calibration = num(source.get("calibration_score"), 0)
        calibration_error = 100 - calibration
        reliabilities.append(reliability)

        proposal_key = f"AGENT_WEIGHT:{source_id}"
        client.upsert(
            "adaptive_proposals_v54",
            {
                "proposal_date": RUN_DATE,
                "proposal_key": proposal_key,
                "proposal_type": "AGENT_WEIGHT",
                "proposal_title": f"Agent Weight Proposal: {agent}",
                "proposal_description": source.get("adjustment_reason")
                or "Generated by Enterprise 5.3.",
                "proposal_source": "agent_weight_adjustments_v53",
                "source_record_id": source_id,
                "status": "VALIDATING",
                "priority": "HIGH" if evidence_count >= 20 else "MEDIUM",
                "risk_level": "HIGH" if abs(change_pct) > max_change else "LOW",
                "evidence_count": evidence_count,
                "expected_benefit": "Improve Agent reliability and calibration.",
                "paper_only": True,
                "automatic_application_enabled": False,
                "live_trading_impact": False,
                "metadata": {"run_id": run_id, "engine_version": ENGINE_VERSION},
            },
            "proposal_date,proposal_key",
        )
        row = read(
            client,
            "adaptive_proposals_v54",
            f"proposal_date=eq.{RUN_DATE}&proposal_key=eq.{proposal_key}&limit=1",
            required=True,
        )[0]
        proposal_id = str(row["id"])
        proposal_ids.append(proposal_id)
        created += 1

        client.upsert(
            "proposal_items_v54",
            {
                "proposal_id": proposal_id,
                "item_key": agent,
                "item_type": "AGENT_WEIGHT",
                "target_name": agent,
                "current_value": current,
                "proposed_value": proposed,
                "change_pct": change_pct,
                "expected_benefit": f"Reliability {reliability:.2f}.",
                "risk_level": "HIGH" if abs(change_pct) > max_change else "LOW",
                "evidence": {"source_id": source_id},
            },
            "proposal_id,item_key",
        )

        gates = {
            "MINIMUM_EVIDENCE": (evidence_count >= min_evidence, evidence_count, min_evidence),
            "MINIMUM_RELIABILITY": (reliability >= min_reliability, reliability, min_reliability),
            "MAXIMUM_WEIGHT_CHANGE": (abs(change_pct) <= max_change, abs(change_pct), max_change),
            "MAXIMUM_CALIBRATION_ERROR": (
                calibration_error <= max_calibration_error,
                calibration_error,
                max_calibration_error,
            ),
            "LIVE_TRADING_IMPACT": (True, 0, 0),
            "ROLLBACK_AVAILABLE": (True, 1, 1),
        }

        for gate, (passed, observed, threshold) in gates.items():
            client.upsert(
                "safety_gate_results_v54",
                {
                    "proposal_id": proposal_id,
                    "gate_key": gate,
                    "gate_status": "PASS" if passed else "FAIL",
                    "passed": passed,
                    "observed_value": observed,
                    "threshold_value": threshold,
                    "severity": "INFO" if passed else "CRITICAL",
                    "message": f"{gate}: {observed} / {threshold}",
                    "evidence": {"paper_only": True},
                },
                "proposal_id,gate_key",
            )
            safety_count += 1

        overall_pass = all(value[0] for value in gates.values())
        stability = min(
            100,
            reliability * 0.45
            + calibration * 0.35
            + min(100, evidence_count * 5) * 0.20,
        )
        shadow_pass = overall_pass and stability >= 60

        client.upsert(
            "shadow_simulations_v54",
            {
                "proposal_id": proposal_id,
                "simulation_date": RUN_DATE,
                "simulation_type": "PAPER_REPLAY_PROXY",
                "sample_size": evidence_count,
                "baseline_score": current * reliability,
                "candidate_score": proposed * reliability,
                "stability_score": stability,
                "risk_regression_score": min(
                    100, abs(change_pct) / max(max_change, 1) * 100
                ),
                "passed": shadow_pass,
                "simulation_status": "PASS" if shadow_pass else "FAILED",
                "summary": f"{agent}: stability={stability:.2f}",
                "evidence": {"realized_backtest_available": False},
            },
            "proposal_id,simulation_date,simulation_type",
        )
        shadow_count += 1

        client.upsert(
            "adaptive_reviews_v54",
            {
                "proposal_id": proposal_id,
                "review_stage": "AUTOMATED_GOVERNANCE",
                "review_result": (
                    "READY_FOR_HUMAN_REVIEW"
                    if shadow_pass
                    else "REJECTED_BY_SAFETY_GATE"
                ),
                "review_comment": "Manual approval required.",
                "reviewer": "ENTERPRISE54_ADAPTIVE_GOVERNANCE",
                "review_time": now(),
                "manual_approval_required": True,
                "automatic_application_enabled": False,
                "evidence": {"safety_pass": overall_pass, "shadow_pass": shadow_pass},
            },
            "proposal_id,review_stage",
        )

        client.patch(
            "adaptive_proposals_v54",
            f"id=eq.{proposal_id}",
            {
                "status": "READY_FOR_REVIEW" if shadow_pass else "VALIDATION_FAILED",
                "safety_gate_passed": overall_pass,
                "shadow_test_passed": shadow_pass,
            },
        )

        if shadow_pass:
            review_ready += 1
            candidate_items.append(
                {
                    "proposal_id": proposal_id,
                    "agent_key": agent,
                    "current_weight": current,
                    "proposed_weight": proposed,
                    "reliability": reliability,
                    "calibration": calibration,
                }
            )
        else:
            rejected += 1

    version_no = None
    rollback_ready = False
    if candidate_items:
        version_no = next_version(client)
        client.upsert(
            "parameter_versions_v54",
            {
                "version_no": version_no,
                "version_type": "AGENT_WEIGHT_SET",
                "parameter_group": "MULTI_AGENT_COUNCIL",
                "version_status": "CANDIDATE",
                "description": "Manual approval required.",
                "source_run_id": run_id,
                "source_proposals": proposal_ids,
                "active": False,
                "paper_only": True,
                "automatic_application_enabled": False,
                "rollback_ready": True,
                "configuration": {"engine_version": ENGINE_VERSION},
            },
            "version_no",
        )
        version = read(
            client,
            "parameter_versions_v54",
            f"version_no=eq.{version_no}&limit=1",
            required=True,
        )[0]
        version_id = str(version["id"])

        for item in candidate_items:
            client.upsert(
                "agent_weight_versions_v54",
                {
                    "version_id": version_id,
                    "agent_key": item["agent_key"],
                    "weight": item["proposed_weight"],
                    "previous_weight": item["current_weight"],
                    "effective_date": None,
                    "version_status": "CANDIDATE",
                    "source_proposal_id": item["proposal_id"],
                    "reliability_score": item["reliability"],
                    "calibration_score": item["calibration"],
                    "active": False,
                    "automatic_application_enabled": False,
                },
                "version_id,agent_key",
            )

        client.upsert(
            "rollback_snapshots_v54",
            {
                "version_id": version_id,
                "snapshot_date": RUN_DATE,
                "snapshot_type": "PRE_APPLICATION",
                "snapshot_status": "READY",
                "configuration_snapshot": {
                    item["agent_key"]: item["current_weight"]
                    for item in candidate_items
                },
                "rollback_instructions": "Manual rollback only.",
                "automatic_rollback_enabled": False,
                "paper_only": True,
            },
            "version_id,snapshot_type",
        )
        rollback_ready = True

    status = "PASS" if candidate_items and rejected == 0 else "WARNING"
    summary = (
        f"Created {created} proposals, {shadow_count} shadow tests, "
        f"{review_ready} ready for review, {rejected} rejected."
    )

    client.upsert(
        "adaptive_metrics_v54",
        {
            "metric_date": RUN_DATE,
            "total_proposals": created,
            "proposal_items": created,
            "safety_checks": safety_count,
            "shadow_tests": shadow_count,
            "ready_for_review": review_ready,
            "candidate_versions": 1 if version_no else 0,
            "approved_versions": 0,
            "rejected_proposals": rejected,
            "rollback_snapshots": 1 if rollback_ready else 0,
            "average_reliability": mean(reliabilities) if reliabilities else 0,
            "automatic_applications": 0,
            "diagnostics": {"run_id": run_id, "version_no": version_no},
        },
        "metric_date",
    )

    client.upsert(
        "adaptive_status_v54",
        {
            "status_date": RUN_DATE,
            "overall_status": status,
            "current_candidate_version": version_no,
            "proposals_generated": created,
            "proposal_items_generated": created,
            "safety_checks_run": safety_count,
            "shadow_tests_run": shadow_count,
            "ready_for_review": review_ready,
            "candidate_versions": 1 if version_no else 0,
            "approved_versions": 0,
            "rejected_proposals": rejected,
            "rollback_ready": rollback_ready,
            "automatic_proposal_application_enabled": False,
            "automatic_agent_weight_update_enabled": False,
            "automatic_risk_parameter_update_enabled": False,
            "automatic_rollback_enabled": False,
            "live_trading_enabled": False,
            "blockers": [],
            "warnings": [] if proposals else ["NO_PENDING_V53_PROPOSALS"],
            "summary": summary,
            "diagnostics": {"run_id": run_id, "engine_version": ENGINE_VERSION},
        },
        "status_date",
    )

    print(summary)
    print(f"Enterprise 5.4 Adaptive Governance status: {status}")


if __name__ == "__main__":
    main()
