create table if not exists public.daily_research_reports (
  id bigint generated by default as identity primary key,
  report_date date not null unique,
  market_regime text,
  summary text not null,
  action_plan text,
  top_symbols jsonb not null default '[]'::jsonb,
  risk_symbols jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.portfolio_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null,
  strategy_version text not null,
  holdings jsonb not null default '[]'::jsonb,
  cash_weight numeric,
  expected_return numeric,
  expected_volatility numeric,
  created_at timestamptz not null default now(),
  unique(snapshot_date, strategy_version)
);

alter table public.daily_research_reports enable row level security;
alter table public.portfolio_snapshots enable row level security;

drop policy if exists "public read daily research reports" on public.daily_research_reports;
create policy "public read daily research reports"
on public.daily_research_reports for select using (true);

drop policy if exists "public read portfolio snapshots" on public.portfolio_snapshots;
create policy "public read portfolio snapshots"
on public.portfolio_snapshots for select using (true);
